### ISSUE TITLE
针对分好词的 contextualized embedding

### ISSUE THREAD

**Issue by allanj** [PaddlePaddle/ERNIE#109]
有针对分好词的 contextualized embedding 能用吗？

**Comment by tianxin1860** [comment]
请稍微详细描述一下你的需求？

**Comment by allanj** [comment]
就是对一个分好词的句子，举个例子：

库里拿了NBA总冠军。 分好词是 库里 拿 了 NBA 总冠军

可以直接得到 
库里 vector
拿 vector
了 vector
NBA vector
总冠军 vector

这样的vector。而不是每个character的vector。
请问这样有吗

**Comment by tianxin1860** [comment]
经过 ERNIE 网络编码之后可以得到每个 character 的 vector, 你可以基于 character 的 vector 自己进行 pooling 得到词粒度的 vector

**Comment by allanj** [comment]
明白。。谢谢🙏
