### ISSUE TITLE
paddle fliud1.3 fluid.ParallelExecutor killed 

### ISSUE THREAD

**Issue by shouonga** [PaddlePaddle/ERNIE#112]
if args.do_train:
        print("start exec_strategy!!!")
        exec_strategy = fluid.ExecutionStrategy()
        exec_strategy.use_experimental_executor = args.use_fast_executor
        exec_strategy.num_threads = 4
        exec_strategy.num_iteration_per_drop_scope = args.num_iteration_per_drop_scope
        train_exe = fluid.ParallelExecutor(  #运行到此处直接被killed
            use_cuda=args.use_cuda,
            loss_name=loss.name,
            exec_strategy=exec_strategy,
            main_program=train_program)
        #train_exe = fluid.Executor(fluid.CPUPlace())
        train_pyreader.decorate_tensor_provider(train_data_generator)

只显示killed，没有任何别的错误

**Comment by qingqing01** [comment]
@shouonga 最好用1.3.1版本以上， 另外，可以通过设置以下环境变量，搜索错误log看下有没有详细的信息:

```
export GLOG_v=4
export GLOG_logtostderr=1
```
