### ISSUE TITLE
unhandled cuda error 多卡跑pretrain的时候，cuDNN和NCCL都装了

### ISSUE THREAD

**Issue by fyubang** [PaddlePaddle/ERNIE#113]
```
W0429 09:42:47.633998 34675 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0429 09:42:47.638882 34675 device_context.cc:269] device: 0, cuDNN Version: 7.0.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0429 09:42:51.247493 34675 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
Traceback (most recent call last):
  File "./train.py", line 357, in <module>
    train(args)
  File "./train.py", line 272, in train
    trainer_id=nccl2_trainer_id)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/compiler.py", line 307, in _compile
    scope=self._scope)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: unhandled cuda error at [/paddle/paddle/fluid/platform/nccl_helper.h:113]
```
python 3.5
cuda 9.0
在跑ernie的多卡与训练的时候报的错。cudnn和nccl2都装了，这个报错太不明显了。大家有遇到吗？

**Comment by Biaocsu** [comment]
@fyubang  我今天运行报错和你一样的，不知道什么原因，明明检测的时候安装成功了：
`>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0529 10:32:16.306861 29367 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0529 10:32:16.626080 29367 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0529 10:32:16.626128 29367 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
`
报错如下：
`attention_probs_dropout_prob: 0.1
hidden_act: relu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
max_position_embeddings: 513
num_attention_heads: 12
num_hidden_layers: 12
type_vocab_size: 2
vocab_size: 18000
------------------------------------------------
Device count: 1
Num train examples: 20864
Max train steps: 3912
Num warmup steps: 0
memory_optimize is deprecated. Use CompiledProgram and Executor
W0529 11:36:42.364841 29500 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0529 11:36:42.367054 29500 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0529 11:36:42.367071 29500 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Load pretraining parameters from ./model/params.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0529 11:36:42.660814 29500 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
Traceback (most recent call last):
  File "run_sequence_labeling.py", line 283, in <module>
    main(args)
  File "run_sequence_labeling.py", line 176, in main
    main_program=train_program)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 307, in _compile
    scope=self._scope)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: unhandled cuda error at [/paddle/paddle/fluid/platform/nccl_helper.h:113]
PaddlePaddle Call Stacks: 
0       0x7fbcbea1bd00p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fbcbea1c079p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fbcbebcc150p paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,`

**Comment by Biaocsu** [comment]
@fyubang  我出现和你一样的错误，但安装检测成功了。
安装检测：
`>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0529 10:32:16.306861 29367 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0529 10:32:16.626080 29367 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0529 10:32:16.626128 29367 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now`
fine-tuning报错:
`Device count: 1
Num train examples: 20864
Max train steps: 3912
Num warmup steps: 0
memory_optimize is deprecated. Use CompiledProgram and Executor
W0529 11:36:42.364841 29500 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0529 11:36:42.367054 29500 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0529 11:36:42.367071 29500 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Load pretraining parameters from ./model/params.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0529 11:36:42.660814 29500 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
Traceback (most recent call last):
  File "run_sequence_labeling.py", line 283, in <module>
    main(args)
  File "run_sequence_labeling.py", line 176, in main
    main_program=train_program)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 307, in _compile
    scope=self._scope)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: unhandled cuda error at [/paddle/paddle/fluid/platform/nccl_helper.h:113]
PaddlePaddle Call Stacks: 
0       0x7fbcbea1bd00p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fbcbea1c079p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fbcbebcc150p paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::`

**Comment by Biaocsu** [comment]
@fyubang 我出现和你一样的错误，但检测安装成功了，
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0529 10:32:16.306861 29367 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0529 10:32:16.626080 29367 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0529 10:32:16.626128 29367 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

**Comment by fyubang** [comment]
> @fyubang 我出现和你一样的错误，但检测安装成功了，
> 
> > > > import paddle.fluid
> > > > paddle.fluid.install_check.run_check()
> > > > Running Verify Fluid Program ...
> > > > W0529 10:32:16.306861 29367 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
> > > > W0529 10:32:16.626080 29367 device_context.cc:269] device: 0, cuDNN Version: 7.0.
> > > > W0529 10:32:16.626128 29367 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
> > > > Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

我最后的解决办法是安装cuda 8.0

**Comment by Biaocsu** [comment]
@fyubang 那你知道cuda9.*是什么原因引起的吗？弄了好长时间还是没办法解决，崩溃。最主要的时按安装教程来我已经安装成功了

**Comment by fyubang** [comment]
> @fyubang 那你知道cuda9.*是什么原因引起的吗？弄了好长时间还是没办法解决，崩溃。最主要的时按安装教程来我已经安装成功了

不清楚哎
