### ISSUE TITLE
funetuning 时候，任务数据下载不一致

### ISSUE THREAD

**Issue by fw339wj** [PaddlePaddle/ERNIE#119]
对应的数据链接只下载到一个文本文件，无法执行readme.md中所描述的“将下载的任务数据解压到 ${TASK_DATA_PATH} 路径下，${TASK_DATA_PATH} 路径包含 LCQMC、XNLI、MSRA-NER、ChnSentCorp、 nlpcc-dbqa 5个任务的训练数据和测试数据；”

**Comment by huntzhan** [comment]
我没问题：
https://ernie.bj.bcebos.com/task_data.tgz

**Comment by fw339wj** [comment]
这个没有问题，谢谢您。


| |
毋杰
|
|
fw339wj@126.com
|
签名由网易邮箱大师定制
在2019年5月5日 23:24，Hunt Zhan<notifications@github.com> 写道：

我没问题：
https://ernie.bj.bcebos.com/task_data.tgz

**Comment by dingjieliu** [comment]
请问大家这个链接还能用吗？我现在打不开了
