### ISSUE TITLE
CPU模式grpc超时

### ISSUE THREAD

**Issue by superxiaoyu** [PaddlePaddle/ERNIE#126]
木有GPU资源，想用CPU MPI集群跑来试试，预期能跑无非是慢一点（local单trainer能跑通），但报grpc超时，FLAGS_rpc_deadline已经设的很大，看上去是访问pserver的问题？

F0430 17:17:47.899032 30175 grpc_client.cc:408] BatchBarrierRPC name:[BATCH_BARRIER@RECV], ep:[ip:port], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:

**Comment by seiriosPlus** [comment]
在cloud上跑的？ 能提供URL么

**Comment by guoshengCS** [comment]
这个可否提供下任务的URL我们看下
