### ISSUE TITLE
ERNIE:CPU版跑ChnSentiCorp报Windows not support stack backtrace yet.

### ISSUE THREAD

**Issue by shenlan211314** [PaddlePaddle/ERNIE#127]
开始是内存不足，调整batch_size为2后，内存应该是能满足（实际8G）。但是后面又报错了。
运行环境是win10，CPU，内存8G，paddlepaddle 1.4.1。
---
Theoretical memory usage in training: 3420.067 - 3582.927 MB
warm validate or test
Load pretraining parameters from MODEL_PATH/params.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified
executor. Example can be found in compiler.py.
W0506 20:38:55.854854 15620 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid us
ing the `OriginProgram()` method!
Traceback (most recent call last):
  File "run_classifier.py", line 307, in <module>
    main(args)
  File "run_classifier.py", line 201, in main
    main_program=train_program)
  File "D:\python3\lib\site-packages\paddle\fluid\parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "D:\python3\lib\site-packages\paddle\fluid\compiler.py", line 307, in _compile
    scope=self._scope)
  File "D:\python3\lib\site-packages\paddle\fluid\compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: Fail to allocate CPU memory: size = 263382656 . at [D:\1.4.1\paddle\paddle\fluid\memory\detail\system_allocator.cc:56]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.

**Comment by shenlan211314** [comment]
CPU版本是不是不能用ParallelExecutor？

**Comment by shenlan211314** [comment]
目前换位GPU，也是报：paddle.fluid.core.EnforceNotMet

win10+GTX1070+Python3.6+CUDA8+CUDNN7+paddlepaddle_gpu-1.4.1-cp36-cp36m-win_amd64.whl

**Comment by Dkhaha** [comment]
> 目前换位GPU，也是报：paddle.fluid.core.EnforceNotMet
> 
> win10+GTX1070+Python3.6+CUDA8+CUDNN7+paddlepaddle_gpu-1.4.1-cp36-cp36m-win_amd64.whl

> ## 开始是内存不足，调整batch_size为2后，内存应该是能满足（实际8G）。但是后面又报错了。
> 运行环境是win10，CPU，内存8G，paddlepaddle 1.4.1。
> Theoretical memory usage in training: 3420.067 - 3582.927 MB
> warm validate or test
> Load pretraining parameters from MODEL_PATH/params.
> ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified
> executor. Example can be found in compiler.py.
> W0506 20:38:55.854854 15620 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid us
> ing the `OriginProgram()` method!
> Traceback (most recent call last):
> File "run_classifier.py", line 307, in 
> main(args)
> File "run_classifier.py", line 201, in main
> main_program=train_program)
> File "D:\python3\lib\site-packages\paddle\fluid\parallel_executor.py", line 134, in **init**
> self._compiled_program._compile(place=self._place, scope=self._scope)
> File "D:\python3\lib\site-packages\paddle\fluid\compiler.py", line 307, in _compile
> scope=self._scope)
> File "D:\python3\lib\site-packages\paddle\fluid\compiler.py", line 278, in _compile_data_parallel
> self._exec_strategy, self._build_strategy, self._graph)
> paddle.fluid.core.EnforceNotMet: Fail to allocate CPU memory: size = 263382656 . at [D:\1.4.1\paddle\paddle\fluid\memory\detail\system_allocator.cc:56]
> PaddlePaddle Call Stacks:
> Windows not support stack backtrace yet.

我也有同样的问题，不知道解决了么
