### ISSUE TITLE
用自己数据多卡做ERNIE语言模型任务的fine tune的时候，没有规律卡在某一步

### ISSUE THREAD

**Issue by fyubang** [PaddlePaddle/ERNIE#129]
多卡做ernie语言模型任务的fine tune的时候，经常遇到，运行到一定步数就卡住的情况，卡住的时候，多卡中的部分卡依旧100%，部分卡0%。并且卡的步数没有规律。同步并不报错，怀疑是nccl的问题。运行坏境是8卡p40。
卡住时，gpu这样：
<img width="523" alt="github1" src="https://user-images.githubusercontent.com/25549892/57455387-9a8eea00-729d-11e9-90f5-245652a1e218.png">
日志：
<img width="1279" alt="github2" src="https://user-images.githubusercontent.com/25549892/57455393-9cf14400-729d-11e9-9971-5b9f57531147.png">
脚本的超参：
![github3](https://user-images.githubusercontent.com/25549892/57455400-9f539e00-729d-11e9-8a3e-6f8eca5b8dd7.png)
挺多人遇到类似问题的。

**Comment by kuke** [comment]
@fyubang 请问paddle版本是什么呢，可以多加点日志初步定位一下hang在何处了么

**Comment by fyubang** [comment]
> @fyubang 请问paddle版本是什么呢，可以多加点日志初步定位一下hang在何处了么

1.3.1，没有别的日志了，hang的位置没什么规律，大部分都是训练的时候hang住

**Comment by LukeALee** [comment]
复议，P40, cuda 9.0，cudnn 7.0;
源码run_classifier.py
用以下命令指定卡数：
 idle_gpu=3,4,5,6
 export CUDA_VISIBLE_DEVICES=${idle_gpu}
数据量 records 24675:
epoch >=4, batchsize = 24，三张卡会卡住
epoch =5, batchsize =36，四张卡也会卡住
找不出原因，也不报错，调的崩溃
