### ISSUE TITLE
i tried to do text similarity on LCQMC, but for BERT, i can't get comparable results

### ISSUE THREAD

**Issue by yyht** [PaddlePaddle/ERNIE#130]
I had tried to re-produce results on LCQMC using BERT. I can't achieve 0.87 accuracy, just 0.85. is there something wrong ?

**Comment by Olivia-xu** [comment]
hi, i had tried to re_produce results on LCQMC using BERT, i can just achieve 0.50 accuracy. From the results, the BERT model does not distinguish well between samples. 
So I want to ask you what parameters you use. thank you very much
