### ISSUE TITLE
训练任务killed

### ISSUE THREAD

**Issue by MaxLingwei** [PaddlePaddle/ERNIE#134]
下载了bert的demo，在开发机本地运行train.sh，任务直接被killed
![image](https://user-images.githubusercontent.com/14048056/57620381-30d35080-75bb-11e9-8b5d-7e991a8177ba.png)

**Comment by seiriosPlus** [comment]
export GLOG_v=4

**Comment by seiriosPlus** [comment]
看一下日志

**Comment by Superjomn** [comment]
应该是内存占用过大，被系统kill了

**Comment by jiayouff** [comment]
有可能是机器的内存较小，可以试试把batchsize改小一些，试试能不能跑起来。

**Comment by wang154917190** [comment]
应该是你机器内存较小导致的，你可以降低max_seq_length、train_batch_size，应该能跑起来
