### ISSUE TITLE
Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by WHQ1111** [PaddlePaddle/ERNIE#144]
为啥老是出现这个问题？之前认为是版本不对所以重新安装对应版本之后解决了，但是不知为啥一天之后又出现在了这个问题？这么不稳定吗？

**Comment by xiegegege** [comment]
你是用的docker吗？可以用nvidia-smi看看环境里有没有gpu

**Comment by LangleyW** [comment]
> 为啥老是出现这个问题？之前认为是版本不对所以重新安装对应版本之后解决了，但是不知为啥一天之后又出现在了这个问题？这么不稳定吗？

请问您现在问题解决了么？我也遇到同样的问题。

**Comment by xiegegege** [comment]
> > 为啥老是出现这个问题？之前认为是版本不对所以重新安装对应版本之后解决了，但是不知为啥一天之后又出现在了这个问题？这么不稳定吗？
> 
> 请问您现在问题解决了么？我也遇到同样的问题。

请问您安装的是gpu版的paddle吗？还有就是可以nvidia-smi确认下环境里有没有gpu

**Comment by LangleyW** [comment]
有gpu 现在安装成功了 我尝试了一下
Ubuntu conda python3 cuda9这个环境下安装paddle成功了 别的成功不了

发自我的 iPhone

**Comment by xiegegege** [comment]
> 有gpu 现在安装成功了 我尝试了一下 Ubuntu conda python3 cuda9这个环境下安装paddle成功了 别的成功不了 发自我的 iPhone
> […](#)

能请问下具体什么环境没成功吗？我复现下～

**Comment by LangleyW** [comment]
其他一样，conda变成pip安装，按照教程会有问题，不过不是runtime问题。 
没有从清华源下载，直接pip安装paddle gpu包，会出现这层层主说的runtime问题。

发自我的 iPhone

**Comment by wtyn** [comment]
我感觉很奇怪。运行 $ bash PaddleNLP/dialogue_model_toolkit/dialogue_general_understanding/run.sh atis_intent predict 这个没问题。但$ PaddleNLP/lexical_analysis/run.sh infer 运行就会报这个错误。懵逼，机器是有GPU的。

**Comment by LangleyW** [comment]
我的就是gpu。我最近没用paddle所以我不清楚是不是版本更新导致的，gpu找不到是安装版本问题。建议cuda那套安装流程，别忘了一开始把清华源加进去，不然安装还会报no gpu found错误。我之前是这样解决的，如果您这样解决不了，那我就不知道了。
是的，查看gpu个数就nvidia-smi或者加个-L都行。

发自我的 iPhone

**Comment by xiegegege** [comment]
> 我感觉很奇怪。运行 $ bash PaddleNLP/dialogue_model_toolkit/dialogue_general_understanding/run.sh atis_intent predict 这个没问题。但$ PaddleNLP/lexical_analysis/run.sh infer 运行就会报这个错误。懵逼，机器是有GPU的。

我刚试了下，这两个infer都是可以跑的，不过第一个模型默认用的0号卡，第二个模型默认用的2号卡，会不会是你机子没有2号卡？可以在lexical_analysis/run.sh中把CUDA_VISIBLE_DEVICES改成0试下～

**Comment by LangleyW** [comment]
不会 我的机子有八个gpu，我的就是环境问题。你找到问题就好。我的目前也没啥问题。

发自我的 iPhone

**Comment by wtyn** [comment]
> > 我感觉很奇怪。运行 $ bash PaddleNLP/dialogue_model_toolkit/dialogue_general_understanding/run.sh atis_intent predict 这个没问题。但$ PaddleNLP/lexical_analysis/run.sh infer 运行就会报这个错误。懵逼，机器是有GPU的。
> 
> 我刚试了下，这两个infer都是可以跑的，不过第一个模型默认用的0号卡，第二个模型默认用的2号卡，会不会是你机子没有2号卡？可以在lexical_analysis/run.sh中把CUDA_VISIBLE_DEVICES改成0试下～

是那么回事～感谢！
