### ISSUE TITLE
有大哥尝试把ernie部署到服务器上面吗？🙏

### ISSUE THREAD

**Issue by yayaQAQ** [PaddlePaddle/ERNIE#147]
我查看了paddlepaddle的部署，但是paddlepaddle只讲了C++版本的部署，和python并没有关系，（并且感觉教程上面的部署其实只是paddlepaddle的C++版本的安装？）虽然加载ernie的模型的时间并不是很长，但是不应当去重复的加载。
或者说，paddlepaddle并不需要部署（或者说没有部署这一操作？），而只是将加载的代码放在外面，然后正常预测就行了？

**Comment by heavengate** [comment]
paddle 预测库部署见 http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/index_cn.html

**Comment by yayaQAQ** [comment]
> paddle 预测库部署见 http://paddlepaddle.org/documentation/docs/zh/1.4/advanced_usage/deploy/inference/index_cn.html

这个有看过，也就是说需要使用C++去进行预测代码的编写，没有python版本的吗？

**Comment by luo1129** [comment]
我用flask强写了一个ernie的服务器部署，但是CPU下的预测很慢，在exe.run执行的时候要500毫秒。gpu下也要100毫秒。百度的这个C++版本的文档写的太不友善了，真不知道他们到底想不想推广自己东西。。。

**Comment by yayaQAQ** [comment]
最终还是没有去使用c++去部署，直接用sanic，直接加载一次执行器和参数，后面每次直接调用预测。

**Comment by kuke** [comment]
1.5版本会发布基于python的预测接口

**Comment by kennyLSN** [comment]
> 我用flask强写了一个ernie的服务器部署，但是CPU下的预测很慢，在exe.run执行的时候要500毫秒。gpu下也要100毫秒。百度的这个C++版本的文档写的太不友善了，真不知道他们到底想不想推广自己东西。。。

能分享下flask部署ernie的代码吗？
