### ISSUE TITLE
ERNIE finetuning报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/ERNIE#151]
1.paddle develop ,python3.6下运行Ernie fine-tuning任务有如下报错：
Traceback (most recent call last):
  File "run_classifier.py", line 276, in <module>
    main(args)
  File "run_classifier.py", line 233, in main
    "dev")
  File "/ssd1/xiege/logs/LARK/ERNIE/finetune/classifier.py", line 180, in evaluate
    qids.extend(np_qids.reshape(-1).tolist())
AttributeError: 'NoneType' object has no attribute 'reshape'
2.另外在运行预训练时，epoch计数从2开始不是从0开始
<img width="846" alt="e26108aca74be1ec5a9f67a8d5ab3b21" src="https://user-images.githubusercontent.com/46314656/58615110-d5a89a00-82ec-11e9-85cc-cd45b5ee90b0.png">

**Comment by tianxin1860** [comment]
这是运行的哪个脚本？

**Comment by xiegegege** [comment]
运行那几个finetune任务都有这个报错

**Comment by tianxin1860** [comment]
已经 fix,  [https://github.com/PaddlePaddle/LARK/pull/172](https://github.com/PaddlePaddle/LARK/pull/172)， 感谢反馈~
