### ISSUE TITLE
ERNIE 推理py代码能否给一下

### ISSUE THREAD

**Issue by sicily** [PaddlePaddle/ERNIE#152]
ERNIE 推理py代码能否给一下？能否封装一个infer.py出来

**Comment by tianxin1860** [comment]
预计6月23发布 infer.py

**Comment by xiaoxue88** [comment]
> 预计6月23发布 infer.py

这个什么时候出来啊

**Comment by Biaocsu** [comment]
@tianxin1860  同问，infer.py什么时候可以出来？
