### ISSUE TITLE
请问有没有官方交流群

### ISSUE THREAD

**Issue by sicily** [PaddlePaddle/ERNIE#153]
关于paddlepaddle或者ernie有没有官方的微信群或者QQ群？

**Comment by adaxi123** [comment]
@sicily 你好哈，我们现在有paddle的交流群和微信群，qq群是：432676488 欢迎您的加入，可以在里面咨询任何和ernie模型有关的问题

**Comment by foreversolar** [comment]
【飞桨PaddlePaddle 交流群】：432676488
【飞桨 ERNIE交流群】: 760439550

**Comment by itclubhelper** [comment]
有个ai群，声明 非官方的。就是互相学习交流，码农加我微信：
![WechatIMG3](https://user-images.githubusercontent.com/55038924/64482406-b8586580-d223-11e9-8c5a-3a284bd3e77d.jpeg)
