### ISSUE TITLE
warmup_proportion  bug反馈

### ISSUE THREAD

**Issue by wq343580510** [PaddlePaddle/ERNIE#157]
![image](https://user-images.githubusercontent.com/15842810/59023769-09eb0000-8883-11e9-885f-cb78b1bebd75.png)
finetune/classifier.py文件中这个train_fetch_list 好像最多只能有四个元素，而这里取的是index为4的元素。我在跑任务的时候把warmup_proportion调为0.1就会有这个错。烦请作者确认下。

**Comment by tianxin1860** [comment]
已经 fix, 感谢反馈
