### ISSUE TITLE
README.md文档笔误：NER示例数据header

### ISSUE THREAD

**Issue by xinfeng1i** [PaddlePaddle/ERNIE#159]
在 【序列标注任务】-> 【1.实体识别】部分

> 以 MSRA-NER(SIGHAN 2006) 作为示例，数据格式为包含2个字段的tsv文件，2个字段分别为: text_a label, 示例数据如下:

这里表示数据格式是text_a在前，而label在后；而在给出的例子中，错误地将label放在了text_a之前，这应该是一个笔误，麻烦更正一下。

> label  text_a
在 这 里 恕 弟 不 恭 之 罪 ， 敢 在 尊 前 一 诤 ： 前 人 论 书 ， 每 曰 “ 字 字 有 来 历 ， 笔 笔 有 出 处 ” ， 细 读 公 字 ， 何 尝 跳 出 前 人 藩 篱 ， 自 隶 变 而 后 ， 直 至 明 季 ， 兄 有 何 新 出 ？    O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O

**Comment by tianxin1860** [comment]
已修复，谢谢反馈。
