### ISSUE TITLE
fluid1.2是否可以运行BERT？

### ISSUE THREAD

**Issue by xiehanlin** [PaddlePaddle/ERNIE#160]
文档中指出需要使用paddle1.3以上训练，但如果只做预测，是否可以使用1.2版本fluid？
比如使用1.2版本paddle，加载预训练的bert或者fine-tune后的bert模型

如果不支持，希望能具体解释下原因，比如1.2上某些op缺失等..

谢谢

**Comment by tianxin1860** [comment]
我们在 paddle 1.3 上做了全面测试，建议使用 1.3 及以上版本；1.3 版本修复了 save_inference_model 存在的 bug，不建议使用。
