### ISSUE TITLE
LCQMC 数据集复现

### ISSUE THREAD

**Issue by Olivia-xu** [PaddlePaddle/ERNIE#165]
LCQMA数据集复现，模型似乎无效果，shuffle也做了，输出的二维数据似乎都一样，请问有没有人遇到同样的问题

**Comment by tianxin1860** [comment]
我们发布的所有结果统一采用如下评估方式:
同 1 个任务跑 5 次，取5次验证集评估结果中的 max_acc 作为 max_dev_acc,  取5次 max_dev_acc 对应的测试集评估结果作为 test_acc, 然后求 5 个 max_dev_acc 及 test_acc 均值作为最终发布的 dev_acc 和 test_acc。

**Comment by arbalest339** [comment]
我也遇到了类似问题，NER任务在原数据原参数上尝试了3次，每一次模型在验证集和测试集上的表现都很差，准确率，召回率，f1，均只有5.0左右，现在尝试的分类任务也是这个问题，已经是最后一个epoch，正确率还是只有0.5。

**Comment by zhanghan1992** [comment]
1.检查下数据格式；2.检查下是否正确加载预训练模型；3.调参数(学习率、batch_size)
