### ISSUE TITLE
ner任务fine tuning 报KeyError错误

### ISSUE THREAD

**Issue by Austendeng** [PaddlePaddle/ERNIE#167]
自己的tsv文件数据集，示例如下：
![image](https://user-images.githubusercontent.com/16330293/59655742-e3578e00-91cd-11e9-80bd-0b72c973035c.png)
执行fine tuning时报KeyError错误：
![image](https://user-images.githubusercontent.com/16330293/59655795-0eda7880-91ce-11e9-9188-07693767f4d9.png)
请问文件整理有什么没满足的要求吗？

**Comment by Austendeng** [comment]
已解决。
字与字、标注与标注之间用计算机不可见字符作为分隔符就好了。
![image](https://user-images.githubusercontent.com/16330293/59661426-616f6100-91dd-11e9-97ee-155f2f3ba4ab.png)

**Comment by semal** [comment]
遇到了同样的问题，用 \001 分割依然报同样的错误，只有 \002 分割有用，因为 ernie 的 tokens 分隔符用的 \002。
