### ISSUE TITLE
如何理解ERNIE的知识增强？

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/ERNIE#175]
我能不能这么理解：

- ERNIE学习词级别先验知识：就是说任意下游任务中，利用ERNIE的seg_label，输入自定义分词结果；
- ERNIE学习实体先验知识：就是说用ERNIE跑多任务预训练时，包含一个通过序列标注任务实现的实体识别任务；
- ERNIE学习实体关系先验知识：就是说用ERNIE跑多任务预训练时，包含一个通过单句分类任务实现的实体关系分类任务。

**Comment by wangshuohuan** [comment]
相较于BERT模型 ，ERNIE模型在学习过程中，对词、实体等先验知识进行完整的掩码，使得模型能够直接对语义知识进行建模，学习更加完整的语义单元和真实世界的实体关系。具体可以看下这个：https://www.jiqizhixin.com/articles/2019-03-16-3
