### ISSUE TITLE
pre_train elmo model

### ISSUE THREAD

**Issue by beibei0902** [PaddlePaddle/ERNIE#178]
预训练好的Elmo模型的文件夹中缺少部分配置文件,请问是否可以提供呢,谢啦

**Comment by tianxin1860** [comment]
请帖一下具体报错信息，以及复现步骤

**Comment by beibei0902** [comment]
> 
> 
> 请帖一下具体报错信息，以及复现步骤

非常感谢回复,在制定了预训练模型后,报错信息为:Cannot open file baike_elmo_checkpoint/softmax_weight for load op at [/paddle/paddle/fluid/operators/load_op.h:37]

**Comment by tianxin1860** [comment]
需求是基于 ELMo 预训练模型继续做 Pretrain ?

**Comment by beibei0902** [comment]
您好:
       是希望可以通过预训练好的Elmo模型获取动态的词向量.
  

 

 ------------------ 原始邮件 ------------------
  发件人: "tianxin"<notifications@github.com>;
 发送时间: 2019年6月28日(星期五) 下午4:44
 收件人: "PaddlePaddle/LARK"<LARK@noreply.github.com>;
 抄送: "小贝"<1639663937@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [PaddlePaddle/LARK] pre_train elmo model (#178)

 

 
需求是基于 ELMo 预训练模型继续做 Pretrain ?

**Comment by tianxin1860** [comment]
执行哪个脚本出错？

**Comment by beibei0902** [comment]
在lark中的Elmo 文件夹下的train文件，指定了预训练文件的目录


发自我的iPhone

------------------ Original ------------------
