### ISSUE TITLE
ernie做embedding时，对输入的一些疑问

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/ERNIE#179]
如下图，py_reader里的shape是固定大小的，比如max_seq_len=512时，src_ids的shape为[-1, 512, 1]，而传入的数据的shape是[batch_size, max_len_in_bs, 1]，max_len_in_bs在每个batch是不一样的。是这样的吗？
![image](https://user-images.githubusercontent.com/15082798/60062711-e8b45b80-972c-11e9-9934-4f071b4356b8.png)

**Comment by wzzju** [comment]
请问您想问什么呢？不好意思，没有看懂您的问题。

**Comment by tianxin1860** [comment]
是的，max_len_in_bs 是根据每个 batch 内的数据动态决定的。

**Comment by shiyazhou121** [comment]
@tianxin1860 @wzzju 谢谢两位的回复～
