### ISSUE TITLE
如何理解batch中序列的mask实现

### ISSUE THREAD

**Issue by shiyazhou121** [PaddlePaddle/ERNIE#180]
在同一个batch里，为了统一长度对短序列加入pad=0。经过scale后补位的部分变成-10000，比如mask矩阵如下
[[0 0 -10000]
[0 0 -10000]
[-10000 -10000 -10000]]
在self-attention时，是将q*k后的矩阵加上mask矩阵，经过softmax后，mask[0][2]后mask[1][2]等于0，实现了掩码功能，但第三行是[0.3333, 0.3333, 0.3333]，再乘v后，第三行不为0。
如果是多层mul_heads_attention的话，掩码貌似失去了功能。

![image](https://user-images.githubusercontent.com/15082798/60231673-a1fd6780-98cc-11e9-8fc0-36139d899483.png)
![image](https://user-images.githubusercontent.com/15082798/60231686-afb2ed00-98cc-11e9-8b37-a846b2bf4b0c.png)

**Comment by kuke** [comment]
第三行这里算出什么值都有没关系，因为在下一层的计算中，这一部分又会被mask，不会影响下一层的计算结果

**Comment by shiyazhou121** [comment]
@kuke 看懂了，感谢回复
