### ISSUE TITLE
ERNIE用CPU提取句向量速度较慢

### ISSUE THREAD

**Issue by zhangzhen8230** [PaddlePaddle/ERNIE#184]
用ERNIE提取句向量的时候，一句话大概是0.7s的编码时间，没有用GPU，8核的mac跑的，请问下这个速度正常么？ 我同样的配置，用bert-as-service 大概不到0.1s一句话

**Comment by bipedalBit** [comment]
用ParallelExecutor替换Executor会快很多。

**Comment by treper** [comment]
我这边测的速度是短文本0.13s一句,但是这速度也满足不了需求，看cpu的利用率很低,我用的16核128G机器，Executor没有并行?看日志有检测到核数
```
Device count: 16
Total num examples: 6030686
```
