### ISSUE TITLE
请问PaddleSlim有覆盖ERNIE计划吗？

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/ERNIE#185]
[bert-as-service](https://github.com/hanxiao/bert-as-service)是一个很方便的BERT句向量编码服务的封装。
我在尝试用ERNIE做相同的事时，发现目前paddle模型的图优化工具还没有覆盖NLP模型。
自测4个CPU的条件下，bert-as-service编码句子的速度是ERNIE的3倍左右，我猜这个差距是因为没有做图优化。

**Comment by bipedalBit** [comment]
用ParallelExecutor替换Executor会快很多。

**Comment by nbcc** [comment]
> [bert-as-service](https://github.com/hanxiao/bert-as-service)是一个很方便的BERT句向量编码服务的封装。
> 我在尝试用ERNIE做相同的事时，发现目前paddle模型的图优化工具还没有覆盖NLP模型。
> 自测4个CPU的条件下，bert-as-service编码句子的速度是ERNIE的3倍左右，我猜这个差距是因为没有做图优化。

感谢建议！我们会评估一下实现的成本。

PE 多卡 finetuning 是我们的默认配置，如果需要进一步释放多卡的性能，可以参考这个实现 https://github.com/PaddlePaddle/LARK/commit/7803d8967074cf4af9c48de4e1d8ede4bb499c60
通过 multi_process 的引入，在支持 NVlink 的硬件上，会有更优异的数据吞吐。
