### ISSUE TITLE
window上用BERT在XNLI任务上Fine-tuning报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/ERNIE#186]
在LARK/BERT目录中，执行python -u run_classifier.py --task_name XNLI --use_cuda true --do_train true --do_val true  --do_test true --batch_size 8192 --in_tokens true --init_pretraining_params chinese_L-12_H-768_A-12/params --data_dir ./XNLI   --checkpoints ./XNLI_checkpoints --save_steps 1000 --weight_decay  0.01 --warmup_proportion 0.0 --validation_steps 25  --epoch 1 --max_seq_len 512 --bert_config_path chinese_L-12_H-768_A-12/bert_config.json --learning_rate 1e-4 --skip_steps 10 --random_seed 1，使用BERT在NLP任务上Fine-tuning,报错信息如下：
![NLI](https://user-images.githubusercontent.com/37854899/60437798-b5e4f880-9c41-11e9-84ff-54c52fa769e8.PNG)

**Comment by tianxin1860** [comment]
python 版本是?

**Comment by JiaXiao243** [comment]
python2.7
