### ISSUE TITLE
ernie没有像bert一样预留[unused1]给一些未知的词使用吗

### ISSUE THREAD

**Issue by lonePatient** [PaddlePaddle/ERNIE#188]
现在做一些特殊序列，一些特殊的符号在bert里面使用[unused]表示，不知道在ernie里面怎么表示，目前看了下 好像都是[unk]的吧

**Comment by tianxin1860** [comment]
> 现在做一些特殊序列，一些特殊的符号在bert里面使用[unused]表示，不知道在ernie里面怎么表示，目前看了下 好像都是[unk]的吧

词表尾部的 `##字符` 都是未使用的 ID，你可以把特殊符号的 ID 设置为词表尾部未占用的 ID;
![image](https://user-images.githubusercontent.com/6829601/60580513-d931b400-9db7-11e9-9c9d-155fbbdcf9e0.png)

**Comment by jfkey** [comment]
bert中的[unused]是可以被替换成自己vocab中一些词是么？一直没清楚这一点。

**Comment by lonePatient** [comment]
@jfkey [unused]只是随机初始化，没有参与训练，留出位置可以替换一些vocab没有中的词，然后微调或者pretrain。这样就不至于全为[unk]

**Comment by jfkey** [comment]
好的，明白了，谢谢您------------------ 原始邮件 ------------------
发件人: "lonePatinet"<notifications@github.com>
发送时间: 2020年3月16日(星期一) 晚上6:07
收件人: "PaddlePaddle/ERNIE"<ERNIE@noreply.github.com>;
抄送: "junfengLiu"<742718933@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PaddlePaddle/ERNIE] ernie没有像bert一样预留[unused1]给一些未知的词使用吗 (#188)




 
@jfkey [unused]只是随机初始化，没有参与训练，留出位置可以替换一些vocab没有中的词，然后微调或者pretrain。这样就不至于全为[unk]
 
&mdash;
