### ISSUE TITLE
相较于BERT与GPT2.0来说有哪些结构上的变化呢

### ISSUE THREAD

**Issue by terrifyzhao** [PaddlePaddle/ERNIE#19]

**Comment by loretoparisi** [comment]
@terrifyzhao for GPT-2 here is the missing training part (unofficial), please add to your repository - https://github.com/loretoparisi/gpt-2

**Comment by bfjia1** [comment]
mailly modify the MLM task sample using word bound to construct mask

**Comment by dgai91** [comment]
@terrifyzhao I think this work may be a preprocessing modification about BERT. Can not be a new pretrained model
