### ISSUE TITLE
实体（比如‘哈尔滨’）被masked时，实体的所有字的MASK机制一样的么？

### ISSUE THREAD

**Issue by lexmen318** [PaddlePaddle/ERNIE#190]
从batching.py的如下代码看，似乎不太一样哦：
prob = prob_mask[prob_index + index]
                        base_prob = 1.0
                        if index == beg:
                            base_prob = 0.15
                        if base_prob * 0.2 < prob <= base_prob:
                            mask_label.append(sent[index])
                            sent[index] = MASK
                            mask_flag = True
                            mask_pos.append(sent_index * max_len + index)
                        elif base_prob * 0.1 < prob <= base_prob * 0.2:
                            mask_label.append(sent[index])
                            sent[index] = replace_ids[prob_index + index]
                            mask_flag = True
                            mask_pos.append(sent_index * max_len + index)
                        else:
                            mask_label.append(sent[index])
                            mask_pos.append(sent_index * max_len + index)

**Comment by zhanghan1992** [comment]
只根据首字的prob是否大于0.15决定该词是否mask；因此如果mask，相当于已知首字的porb < 0.15了，所以在首字上按0.15的80%, 10%, 10%决定替换的token。首字和非首字的处理是一样的。

**Comment by zhanghan1992** [comment]
参考https://github.com/PaddlePaddle/LARK/issues/33

**Comment by lexmen318** [comment]
仔细看了一下代码，确实都是一样的概率，关键点就在于非词首本身是在  if prob > 0.15的else分支里面了，因此已经是依赖于词首的15%概率了，所以prob必须以1.0为起点。

而词首本身前后两次取的prob_mask概率是一样的，所以必须以0.15为起点。
