### ISSUE TITLE
我想用你们训练好的模型参数来训练我们的文章数据拿到词向量做检索 召回相似的文章 现在怎么拿到经过ERNIE 编码后Embedding对应的句子呢

### ISSUE THREAD

**Issue by qq1074123922** [PaddlePaddle/ERNIE#195]
已经通过 ernie_encoder.py 抽取出到输入句子的 Embedding 表示并做了向量检索，现在拿不到向量对应的句子表示

**Comment by kuke** [comment]
可以更清楚地表达一下你的问题吗？按字面理解，ernie的输出就是句子的表示了

**Comment by qq1074123922** [comment]
![WechatIMG23](https://user-images.githubusercontent.com/13366698/60883767-aab34d80-a27d-11e9-8e36-d476f5e73f65.png)
现在有向量，怎么知道向量对应的原始句子呢 是通过config/vocab.txt的ID 索引拼出句子吗

**Comment by kuke** [comment]
原则上不行，如果是输入embedding的词向量去拼接句子，可行。但经过编码后的表示应该还原不了句子了

**Comment by qq1074123922** [comment]
明白，那我在用ernie编码句子的时候可以构建每一个原始句子和embedding之后句向量表示的对应关系吗

**Comment by qq1074123922** [comment]
![WechatIMG25](https://user-images.githubusercontent.com/13366698/60935353-27850c80-a2fc-11e9-884f-4cabb8a18d59.jpeg)
这是AI大会的示例，我现在的思路有问题吗？ 应该还可以实现的 对吧

**Comment by kuke** [comment]
现在这么用没问题

**Comment by qq1074123922** [comment]
![WechatIMG26](https://user-images.githubusercontent.com/13366698/60936808-fbb85580-a300-11e9-81ba-900d95bf73ab.png)
谢谢，麻烦您可以说一下AI大会相关视频推荐的实现思路吗 我的思路是用你们训练好的模型参数来编码文章title拿到词向量做检索 召回相似的文章 相似句向量检索可以做到 现在的问题是我无法知道召回的句向量对应的原始文章title 就没法推荐
