### ISSUE TITLE
ELMo train.py报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/ERNIE#200]
Traceback (most recent call last):
  File "train.py", line 580, in <module>
    train()
  File "train.py", line 248, in train
    random.seed(args.random_seed)
NameError: name 'random' is not defined

**Comment by tianxin1860** [comment]
帖一下 运行环境、复现命令吧;

**Comment by tianxin1860** [comment]
> Traceback (most recent call last):
> File "train.py", line 580, in 
> train()
> File "train.py", line 248, in train
> random.seed(args.random_seed)
> NameError: name 'random' is not defined

帖一下 运行环境、复现命令吧;

**Comment by zhengya01** [comment]
> > Traceback (most recent call last):
> > File "train.py", line 580, in
> > train()
> > File "train.py", line 248, in train
> > random.seed(args.random_seed)
> > NameError: name 'random' is not defined
> 
> 帖一下 运行环境、复现命令吧;
运行环境：
Python 2.7.15
paddle 1.5.0
cuda 9
cudnn 7
运行命令：
python  train.py \
--train_path='data/train/sentence_file_*'  \
--test_path='data/dev/sentence_file_*'  \
--vocab_path data/vocabulary_min5k.txt \
--learning_rate 0.2 \
--use_gpu True \
--all_train_tokens 35479 \
--max_epoch 10 \
--log_interval 10 \
--dev_interval 20 \
--local True $@ \
--enable_ce \
--shuffle false \
--random_seed 100
