### ISSUE TITLE
关于在AIStudio上传数据集

### ISSUE THREAD

**Issue by a159879** [PaddlePaddle/ERNIE#204]
我想利用某位大佬搭建的resnet网络传入自己的植物病害图片进行训练看看，训练集有60种类的病害，我再上传数据集在aistudio上遇到了困难   好像不能传文件夹   只能传压缩文件。求助各位大牛 
                                                                                                                          谢谢

**Comment by tianxin1860** [comment]
LARK 项目无关的问题请在这里提 Issue: [https://github.com/PaddlePaddle/Paddle/issues](https://github.com/PaddlePaddle/Paddle/issues)
