### ISSUE TITLE
句子相似度 使用自己数据 finetune效果不好 

### ISSUE THREAD

**Issue by daidaidal** [PaddlePaddle/ERNIE#206]
使用run_lcqmc.sh对数据进行finetune具体设置如下
  1 set -eux
  2 
  3 export FLAGS_sync_nccl_allreduce=1
  4 export CUDA_VISIBLE_DEVICES=7
  5 
  6 python -u run_classifier.py \
  7                    --use_cuda true \
  8                    --verbose true \
  9                    --do_train true \
 10                    --do_val true \
 11                    --do_test true \
 12                    --batch_size 32 \
 13                    --init_pretraining_params model_para/params \
 14                    --train_set task_data/task_data/mydata/train_badcase.tsv \
 15                    --dev_set task_data/task_data/mydata/dev_badcase.tsv \
 16                    --test_set task_data/task_data/mydata/test_badcase.tsv \
 17                    --vocab_path config/vocab.txt \
 18                    --checkpoints ./checkpoints \
 19                    --save_steps 10000 \
 20                    --weight_decay  0.0 \
 21                    --warmup_proportion 0.0 \
 22                    --validation_steps 10900 \
 23                    --epoch 200 \
 24                    --max_seq_len 128  \
 25                    --ernie_config_path config/ernie_config.json \
 26                    --learning_rate 2e-5 \                                                                                                                               
 27                    --skip_steps 10 \
 28                    --num_iteration_per_drop_scope 1 \
 29                    --num_labels 2 \
 30                    --random_seed 1

**Comment by tianxin1860** [comment]
贴一下日志评估结果吧？

> 使用run_lcqmc.sh对数据进行finetune具体设置如下
> 1 set -eux
> 2
> 3 export FLAGS_sync_nccl_allreduce=1
> 4 export CUDA_VISIBLE_DEVICES=7
> 5
> 6 python -u run_classifier.py 
> 7 --use_cuda true 
> 8 --verbose true 
> 9 --do_train true 
> 10 --do_val true 
> 11 --do_test true 
> 12 --batch_size 32 
> 13 --init_pretraining_params model_para/params 
> 14 --train_set task_data/task_data/mydata/train_badcase.tsv 
> 15 --dev_set task_data/task_data/mydata/dev_badcase.tsv 
> 16 --test_set task_data/task_data/mydata/test_badcase.tsv 
> 17 --vocab_path config/vocab.txt 
> 18 --checkpoints ./checkpoints 
> 19 --save_steps 10000 
> 20 --weight_decay 0.0 
> 21 --warmup_proportion 0.0 
> 22 --validation_steps 10900 
> 23 --epoch 200 
> 24 --max_seq_len 128 
> 25 --ernie_config_path config/ernie_config.json 
> 26 --learning_rate 2e-5 \
> 27 --skip_steps 10 
> 28 --num_iteration_per_drop_scope 1 
> 29 --num_labels 2 
> 30 --random_seed 1
贴一下日志评估结果吧？

**Comment by tianxin1860** [comment]
> 使用run_lcqmc.sh对数据进行finetune具体设置如下
> 1 set -eux
> 2
> 3 export FLAGS_sync_nccl_allreduce=1
> 4 export CUDA_VISIBLE_DEVICES=7
> 5
> 6 python -u run_classifier.py 
> 7 --use_cuda true 
> 8 --verbose true 
> 9 --do_train true 
> 10 --do_val true 
> 11 --do_test true 
> 12 --batch_size 32 
> 13 --init_pretraining_params model_para/params 
> 14 --train_set task_data/task_data/mydata/train_badcase.tsv 
> 15 --dev_set task_data/task_data/mydata/dev_badcase.tsv 
> 16 --test_set task_data/task_data/mydata/test_badcase.tsv 
> 17 --vocab_path config/vocab.txt 
> 18 --checkpoints ./checkpoints 
> 19 --save_steps 10000 
> 20 --weight_decay 0.0 
> 21 --warmup_proportion 0.0 
> 22 --validation_steps 10900 
> 23 --epoch 200 
> 24 --max_seq_len 128 
> 25 --ernie_config_path config/ernie_config.json 
> 26 --learning_rate 2e-5 \
> 27 --skip_steps 10 
> 28 --num_iteration_per_drop_scope 1 
> 29 --num_labels 2 
> 30 --random_seed 1

贴一下日志评估结果吧。

**Comment by daidaidal** [comment]
[dev evaluation] ave loss: 0.402439, ave acc: 0.855987, ave p 0.858453, ave r 0.992442, ave f1: 0.920598, data_num: 175380, elapsed time: 388.260896 s
[dev evaluation] ave loss: 0.397664, ave acc: 0.857943, ave p 0.858569, ave r 0.995038, ave f1: 0.921780, data_num: 175380, elapsed time: 382.906403 s
[dev evaluation] ave loss: 0.390151, ave acc: 0.859169, ave p 0.858249, ave r 0.997302, ave f1: 0.922565, data_num: 175380, elapsed time: 388.459453 s
[dev evaluation] ave loss: 0.390315, ave acc: 0.859385, ave p 0.861013, ave r 0.993161, ave f1: 0.922378, data_num: 175380, elapsed time: 393.419607 s
[dev evaluation] ave loss: 0.387367, ave acc: 0.860834, ave p 0.860281, ave r 0.996387, ave f1: 0.923346, data_num: 175380, elapsed time: 402.016453 s
[dev evaluation] ave loss: 0.386303, ave acc: 0.861187, ave p 0.862448, ave r 0.993425, ave f1: 0.923315, data_num: 175380, elapsed time: 413.335207 s
[dev evaluation] ave loss: 0.388767, ave acc: 0.861489, ave p 0.861666, ave r 0.995099, ave f1: 0.923588, data_num: 175380, elapsed time: 410.995919 s
[dev evaluation] ave loss: 0.387211, ave acc: 0.862288, ave p 0.862826, ave r 0.994381, ave f1: 0.923944, data_num: 175380, elapsed time: 410.639337 s
[dev evaluation] ave loss: 0.381663, ave acc: 0.863251, ave p 0.864401, ave r 0.993249, ave f1: 0.924356, data_num: 175380, elapsed time: 411.415905 s
[dev evaluation] ave loss: 0.380098, ave acc: 0.863679, ave p 0.865297, ave r 0.992442, ave f1: 0.924519, data_num: 175380, elapsed time: 410.661954 s
[dev evaluation] ave loss: 0.379564, ave acc: 0.864534, ave p 0.865037, ave r 0.994055, ave f1: 0.925069, data_num: 175380, elapsed time: 411.331173 s
[dev evaluation] ave loss: 0.378026, ave acc: 0.864654, ave p 0.866645, ave r 0.991703, ave f1: 0.924966, data_num: 175380, elapsed time: 410.392761 s
[dev evaluation] ave loss: 0.376194, ave acc: 0.865578, ave p 0.867294, ave r 0.991988, ave f1: 0.925460, data_num: 175380, elapsed time: 419.495584 s
[dev evaluation] ave loss: 0.374454, ave acc: 0.866285, ave p 0.865677, ave r 0.995513, ave f1: 0.926066, data_num: 175380, elapsed time: 415.533363 s
[dev evaluation] ave loss: 0.379398, ave acc: 0.866068, ave p 0.866710, ave r 0.993588, ave f1: 0.925822, data_num: 175380, elapsed time: 414.276473 s
[dev evaluation] ave loss: 0.375053, ave acc: 0.867231, ave p 0.867923, ave r 0.993330, ave f1: 0.926402, data_num: 175380, elapsed time: 404.057022 s
[dev evaluation] ave loss: 0.375337, ave acc: 0.867727, ave p 0.868335, ave r 0.993384, ave f1: 0.926660, data_num: 175380, elapsed time: 384.852420 s
[dev evaluation] ave loss: 0.376404, ave acc: 0.867972, ave p 0.868897, ave r 0.992856, ave f1: 0.926750, data_num: 175380, elapsed time: 393.582216 s
[dev evaluation] ave loss: 0.378000, ave acc: 0.868383, ave p 0.869528, ave r 0.992456, ave f1: 0.926934, data_num: 175380, elapsed time: 395.149663 s
[dev evaluation] ave loss: 0.381301, ave acc: 0.869136, ave p 0.869481, ave r 0.993581, ave f1: 0.927398, data_num: 175380, elapsed time: 390.549581 s
[dev evaluation] ave loss: 0.371318, ave acc: 0.869443, ave p 0.871660, ave r 0.990660, ave f1: 0.927358, data_num: 175380, elapsed time: 395.930126 s
[dev evaluation] ave loss: 0.374308, ave acc: 0.870664, ave p 0.871717, ave r 0.992273, ave f1: 0.928097, data_num: 175380, elapsed time: 393.870682 s
[dev evaluation] ave loss: 0.374045, ave acc: 0.870225, ave p 0.872311, ave r 0.990754, ave f1: 0.927768, data_num: 175380, elapsed time: 399.287012 s
[dev evaluation] ave loss: 0.373117, ave acc: 0.870738, ave p 0.871480, ave r 0.992741, ave f1: 0.928166, data_num: 175380, elapsed time: 385.594751 s
[dev evaluation] ave loss: 0.372859, ave acc: 0.870892, ave p 0.871536, ave r 0.992869, ave f1: 0.928254, data_num: 175380, elapsed time: 388.083435 s
[dev evaluation] ave loss: 0.369510, ave acc: 0.871451, ave p 0.871823, ave r 0.993208, ave f1: 0.928565, data_num: 175380, elapsed time: 367.192106 s
[dev evaluation] ave loss: 0.376708, ave acc: 0.871724, ave p 0.873004, ave r 0.991785, ave f1: 0.928612, data_num: 175380, elapsed time: 368.255313 s
[dev evaluation] ave loss: 0.361950, ave acc: 0.872562, ave p 0.873855, ave r 0.991656, ave f1: 0.929036, data_num: 175380, elapsed time: 367.907001 s
[dev evaluation] ave loss: 0.371035, ave acc: 0.872574, ave p 0.873549, ave r 0.992137, ave f1: 0.929074, data_num: 175380, elapsed time: 368.608770 s
[dev evaluation] ave loss: 0.369583, ave acc: 0.873030, ave p 0.874132, ave r 0.991886, ave f1: 0.929294, data_num: 175380, elapsed time: 367.728836 s
[dev evaluation] ave loss: 0.368213, ave acc: 0.872688, ave p 0.874046, ave r 0.991541, ave f1: 0.929094, data_num: 175380, elapsed time: 371.653536 s
[dev evaluation] ave loss: 0.364671, ave acc: 0.871890, ave p 0.875193, ave r 0.988701, ave f1: 0.928490, data_num: 175380, elapsed time: 366.008117 s
[dev evaluation] ave loss: 0.373803, ave acc: 0.872477, ave p 0.874341, ave r 0.990802, ave f1: 0.928935, data_num: 175380, elapsed time: 363.104151 s
[dev evaluation] ave loss: 0.368774, ave acc: 0.873617, ave p 0.875046, ave r 0.991317, ave f1: 0.929560, data_num: 175380, elapsed time: 370.268786 s
[dev evaluation] ave loss: 0.372703, ave acc: 0.873138, ave p 0.875352, ave r 0.990192, ave f1: 0.929237, data_num: 175380, elapsed time: 369.793399 s
[dev evaluation] ave loss: 0.367725, ave acc: 0.873024, ave p 0.875819, ave r 0.989331, ave f1: 0.929121, data_num: 175380, elapsed time: 369.953435 s
[dev evaluation] ave loss: 0.369095, ave acc: 0.873338, ave p 0.876637, ave r 0.988538, ave f1: 0.929231, data_num: 175380, elapsed time: 369.158057 s
[dev evaluation] ave loss: 0.367636, ave acc: 0.874313, ave p 0.876434, ave r 0.990192, ave f1: 0.929847, data_num: 175380, elapsed time: 367.307527 s
[dev evaluation] ave loss: 0.372012, ave acc: 0.874307, ave p 0.876113, ave r 0.990666, ave f1: 0.929875, data_num: 175380, elapsed time: 365.107008 s
[dev evaluation] ave loss: 0.375429, ave acc: 0.873857, ave p 0.875982, ave r 0.990239, ave f1: 0.929613, data_num: 175380, elapsed time: 391.299509 s
[dev evaluation] ave loss: 0.376995, ave acc: 0.873788, ave p 0.875883, ave r 0.990294, ave f1: 0.929581, data_num: 175380, elapsed time: 379.933011 s
[dev evaluation] ave loss: 0.364074, ave acc: 0.875305, ave p 0.875514, ave r 0.992951, ave f1: 0.930542, data_num: 175380, elapsed time: 397.539081 s
[dev evaluation] ave loss: 0.376678, ave acc: 0.874632, ave p 0.876756, ave r 0.990151, ave f1: 0.930010, data_num: 175380, elapsed time: 392.193115 s
[dev evaluation] ave loss: 0.372789, ave acc: 0.875259, ave p 0.875764, ave r 0.992510, ave f1: 0.930489, data_num: 175380, elapsed time: 390.071153 s
[dev evaluation] ave loss: 0.378637, ave acc: 0.874587, ave p 0.875016, ave r 0.992707, ave f1: 0.930154, data_num: 175380, elapsed time: 396.258375 s
[dev evaluation] ave loss: 0.368232, ave acc: 0.873977, ave p 0.878434, ave r 0.986742, ave f1: 0.929443, data_num: 175380, elapsed time: 389.449600 s
[dev evaluation] ave loss: 0.367746, ave acc: 0.874917, ave p 0.878295, ave r 0.988247, ave f1: 0.930032, data_num: 175380, elapsed time: 389.693531 s
[dev evaluation] ave loss: 0.371320, ave acc: 0.875305, ave p 0.876590, ave r 0.991331, ave f1: 0.930436, data_num: 175380, elapsed time: 395.505187 s
[dev evaluation] ave loss: 0.375423, ave acc: 0.874376, ave p 0.877057, ave r 0.989345, ave f1: 0.929823, data_num: 175380, elapsed time: 396.178781 s
[dev evaluation] ave loss: 0.368092, ave acc: 0.875328, ave p 0.876588, ave r 0.991365, ave f1: 0.930450, data_num: 175380, elapsed time: 397.572197 s
[dev evaluation] ave loss: 0.367313, ave acc: 0.874820, ave p 0.878945, ave r 0.987148, ave f1: 0.929910, data_num: 175380, elapsed time: 392.595453 s
[dev evaluation] ave loss: 0.370225, ave acc: 0.874279, ave p 0.880060, ave r 0.984756, ave f1: 0.929469, data_num: 175380, elapsed time: 393.032563 s
[dev evaluation] ave loss: 0.371946, ave acc: 0.876103, ave p 0.877226, ave r 0.991480, ave f1: 0.930860, data_num: 175380, elapsed time: 389.837060 s
[dev evaluation] ave loss: 0.374115, ave acc: 0.876252, ave p 0.876956, ave r 0.992090, ave f1: 0.930977, data_num: 175380, elapsed time: 386.124070 s
[dev evaluation] ave loss: 0.365775, ave acc: 0.876120, ave p 0.878404, ave r 0.989745, ave f1: 0.930756, data_num: 175380, elapsed time: 389.043092 s
[dev evaluation] ave loss: 0.370453, ave acc: 0.876006, ave p 0.878704, ave r 0.989141, ave f1: 0.930658, data_num: 175380, elapsed time: 387.272539 s
[dev evaluation] ave loss: 0.370987, ave acc: 0.875938, ave p 0.878376, ave r 0.989534, ave f1: 0.930648, data_num: 175380, elapsed time: 389.056888 s
[dev evaluation] ave loss: 0.368836, ave acc: 0.876451, ave p 0.876315, ave r 0.993330, ave f1: 0.931161, data_num: 175380, elapsed time: 384.887165 s
[dev evaluation] ave loss: 0.372698, ave acc: 0.876366, ave p 0.878522, ave r 0.989907, ave f1: 0.930895, data_num: 175380, elapsed time: 386.131053 s
[dev evaluation] ave loss: 0.370602, ave acc: 0.877101, ave p 0.878098, ave r 0.991554, ave f1: 0.931384, data_num: 175380, elapsed time: 391.668767 s
[dev evaluation] ave loss: 0.379705, ave acc: 0.877238, ave p 0.878020, ave r 0.991859, ave f1: 0.931475, data_num: 175380, elapsed time: 391.900839 s
[dev evaluation] ave loss: 0.377297, ave acc: 0.877078, ave p 0.878045, ave r 0.991602, ave f1: 0.931375, data_num: 175380, elapsed time: 394.894322 s
[dev evaluation] ave loss: 0.379431, ave acc: 0.876445, ave p 0.878651, ave r 0.989826, ave f1: 0.930931, data_num: 175380, elapsed time: 407.652696 s
[dev evaluation] ave loss: 0.374804, ave acc: 0.877181, ave p 0.879237, ave r 0.989968, ave f1: 0.931323, data_num: 175380, elapsed time: 403.705580 s
[dev evaluation] ave loss: 0.371153, ave acc: 0.877609, ave p 0.878281, ave r 0.991981, ave f1: 0.931675, data_num: 175380, elapsed time: 396.462759 s
[dev evaluation] ave loss: 0.367850, ave acc: 0.876833, ave p 0.879536, ave r 0.989046, ave f1: 0.931082, data_num: 175380, elapsed time: 394.053875 s
[dev evaluation] ave loss: 0.369795, ave acc: 0.876628, ave p 0.879363, ave r 0.989019, ave f1: 0.930973, data_num: 175380, elapsed time: 396.700111 s
[dev evaluation] ave loss: 0.378377, ave acc: 0.876770, ave p 0.880606, ave r 0.987379, ave f1: 0.930941, data_num: 175380, elapsed time: 396.919845 s
[dev evaluation] ave loss: 0.376264, ave acc: 0.876930, ave p 0.880043, ave r 0.988430, ave f1: 0.931093, data_num: 175380, elapsed time: 391.853822 s
[dev evaluation] ave loss: 0.370228, ave acc: 0.877745, ave p 0.879045, ave r 0.991032, ave f1: 0.931685, data_num: 175380, elapsed time: 398.543637 s
[dev evaluation] ave loss: 0.373437, ave acc: 0.877403, ave p 0.879512, ave r 0.989867, ave f1: 0.931432, data_num: 175380, elapsed time: 388.803529 s
[dev evaluation] ave loss: 0.369547, ave acc: 0.877825, ave p 0.878996, ave r 0.991215, ave f1: 0.931739, data_num: 175380, elapsed time: 394.523475 s
[dev evaluation] ave loss: 0.366247, ave acc: 0.877569, ave p 0.880477, ave r 0.988667, ave f1: 0.931441, data_num: 175380, elapsed time: 393.234828 s
[dev evaluation] ave loss: 0.374722, ave acc: 0.877979, ave p 0.879577, ave r 0.990565, ave f1: 0.931777, data_num: 175380, elapsed time: 392.592827 s
[dev evaluation] ave loss: 0.370195, ave acc: 0.877386, ave p 0.880482, ave r 0.988409, ave f1: 0.931329, data_num: 175380, elapsed time: 392.878893 s
[dev evaluation] ave loss: 0.373066, ave acc: 0.878133, ave p 0.879683, ave r 0.990619, ave f1: 0.931861, data_num: 175380, elapsed time: 398.855773 s
[dev evaluation] ave loss: 0.376103, ave acc: 0.878190, ave p 0.878755, ave r 0.992076, ave f1: 0.931984, data_num: 175380, elapsed time: 386.737953 s
[dev evaluation] ave loss: 0.368764, ave acc: 0.877820, ave p 0.878981, ave r 0.991229, ave f1: 0.931737, data_num: 175380, elapsed time: 396.594223 s
[dev evaluation] ave loss: 0.372512, ave acc: 0.876776, ave p 0.880745, ave r 0.987182, ave f1: 0.930931, data_num: 175380, elapsed time: 407.839504 s
[dev evaluation] ave loss: 0.374801, ave acc: 0.877814, ave p 0.878589, ave r 0.991805, ave f1: 0.931771, data_num: 175380, elapsed time: 396.911232 s
[dev evaluation] ave loss: 0.377462, ave acc: 0.876491, ave p 0.880589, ave r 0.987020, ave f1: 0.930772, data_num: 175380, elapsed time: 379.010872 s
[dev evaluation] ave loss: 0.373646, ave acc: 0.877968, ave p 0.879552, ave r 0.990585, ave f1: 0.931773, data_num: 175380, elapsed time: 382.357293 s
[dev evaluation] ave loss: 0.373607, ave acc: 0.877899, ave p 0.879946, ave r 0.989907, ave f1: 0.931693, data_num: 175380, elapsed time: 374.445426 s
[dev evaluation] ave loss: 0.382706, ave acc: 0.878031, ave p 0.879697, ave r 0.990456, ave f1: 0.931797, data_num: 175380, elapsed time: 382.141171 s
[dev evaluation] ave loss: 0.384797, ave acc: 0.877706, ave p 0.879359, ave r 0.990510, ave f1: 0.931631, data_num: 175380, elapsed time: 377.228464 s
[dev evaluation] ave loss: 0.371975, ave acc: 0.878327, ave p 0.879041, ave r 0.991839, ave f1: 0.932040, data_num: 175380, elapsed time: 382.402256 s
[dev evaluation] ave loss: 0.379988, ave acc: 0.877649, ave p 0.880676, ave r 0.988484, ave f1: 0.931471, data_num: 175380, elapsed time: 365.868000 s
[dev evaluation] ave loss: 0.385202, ave acc: 0.878116, ave p 0.880363, ave r 0.989589, ave f1: 0.931786, data_num: 175380, elapsed time: 371.467416 s
[dev evaluation] ave loss: 0.378935, ave acc: 0.878025, ave p 0.879925, ave r 0.990111, ave f1: 0.931772, data_num: 175380, elapsed time: 359.200937 s
[dev evaluation] ave loss: 0.382333, ave acc: 0.877985, ave p 0.880792, ave r 0.988775, ave f1: 0.931665, data_num: 175380, elapsed time: 356.805658 s
[dev evaluation] ave loss: 0.381825, ave acc: 0.878196, ave p 0.879723, ave r 0.990646, ave f1: 0.931895, data_num: 175380, elapsed time: 358.356959 s
[dev evaluation] ave loss: 0.371875, ave acc: 0.877905, ave p 0.882069, ave r 0.986789, ave f1: 0.931495, data_num: 175380, elapsed time: 356.411919 s

**Comment by daidaidal** [comment]
bert f1值可以跑到97.15%
