### ISSUE TITLE
ERNIE推理时使用CPU，内存占用过高

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/ERNIE#210]
#207 
鉴于之前的issue已经被关闭，但问题仍没解决，现重开。

我利用更新后的代码，使用CPU进行推理，发现内存占用仍然很高12.8G，已经在Ubuntu服务器及windows本地机器多次实验，结论一致，内存占用过高问题仍没有解决，望核实解决

**Comment by tianxin1860** [comment]
please refer to #207
