### ISSUE TITLE
ValueError: cannot reshape array of size 16 into shape (6,newaxis)

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#220]
![image](https://user-images.githubusercontent.com/28988355/61642664-f3362680-acd3-11e9-9ada-6227310f9508.png)
 outputs = evaluate(train_exe, train_program, train_py_reader, graph_vars, args.num_labels, "train",
                                   dev_count)
报错

**Comment by tianxin1860** [comment]
> ![image](https://user-images.githubusercontent.com/28988355/61642664-f3362680-acd3-11e9-9ada-6227310f9508.png)
> outputs = evaluate(train_exe, train_program, train_py_reader, graph_vars, args.num_labels, "train",
> dev_count)
> 报错

是运行这个脚本 `script/run_msra_ner.sh` 吗?  数据是我们开源的数据集还是自己的数据？

**Comment by jtyoui** [comment]
> 是我们开源的数据集

是你们的开源的数据集

**Comment by jtyoui** [comment]
> > ![image](https://user-images.githubusercontent.com/28988355/61642664-f3362680-acd3-11e9-9ada-6227310f9508.png)
> > outputs = evaluate(train_exe, train_program, train_py_reader, graph_vars, args.num_labels, "train",
> > dev_count)
> > 报错
> 
> 是运行这个脚本 `script/run_msra_ner.sh` 吗? 数据是我们开源的数据集还是自己的数据？

是你们的开源的数据集
