### ISSUE TITLE
检查paddle是否安装成功失败，module 'paddle.fluid' has no attribute 'install_check'

### ISSUE THREAD

**Issue by jackyrpi2016** [PaddlePaddle/ERNIE#221]
想安装paddle之后测试ERNIE的性能，paddle版本1.3.1。在使用paddle.fluid.install_check.run_check()的时候爆如下错误
![error](https://user-images.githubusercontent.com/25231706/61674868-6b2e3c00-ad28-11e9-8818-f21f0ff2469e.png)

忽略上述问题之后，直接跑ERNIE demo暂时没有发现报错。所以，大概率是1.3.1检验安装成功的属性不是这个。

**Comment by tianxin1860** [comment]
> 想安装paddle之后测试ERNIE的性能，paddle版本1.3.1。在使用paddle.fluid.install_check.run_check()的时候爆如下错误
> ![error](https://user-images.githubusercontent.com/25231706/61674868-6b2e3c00-ad28-11e9-8818-f21f0ff2469e.png)
> 
> 忽略上述问题之后，直接跑ERNIE demo暂时没有发现报错。所以，大概率是1.3.1检验安装成功的属性不是这个。

建议升级到 paddle 1.5.x 版本

**Comment by jackyrpi2016** [comment]
> > 想安装paddle之后测试ERNIE的性能，paddle版本1.3.1。在使用paddle.fluid.install_check.run_check()的时候爆如下错误
> > ![error](https://user-images.githubusercontent.com/25231706/61674868-6b2e3c00-ad28-11e9-8818-f21f0ff2469e.png)
> > 忽略上述问题之后，直接跑ERNIE demo暂时没有发现报错。所以，大概率是1.3.1检验安装成功的属性不是这个。
> 
> 建议升级到 paddle 1.5.x 版本

我看其他人的踩坑博客的时候，他们推荐不要安装最新的paddle，而且我看ERNIE写的是paddle1.3.1，所以才降级安装的。好在跑demo的时候没有报错，就只有这个check有点小问题。

**Comment by jackyrpi2016** [comment]
感谢
