### ISSUE TITLE
怎么把ERNIE改造成双塔的结构，双塔共享ernie内部所有参数？

### ISSUE THREAD

**Issue by yuanzfy** [PaddlePaddle/ERNIE#223]
![image](https://user-images.githubusercontent.com/4515954/61769539-3354f080-ae1d-11e9-90f9-9312b1ec4f3f.png)
请问这样可以吗？

**Comment by tianxin1860** [comment]
> ![image](https://user-images.githubusercontent.com/4515954/61769539-3354f080-ae1d-11e9-90f9-9312b1ec4f3f.png)
> 请问这样可以吗？

可以通过这种方式做双塔结构，reader 端分别生成双塔所需的数据即可
