### ISSUE TITLE
预训练数据预处理-切分边界信息seg_labels如何获取

### ISSUE THREAD

**Issue by Bodhi-Tree** [PaddlePaddle/ERNIE#224]
在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。

**Comment by tianxin1860** [comment]
> 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。

根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述:  `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；

**Comment by Bodhi-Tree** [comment]
> > 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。
> 
> 根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述: `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；

按我的理解，“北京是中国首都”这句话，通过BasicTokenizer处理后得到"北京 是 中国 首都"，然后通过WordpieceTokenizer处理得到“北 京 是 中 国 首 都”，那么“北”是词首0，“京”是非词首1，“是”是词首0，“中”是词首0，“国”是非词首1，“首”是词首0，“都”是非词首1，所以，其seg_labels就是[0 1 0 0 1 0 1]，是这样理解的么？

**Comment by tianxin1860** [comment]
> > > 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。
> > 
> > 
> > 根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述: `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；
> 
> 按我的理解，“北京是中国首都”这句话，通过BasicTokenizer处理后得到"北京 是 中国 首都"，然后通过WordpieceTokenizer处理得到“北 京 是 中 国 首 都”，那么“北”是词首0，“京”是非词首1，“是”是词首0，“中”是词首0，“国”是非词首1，“首”是词首0，“都”是非词首1，所以，其seg_labels就是[0 1 0 0 1 0 1]，是这样理解的么？

对 seg_labels 的理解是正确的，BasicTokenizer 和 WordpieceTokenizer 的处理逻辑建议看一下源码;

**Comment by Bodhi-Tree** [comment]
> > > > 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。
> > > 
> > > 
> > > 根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述: `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；
> > 
> > 
> > 按我的理解，“北京是中国首都”这句话，通过BasicTokenizer处理后得到"北京 是 中国 首都"，然后通过WordpieceTokenizer处理得到“北 京 是 中 国 首 都”，那么“北”是词首0，“京”是非词首1，“是”是词首0，“中”是词首0，“国”是非词首1，“首”是词首0，“都”是非词首1，所以，其seg_labels就是[0 1 0 0 1 0 1]，是这样理解的么？
> 
> 对 seg_labels 的理解是正确的，BasicTokenizer 和 WordpieceTokenizer 的处理逻辑建议看一下源码;

我看了一下，BasicTokenizer直接就把“北京是中国首都”这句话切成了“北 京 是 中 国 首 都”这样一个一个的字符，请问怎么先按词粒度切割呢，不然难以得到它的切分边界信息，有什么推荐的切词工具么？

**Comment by tianxin1860** [comment]
> > > > > 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。
> > > > 
> > > > 
> > > > 根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述: `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；
> > > 
> > > 
> > > 按我的理解，“北京是中国首都”这句话，通过BasicTokenizer处理后得到"北京 是 中国 首都"，然后通过WordpieceTokenizer处理得到“北 京 是 中 国 首 都”，那么“北”是词首0，“京”是非词首1，“是”是词首0，“中”是词首0，“国”是非词首1，“首”是词首0，“都”是非词首1，所以，其seg_labels就是[0 1 0 0 1 0 1]，是这样理解的么？
> > 
> > 
> > 对 seg_labels 的理解是正确的，BasicTokenizer 和 WordpieceTokenizer 的处理逻辑建议看一下源码;
> 
> 我看了一下，BasicTokenizer直接就把“北京是中国首都”这句话切成了“北 京 是 中 国 首 都”这样一个一个的字符，请问怎么先按词粒度切割呢，不然难以得到它的切分边界信息，有什么推荐的切词工具么？

我们基于百度内部分词工具做切分，分词工具涉及一些内部代码库依赖，没有开源;  可以使用开源工具 [LAC](https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/lexical_analysis) 切词;

**Comment by jfkey** [comment]
> > 在ERNIE自定义数据进行预训练中，首先要对数据作预处理，生成与demo数据一样的格式，README文件中说“然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界”、“其中 seg_labels 表示分词边界信息: 0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”，请问这里的切分边界信息seg_labels怎么获取？在tokenization.py文件中没有找到相应的处理函数。
> 
> 根据分词后的结果提取 seg_labels 的逻辑比较容易实现，具体逻辑如 readme 所述: `0表示词首、1表示非词首、-1为占位符, 其对应的词为 CLS 或者 SEP”`，相应代码逻辑可以自己添加；

 请问你们提到的seg_labels是什么？是sentence reordering task任务中的对segments进行排序的classes么？
