### ISSUE TITLE
BERT fineturn任务的脚本

### ISSUE THREAD

**Issue by NotToday** [PaddlePaddle/ERNIE#226]
请问有没有Readme里用BERT做各种中文fineturn任务的脚本？现在需要先验证BERT的效果。

**Comment by tianxin1860** [comment]
> 请问有没有Readme里用BERT做各种中文fineturn任务的脚本？现在需要先验证BERT的效果。

参考 ERNIE readme 中 finetune 任务的脚本，用 `--init_pretraining_params` 参数指定 bert 模型即可
