### ISSUE TITLE
Run environment

### ISSUE THREAD

**Issue by cloudXia777** [PaddlePaddle/ERNIE#23]
具体的运行环境能够介绍吗？

**Comment by tianxin1860** [comment]
> 具体的运行环境能够介绍吗？

@cloudXia777 README中 **安装** 一节已经新增了说明，请参考README；

**Comment by cloudXia777** [comment]
> > 具体的运行环境能够介绍吗？
> 
> @cloudXia777 README中 **安装** 一节已经新增了说明，请参考README；

感谢！
