### ISSUE TITLE
任务数据无法下载 = =

### ISSUE THREAD

**Issue by lrs1353281004** [PaddlePaddle/ERNIE#231]
任务数据下载链接，目前点击之后无法下载，显示下面的提示：
{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"c9208832-a279-4fa7-a874-c57cbb98f43e"}
请问这个情况如何解决呢？

**Comment by OleNet** [comment]
地址更新了， 我们还没有更新到github中， 
可以先用https://ernie.bj.bcebos.com/task_data_zh.tgz

**Comment by nbcc** [comment]
> 任务数据下载链接，目前点击之后无法下载，显示下面的提示：
> {"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"c9208832-a279-4fa7-a874-c57cbb98f43e"}
> 请问这个情况如何解决呢？

已经更新，感谢反馈！
