### ISSUE TITLE
BERT readme 中“预训练 数据预处理”部分， id 化后的数据

### ISSUE THREAD

**Issue by yuzunrui** [PaddlePaddle/ERNIE#234]
BERT readme 中“预训练 数据预处理”部分， id 化后的数据，开头是 1 ，结尾是 2，是代表是CLS和SEP吗，但是在vocab.txt里，CLS和SEP分别对应 101 和 102 ，这部分是否有错误？谢谢

**Comment by ak47-1234** [comment]
CLS对应1和SEP对应2，是中文词典对应结果；CLS对应101和SEP对应102是英文词典的对应结果，没错吧

**Comment by yuzunrui** [comment]
https://bert-models.bj.bcebos.com/chinese_L-12_H-768_A-12.tar.gz
readm中BERT-Base, Chinese的vocab.txt，CLS对应101，SEP对应102
