### ISSUE TITLE
ERNIE2.0 中文的预训练模型

### ISSUE THREAD

**Issue by shuying136** [PaddlePaddle/ERNIE#237]
ERNIE2.0 中文的预训练模型会不会放出来？

**Comment by treper** [comment]
好像只有1.0的下载

**Comment by wq343580510** [comment]
同问  应该近期会放出来吧

**Comment by tolbkni** [comment]
官方QQ群里看到的：
> 目前对外发布了 ERNIE 2.0 的英文预训练模型，ERNIE 2.0 的中文预训练模型暂时没有开源计划

**Comment by hzrpku** [comment]
我收到的消息是会放出来，时间待定
