### ISSUE TITLE
ERNIE 2.0  task embedding

### ISSUE THREAD

**Issue by wq343580510** [PaddlePaddle/ERNIE#239]
论文中预训练的时候不同的任务加入了task embedding，想问下finetune的时候是什么情况？
加没加这个embedding

**Comment by nbcc** [comment]
通过 task embedding 的引入，可以让 pre-trained model 更好的适应不同的预训练任务。

在 Fine-tuning 阶段，一般使用默认的 task id (0，也是开源 finetuning 的默认设置) 即可。

**Comment by yangze01** [comment]
@nbcc 那task embedding在finetune的意义是什么，在finetune阶段并没有引入task specific的embedding信息，另外也会导致pretrain和finetune过程训练方式的不统一。
