### ISSUE TITLE
8g内存-cpu运行，跑情感分类的训练阶段总是奔溃

### ISSUE THREAD

**Issue by Inspiring26** [PaddlePaddle/ERNIE#24]

**Comment by Inspiring26** [comment]
Theoretical memory usage in training: 10522.327 - 11023.390 MB
Load pretraining parameters from /home/h1/LARK/ERNIE/model/params.
script/run_ChnSentiCorp2.sh: 行 30: 23195 已杀死

**Comment by tianxin1860** [comment]
> Theoretical memory usage in training: 10522.327 - 11023.390 MB
> Load pretraining parameters from /home/h1/LARK/ERNIE/model/params.
> script/run_ChnSentiCorp2.sh: 行 30: 23195 已杀死

@Inspiring26 内存不足问题，可以把 batch_size 调小再尝试；
