### ISSUE TITLE
序列标注任务的预测脚本有没有

### ISSUE THREAD

**Issue by onfireisme** [PaddlePaddle/ERNIE#243]
我看有分类任务的预测脚本了。
能不能也把序列标注的脚本也给一下？

**Comment by XIAOLINSHINE** [comment]
感谢您的建议，这个功能点，我们计划在近期启动研发，敬请期待~

**Comment by lrs1353281004** [comment]
> 感谢您的建议，这个功能点，我们计划在近期启动研发，敬请期待~

期待！希望能尽快上线！~ >~<

**Comment by semal** [comment]
是不是在 create_model 的时候如 classify_infer 一样返回相关参数就可以了？

**Comment by semal** [comment]
> 我看有分类任务的预测脚本了。
> 能不能也把序列标注的脚本也给一下？

可以试试 paddlehub 的序列标注功能..
