### ISSUE TITLE
ERNIE自定义预训练时，为什么每次迭代打印出来的learning_rate都是0？

### ISSUE THREAD

**Issue by Bodhi-Tree** [PaddlePaddle/ERNIE#246]
如题，在ERNIE自定义预训练时，设置了学习率为0.0001，但每次迭代打印出来的当前学习率为什么都是0呢？
![image](https://user-images.githubusercontent.com/18651447/62271241-b94ee800-b46a-11e9-9c66-227ddaeb7ea3.png)
![image](https://user-images.githubusercontent.com/18651447/62271289-d08dd580-b46a-11e9-96f9-341ed4380387.png)

**Comment by OleNet** [comment]
应该有warmup机制在， 再加上预训练的总step数很多，导致刚开始的时候，lr非常小， 以至于在打印的时候有效数字显示的都是0。
