### ISSUE TITLE
there is no lcqmc data set in task_data

### ISSUE THREAD

**Issue by steveatgit** [PaddlePaddle/ERNIE#247]

**Comment by OleNet** [comment]
Because of the license, we can't share the data publicly. 
However, you can apply to the dataset owners for LCQMC、BQ Corpus. 

For the LCQMC: http://icrc.hitsz.edu.cn/info/1037/1146.htm, 
For BQ Corpus: http://icrc.hitsz.edu.cn/Article/show/175.html
