### ISSUE TITLE
bert 预训练代码有个小错误

### ISSUE THREAD

**Issue by zle1992** [PaddlePaddle/ERNIE#249]
ERNIE/BERT/reader/pretraining.py

91行与162行应该统一吧
162行应该是大于号

**Comment by XIAOLINSHINE** [comment]
> ERNIE/BERT/reader/pretraining.py
> 
> 91行与162行应该统一吧
> 162行应该是大于号

感谢您指出的问题，我们核查一下

**Comment by tianxin1860** [comment]
> ERNIE/BERT/reader/pretraining.py
> 
> 91行与162行应该统一吧
> 162行应该是大于号

你好，BERT 项目已经迁移至 [这里](https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/language_representations_kit/BERT)
该问题已修复: [https://github.com/PaddlePaddle/models/pull/3024/files](https://github.com/PaddlePaddle/models/pull/3024/files)
