### ISSUE TITLE
请问：是训练数据导致了效果提升还是所用模型及方法，有相关论文或 ablation experiments 结果吗？

### ISSUE THREAD

**Issue by Das-Boot** [PaddlePaddle/ERNIE#25]
如题。

**Comment by bfjia1** [comment]
how to construct train data for MLM task may have an important effect on this matter

**Comment by Das-Boot** [comment]
跪求论文！Begging for paper！

**Comment by ArthurRizar** [comment]
论文就是bert，百度使用了自己的数据集，区别在于bert随机mask某个字，百度随机mask某个词

**Comment by vincehxb** [comment]
https://arxiv.org/pdf/1904.09223v1.pdf
