### ISSUE TITLE
mask issue during pretraining 

### ISSUE THREAD

**Issue by Sherriiie** [PaddlePaddle/ERNIE#250]
共有2个问题，
1) 在这个函数里 _convert_example_to_record()，  下面的label_id是怎么来的？
` if self.is_inference:
            Record = namedtuple('Record',
                                ['token_ids', 'text_type_ids', 'position_ids'])
            record = Record(
                token_ids=token_ids,
                text_type_ids=text_type_ids,
                position_ids=position_ids)
        else:
            if self.label_map:
                label_id = self.label_map[example.label]
            else:
                label_id = example.label

            Record = namedtuple('Record', [
                'token_ids', 'text_type_ids', 'position_ids', 'label_id', 'qid'
            ])

            qid = None
            if "qid" in example._fields:
                qid = example.qid

            record = Record(
                token_ids=token_ids,
                text_type_ids=text_type_ids,
                position_ids=position_ids,
                label_id=label_id,
                qid=qid)`

2) 论文里面的 incremental learning, 是通过多次数据预处理生成不同的mask labels 实现的吗？ 这样的话需要根据不同的数据跑代码多次？

**Comment by OleNet** [comment]
1. 对于训练数据而言，会有一列叫做label, 这个label会读入example中， 即example.label， 在上述代码中也可以看到， label_id通过example.label赋值得到。
2. 这个问题可以参考[论文](http://arxiv.org/abs/1907.12412)的3.1章节，
