### ISSUE TITLE
ERNIE2.0 run_classifier.py fp16 error

### ISSUE THREAD

**Issue by yangze01** [PaddlePaddle/ERNIE#251]
Traceback (most recent call last):
  File "run_classifier.py", line 405, in <module>
    main(args)
  File "run_classifier.py", line 126, in main
    use_fp16=args.use_fp16)
  File "/home/yaze/remote/ERNIE-develop/optimization.py", line 117, in optimization
    param_grads, train_program, startup_prog, loss_scaling)
  File "/home/yaze/remote/ERNIE-develop/utils/fp16.py", line 85, in create_master_params_grads
    master_grad = master_grad / float(loss_scaling)
TypeError: float() argument must be a string or a number, not 'Variable'

**Comment by tianxin1860** [comment]
> Traceback (most recent call last):
> File "run_classifier.py", line 405, in 
> main(args)
> File "run_classifier.py", line 126, in main
> use_fp16=args.use_fp16)
> File "/home/yaze/remote/ERNIE-develop/optimization.py", line 117, in optimization
> param_grads, train_program, startup_prog, loss_scaling)
> File "/home/yaze/remote/ERNIE-develop/utils/fp16.py", line 85, in create_master_params_grads
> master_grad = master_grad / float(loss_scaling)
> TypeError: float() argument must be a string or a number, not 'Variable'

感谢反馈,  我们近期会修复这个问题;   开源结果都是基于 fp32 精度 finetune 的结果，如果是追求最优效果的话，建议使用 fp32；

**Comment by yangze01** [comment]
好的。谢谢。我想测试下当前模型在fp16和fp32的性能差异。另外，mrc文件没有做python2和python3的兼容。
![image](https://user-images.githubusercontent.com/11796873/62410766-4e91de00-b61d-11e9-9b46-c54d74cf4d0b.png)

**Comment by yangze01** [comment]
此外，在windows环境下运行文件会有编码问题。建议open的时候加上encoding=“utf8”。不好意思，提的问题有点多。

**Comment by Meiyim** [comment]
python3兼容性问题、会在下一次提交时修复。fp16问题，我这边已经复现了。估计是paddle 相关api变更导致的，会在下一版提交时修复。
