### ISSUE TITLE
save_inference_model_path生成模型不一致问题

### ISSUE THREAD

**Issue by qibaoyuan** [PaddlePaddle/ERNIE#256]
问题描述：使用ernie做完一个文本多分类模型训练。现在发现每次**重新**调用predict_classifier时，利用ckpt成代用save_inference_model持久化模型对同样的输入预测出来的结果概率值不相同。但是如果不调用save_inference_model，而是使用之前的生成持久化模型，则对同样的输入预测是相同的。
测试环境：cpu和gpu都测试，使用ernie2.0的代码，版本一致

**Comment by tianxin1860** [comment]
请检验一下连续2次生成的 inference_model 里的所有参数文件 md5 是否一致？

**Comment by qibaoyuan** [comment]
经确认检查_cls_out_w 文件前后保存不一致。再次检查数据后发现，训练时的类的数量和做predict时的类的数量不一致，从而导致有些值可能是随机生成的。引以为戒！一定要确定总的类数量一致。可以通过**label_map_config.json**里指定类和id的下标关系。如果实在不记得对应关系的话，需要通过**train.tsv**文件读取确认。

**Comment by tianxin1860** [comment]
> 经确认检查_cls_out_w 文件前后保存不一致。再次检查数据后发现，训练时的类的数量和做predict时的类的数量不一致，从而导致有些值可能是随机生成的。引以为戒！一定要确定总的类数量一致。可以通过**label_map_config.json**里指定类和id的下标关系。如果实在不记得对应关系的话，需要通过**train.tsv**文件读取确认。

训练时设置的 label 数量需要和 predict 时设置的 label 数量一致，因为计算图的网络结构和 label 数量有关，如果 label 数量配置不一致，就会导致定义的计算图网络结构有差异，从而出现多次预测结果不一致;
