### ISSUE TITLE
ur'strings' are syntax errors in Python 3

### ISSUE THREAD

**Issue by cclauss** [PaddlePaddle/ERNIE#258]
In Python 3, you can have a u'string' or an r'string' but a ur'string' is a syntax error...

$ __python3 -c "ur'string'"__  # --> SyntaxError: invalid syntax

https://github.com/PaddlePaddle/ERNIE/blob/develop/utils/cmrc2018_eval.py#L35

**Comment by Meiyim** [comment]
this code is python2.7 only at the moment, python3 compatiblilty and more features are comming soon.
