### ISSUE TITLE
关于ERNIE2.0预训练代码

### ISSUE THREAD

**Issue by daizh** [PaddlePaddle/ERNIE#261]
请问开放的代码中是否有"增量训练"的各种任务的代码呢? (好像没有找到)
如果暂时还未开放这部分代码的话, 请问是否未来有计划开放呢? 
ERNIE2.0增量训练的概念很吸引人, 希望能够增加自己的pretraining任务~

**Comment by Meiyim** [comment]
Duplicate of #253

**Comment by Meiyim** [comment]
pre-training code of ERNIE2.0 is not available at the moment

**Comment by UniqueAndys** [comment]
请问预训练的代码什么时候会公布呢？谢谢

**Comment by ClistaWang** [comment]
ERNIE2.0中文模型将于近期发布，敬请大家关注。

**Comment by ClistaWang** [comment]
ERNIE2.0中文模型将于近期发布，敬请大家关注。
