### ISSUE TITLE
关于Sentence Reordering Task的k的数值

### ISSUE THREAD

**Issue by tanaka-jp** [PaddlePaddle/ERNIE#262]
ERNIE2.0是一篇非常好的论文，令人振奋。
感谢各位作者的努力。

我有一个问题想问一下
关于Sentence Reordering Task，论文中写到，
During the pre-training process of this task, a given paragraph is randomly split into 1 to m segments and then all of the combinations are shuffled by a random permuted order.
We let the pre-trained model to reorganize these permuted segments, modeled as a k-class classification problem where k= 1! + 2! + 3! + ... + m! .  

我的问题是，将一个段落分解为1到m个segment的话，
将被打乱的次序恢复回去，只需要m!种可能性就可以了。
论文中的1! + 2! + 3! + ... + m!的可能性，
是否因为把不相同的segment的个数看作不同情况？

**Comment by Meiyim** [comment]
你的理解没有问题。m会遍历[1, m]之间的取值

**Comment by tanaka-jp** [comment]
知道了，
谢谢

**Comment by ShaneTian** [comment]
请问这里切分为 1 有什么用呢？切分为 1 不是相当于原句子吗？
