### ISSUE TITLE
关于Token-Document Relation Prediction Task

### ISSUE THREAD

**Issue by tanaka-jp** [PaddlePaddle/ERNIE#263]
请问，关于Pre-Training Task，
论文中是这么写的
We add a task to predict whether the token in a segment appears in other segments of the original document. Empirically, the words that appear in many parts of a document are usually
commonly-used words or relevant with the main topics of the document. Therefore, through identifying the key words of a document appearing in the segment, the task can enable the ability of a model to capture the key words of the document to some extent

我有2个问题。

问题1，是如何在input data中标示要预测的token的？
问题2，一个token在文章中出现很多次的话，这个token可能是很常见的token，也有可能是对于这个文章来说很重要的token。直接预测token是否多次出现，应该不能得到一个判断capture the key words的模型。是否有用TFIDF之类的方法做了进一步的处理？

**Comment by OleNet** [comment]
1. 在实践中，预处理数据的时候就会把预测的token的标出来，和token_id, sent_type_id这些信息组织在一起；
2. 没有用TFIDF等方法做进一步处理

**Comment by tanaka-jp** [comment]
请问具体是如何标示的呢？

是在input的seq中，添加了2个专用token吗？
    比方说， <predict> token </predict> 
还是另外添加了一种Emedding？

**Comment by OleNet** [comment]
只是是增加了标签而已，
有点像language model的训练， 训练lm的之前，要记录被mask掉的词的位置还有对应的label
同理，对于上面问题中的“key words”，在训练之前提前记录其位置和label(0/1)就可以了

**Comment by tanaka-jp** [comment]
原来如此，谢谢您的回答。
