### ISSUE TITLE
分类预测脚本多次执行不一致问题

### ISSUE THREAD

**Issue by liuguolian** [PaddlePaddle/ERNIE#266]
直接用ernie的预训练模型做预测，遇到了每次save_inference_model生成的模型不一致的问题，每次执行保存的模型对相同的输入的预测概率值都不一样，check了每次保存的模型 _cls_out_w跟__model__这两个文件的md5值不一样，请问这个是什么问题呢？
执行的是开源代码中的predict_classifier.py脚本，加载的是开源的预训练模型参数。

**Comment by Meiyim** [comment]
我猜测你加载的是开源的pretrain模型而没有自己做finetune？这样一来每次你执行`predict_classifier.py`的时候都只有一部分参数（pretrain）被加载了。而finetune部分的参数(`_cls_out_w`, `_cls_out_b`)是会从重新初始化的，所以每次不一样。

**Comment by liuguolian** [comment]
是直接加载的是开源的pretrain模型，开源的模型不可以直接用来做预测么？？

**Comment by Meiyim** [comment]
如果不finetune进行预测的话，请使用`ernie_encoder`获取输入句子的emedding
