### ISSUE TITLE
ERNIE在DuReader上的实验

### ISSUE THREAD

**Issue by dli1** [PaddlePaddle/ERNIE#267]
请问ERNIE在DuReader实验的相关代码是会放出？
`ERNIE/run_mrc.py`中是针对Squad数据格式的。而DuReader是多文档的阅读理解数据集，和Squad不同。不知道这部分是如何处理的？

**Comment by Meiyim** [comment]
目前还没有计划开源相关代码，
内部对于dureader的处理方式是同squad一样的。用了dureader单文档的子集，转换成squad兼容的格式进行处理。
