### ISSUE TITLE
预训练与finetune时的tokenizer不一致

### ISSUE THREAD

**Issue by prozhuchen** [PaddlePaddle/ERNIE#268]
1. 我发现在ernie的pretrain阶段使用的是CharTokenizer,在finetune阶段使用的是FullTokenizer，这两个tokenizer的逻辑还不一样，请问这个是什么原因呢？不会出现两个阶段不对应的问题吗？

**Comment by Meiyim** [comment]
这两个tokenizer本质是一样的。`FullTokenizer`对标GoogleBert，会做更多的清洗(融合空白符，拆汉字等等等)。用哪个tokenizer取决于数据是否被预先清洗过。

**Comment by prozhuchen** [comment]
但是例如`打印 机 墨盒 型号`这个例子，CharTokenizer会变成`打|##印|机|墨|##盒|型|##号`，而FullTokenizer会变成`打|印|机|墨|盒|型|号`，所以两个产生的最后tokenid也是不同的，这在训练的时候不会产生不对应吗？

**Comment by Meiyim** [comment]
如果是数据文本没有拆字的话，得使用FullTokenizer进行拆分。目前开源的中文模型是基于中文单字粒度的。所以pretrain预处理没有产生`打|##印|机|墨|##盒|型|##号`这样的句子（也就是说实际预处理是基于`FullTokenizer `完成的）

**Comment by prozhuchen** [comment]
哦哦我明白了，你们分词得到seg_label是单独做的，其他id的得到其实还是基于fulltokenizer的逻辑得到的，这么理解是对的吧
