### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: ptr_ should not be null

### ISSUE THREAD

**Issue by liuguolian** [PaddlePaddle/ERNIE#269]
在gpu环境执行获取embedding的脚本报错如下：
Traceback (most recent call last):
File "ernie_encoder.py", line 187, in <module>
main(args)
File "ernie_encoder.py", line 163, in main
return_numpy=False)
File "/home/slurm/job/tmp/job-120971/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: ptr_ should not be null
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/framework/tensor.h:180]
PaddlePaddle Call Stacks: 
0 0x7f9e8e8bad06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1 0x7f9e8fec262cp paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index, unsigned long) + 2428
2 0x7f9e8edc1641p paddle::operators::GPUDropoutKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 225
3 0x7f9e8edc1cd3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUDropoutKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::GPUDropoutKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16>, paddle::operators::GPUDropoutKernel<paddle::platform::CUDADeviceContext, double> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4 0x7f9e8fe44bbcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
5 0x7f9e8fe413ffp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
6 0x7f9e8e9889cbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
7 0x7f9e8e989620p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
8 0x7f9e8e89dfedp
9 0x7f9e8e8d1414p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
10 0x7f9eeffa855fp PyEval_EvalFrameEx + 29855
11 0x7f9eeffaa86dp PyEval_EvalCodeEx + 2061
12 0x7f9eeffa79fcp PyEval_EvalFrameEx + 26940
13 0x7f9eeffaa86dp PyEval_EvalCodeEx + 2061
14 0x7f9eeffa79fcp PyEval_EvalFrameEx + 26940
15 0x7f9eeffaa86dp PyEval_EvalCodeEx + 2061
16 0x7f9eeffaa9a2p PyEval_EvalCode + 50
17 0x7f9eeffd3782p PyRun_FileExFlags + 146
18 0x7f9eeffd4af9p PyRun_SimpleFileExFlags + 217
19 0x7f9eeffea82dp Py_Main + 3149
20 0x7f9eef1e7bd5p __libc_start_main + 245
21 0x4007a1p

**Comment by Meiyim** [comment]
这个看起来像超显存了？能确认机器的状况么 e.g. 显存是否足够（一般来说16G+），该卡是否预先被占用，batch/max_seqlen是否过大？

**Comment by liuguolian** [comment]
噢 我的batch_size设置的500，max_seqlen是默认的128，那我把batch_size改小试下吧

**Comment by liuguolian** [comment]
batch_size改小后没有再出现上面的错误，但是换了一个错误信息。

**Comment by liuguolian** [comment]
@Meiyim
错误信息如下，麻烦在帮看看是啥错误哈。
*** Aborted at 1565236796 (unix time) try "date -d @1565236796" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGFPE (@0x7f8c1c665f29) received by PID 23016 (TID 0x7f8c7ce70700) from PID 476471081; stack trace: ***
@ 0x7f8c7c626160 (unknown)
@ 0x7f8c1c665f29 paddle::operators::math::UnpaddingLoDTensorFunctor<>::operator()()
@ 0x7f8c1bd6979f paddle::operators::SequenceUnpadOpKernel<>::Compute()
@ 0x7f8c1bd69943 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators21SequenceUnpadOpKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_lEEEEclEPKcSI_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
@ 0x7f8c1c7ddbbc paddle::framework::OperatorWithKernel::RunImpl()
@ 0x7f8c1c7da3ff paddle::framework::OperatorBase::Run()
@ 0x7f8c1b3219cb paddle::framework::Executor::RunPreparedContext()
@ 0x7f8c1b322620 paddle::framework::Executor::Run()
@ 0x7f8c1b236fed _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlRNS2_9framework8ExecutorERKNS4_11ProgramDescEPNS4_5ScopeEibbE64_vIS6_S9_SB_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNEST_
@ 0x7f8c1b26a414 pybind11::cpp_function::dispatcher()
@ 0x7f8c7c94155f PyEval_EvalFrameEx
@ 0x7f8c7c94386d PyEval_EvalCodeEx
@ 0x7f8c7c9409fc PyEval_EvalFrameEx
@ 0x7f8c7c94386d PyEval_EvalCodeEx
@ 0x7f8c7c9409fc PyEval_EvalFrameEx
@ 0x7f8c7c94386d PyEval_EvalCodeEx
@ 0x7f8c7c9439a2 PyEval_EvalCode
@ 0x7f8c7c96c782 PyRun_FileExFlags
@ 0x7f8c7c96daf9 PyRun_SimpleFileExFlags
@ 0x7f8c7c98382d Py_Main
@ 0x7f8c7bb80bd5 __libc_start_main
@ 0x4007a1 (unknown)
@ 0x0 (unknown)
