### ISSUE TITLE
请问ERNIE 2.0  为什么没有中文的？

### ISSUE THREAD

**Issue by 90217** [PaddlePaddle/ERNIE#270]
请问 ERNIE 2.0  为什么没有中文的？

**Comment by huntzhan** [comment]
https://github.com/PaddlePaddle/ERNIE/issues/261
https://github.com/PaddlePaddle/ERNIE/issues/237

**Comment by XIAOLINSHINE** [comment]
> 请问 ERNIE 2.0 为什么没有中文的？
ERNIE2.0中文模型将于近期发布，敬请大家关注。
