### ISSUE TITLE
关于多答案的阅读理解任务

### ISSUE THREAD

**Issue by AzureDreamDing** [PaddlePaddle/ERNIE#271]
请问在阅读理解任务，如果一个问题的答案包含2个以上的情况（多个答案出现在文本的不同位置），现在支持模型训练与预测吗？

如果不支持的话，理论上是否可行？近期是否有更新的计划？

谢谢！

**Comment by Meiyim** [comment]
目前代码不支持这样的数据集。

**Comment by AzureDreamDing** [comment]
@Meiyim 谢谢答复。请问现在有理论支持这样的模型吗？（多个答案出现在不同位置）感觉如果答案不连续的话，目前的nlp模型较难实现的样子。

谢谢！

**Comment by wang001** [comment]
可以考虑用seq2seq，同时生成多个答案，中间用特定token连接起来。或者是拆成多对QA（不知道效果会怎么样）
