### ISSUE TITLE
LARK/BERT finetune 阅读理解任务，多卡预测发现出现数据丢失

### ISSUE THREAD

**Issue by Steffy-zxf** [PaddlePaddle/ERNIE#275]
利用BERT finetune阅读理解任务（SQuAD），发现源码run_squad.py 预测时用的时单卡，训练时用的是可以多卡，我试着按照多卡训练的方式改写预测，使得预测时也可以支持多卡。以下是 我改写的 多卡预测：
![image](https://user-images.githubusercontent.com/48793257/62844157-ea90a900-bcf1-11e9-9963-79fd645d05a8.png)

并且同时将batching.py/pad_batch_data()方法的max_len改为 全局的max_seq_len，而不是每个batch下sample的最大长度，
最后运行发现错误，输入的all_features和返回的all_results，数量不一致：
![image](https://user-images.githubusercontent.com/48793257/62844143-caf98080-bcf1-11e9-8168-17eac3b99e6e.png)

**Comment by zhanghan1992** [comment]
在N卡预测时，最后一个step如果凑不到N个batch就会把数据丢弃。建议用单卡预测。
