### ISSUE TITLE
对于预训练mask单词的疑问

### ISSUE THREAD

**Issue by prozhuchen** [PaddlePaddle/ERNIE#276]
在看batching.py的mask一个batch数据的代码时，我发现mask_pos和mask_label一直是一个一维矩阵，在处理最后观察数据维度时也证明了这个结论
```
(Pdb) sent_id.shape
(6, 19, 1)
(Pdb) mask_pos.shape
(9, 1)
```
感觉这个不对吧，mask_pos和mask_label应该是个二维矩阵，比如最后维度应该是(6,9,1)这种的吧？请知晓的同学解答一下疑惑

**Comment by prozhuchen** [comment]
而且我看google bert的预处理代码中，他们处理出来的数据每一个样本都是有自己的mask label的。请问这是不是ernie某些实现上的故意而为呢

**Comment by PROoshio** [comment]
batch_src_ids在传网络时的shape为[bsz, max_seq_len, 1]，为了计算[mask]位置的损失，需要用一个pos_index去获取[mask]位置的隐层输出，也就是mask_pos及其对应的label : mask_label；又为了方便计算这些mask的损失，干脆直接用一个1维的mask pos将一个batch中所有sequence的mask取出，计算损失。
