### ISSUE TITLE
ERNIE 2.0 多任务学习的预训练代码何时会放

### ISSUE THREAD

**Issue by Albert-Ma** [PaddlePaddle/ERNIE#278]

**Comment by PROoshio** [comment]
ERNIE2.0的中文模型近期会发布，句代码开源还在讨论中，敬请大家关注。

**Comment by Albert-Ma** [comment]
> ERNIE2.0的中文模型近期会发布，句代码开源还在讨论中，敬请大家关注。

请问 ERNIE 1.0 有没有在英文语料上预训练过，像bert那样，结果如何？
