### ISSUE TITLE
Pretrain method

### ISSUE THREAD

**Issue by vanche** [PaddlePaddle/ERNIE#280]
Hi, I wanna ask question to understand your paper.
In your paper, you said “when adding a new task we initialize the parameters of the previous one. ”
If the previous parameter is initialized, how can the model get knowledge of previous ones? I’m not sure 
And “Whenever a new task is a introduced,  it would be trained with the previous ones.” this means joint learning or something else?

Also I want to know how I can find this procedure in your code

**Comment by PROoshio** [comment]
When adding a new task we initialize the parameters with those of the previous one ~ And secondly, without being initialized with the previous model, it can be treated as a kind of multi-task learning in the pre-train level.
