### ISSUE TITLE
NER任务中，如何利用 Fine-tuning 得到的模型对新数据进行批量预测？

### ISSUE THREAD

**Issue by yechens** [PaddlePaddle/ERNIE#281]
官方例子中，给了 predict_classifier.py 来进行分类任务的预测，请问一下对于微调后的 ner 模型，如何进行批量预测呢？

**Comment by sandyhouse** [comment]
可以参考script/zh_task/ernie_base/run_msra_ner.sh

**Comment by yechens** [comment]
> 可以参考script/zh_task/ernie_base/run_msra_ner.sh

谢谢，用这个脚本测试得到了F1等值，但是如何获取模型预测的输出结果呀（预测的标注序列）

**Comment by cjliux** [comment]
同样遇到这个问题，求解答。
请问ernie输出的预测结果文件当中，哪个才是最优模型的输出？还有就是模型输出的标签与文本是如何对应的（目测有错位）？

以下是运行run_msra_ner.sh之后，标签错一位抽取的实体结果实例（test_result.5.final），结果比较不堪：


欧;美;港;台
趋;势;大;量
几;百;；;珍
句;中;之;，
在;集;有;道

一;些;很;是
旧;”;“;传
烈;日;树;下
师;，;茶;不
叶;染;，;春
学;老;就;千
腾;出;手;从
，;翻;眼;白
了
事
，;称;大;足
说;：;对;宝
映;贫;生;活
浴;太;图;》
的;千;佛;中
礼;部;杨;次
也;有;来;米
这;片;老;的
，;既;强;了
知;只;靠;想
十;分;有;特
笑
往;“;反;”
母;亲;没;有
飞;去
子;成;、;望
个;新;，;结
进;了;的;确
有;声
晖;沐;着;庄
锻;炼;提;高
们;的;命;，
高;了;对;美
技;能;机;会
、;畜;局;领
贫;困;生
大;代;等;搞
基;层;要;送
所;基;的;文
场;将;行;开
慰;[UNK]
终;于;到;了
们;开;和;溥
日;子;流;淌
