### ISSUE TITLE
关于ERNIE在MSRA上的数据预处理

### ISSUE THREAD

**Issue by ZacBi** [PaddlePaddle/ERNIE#282]
ERNIE的msra-ner任务中看到最后一个全连接层的输出等于num_labels，请问一下[CLS]，[SEP]，[PAD]这些的label是被标记为'O'了吗.

**Comment by PROoshio** [comment]
这些字符都没有计算loss，都标记为'O'

**Comment by ZacBi** [comment]
> 这些字符都没有计算loss，都标记为'O'

好的,谢谢!
