### ISSUE TITLE
Publish ERNIE 2.0 results on paperswithcode.com

### ISSUE THREAD

**Issue by LifeIsStrange** [PaddlePaddle/ERNIE#288]
Paperswithcode.com is the world reference for observing state of the art results on nlp tasks.
The community already posted some of your results but for now ERNIE 2.0 has not a single first place on leaderboards. 
Your paper claim to beat BERT and even XLnet. 
If that's true then publish your results on paperswithcode.com as every researcher should. https://paperswithcode.com/paper/ernie-20-a-continual-pre-training-framework

**Comment by wangshuohuan** [comment]
Most of the top leaderboard submissions are ensembles and muli-task learning. We mainly focus on single-task single models for comparision previously. We will do ensemble experiments and release the result in future.
