### ISSUE TITLE
ernie_encoder 中的 token embedding 缺少 0_padding

### ISSUE THREAD

**Issue by ydli-ai** [PaddlePaddle/ERNIE#290]
[词经过 ERNIE 编码后的 Embedding 表示](https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#faq1-%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%BE%93%E5%85%A5%E5%8F%A5%E5%AD%90%E8%AF%8D%E7%BB%8F%E8%BF%87-ernie-%E7%BC%96%E7%A0%81%E5%90%8E%E7%9A%84-embedding-%E8%A1%A8%E7%A4%BA) 没有 zero_padding 。 
例如对 chnsenticorp/dev.tsv 生成的句 embedding 是 (1200,768)，词 embedding 是 (97838,768)，是否考虑填充成 (1200,128,768)？

**Comment by zhanghan1992** [comment]
可以根据每个句子的长度来计算位置，提取相应的embedding
