### ISSUE TITLE
ImportError: No module named paddle.fluid

### ISSUE THREAD

**Issue by Zengpr** [PaddlePaddle/ERNIE#30]
执行bash script/pretrain.sh提示：
ImportError: No module named paddle.fluid

但单独使用 python3 进入python解释器，然后使用import paddle.fluid并没有报这个错

**Comment by bfjia1** [comment]
i just pip install paddlepaddle, then mv the pretrain script to "train.py"'s dictionary, finally run it and success

**Comment by Zengpr** [comment]
@jiabinfeng I pip install paddlepaddle too, mv the pretrain script under the ERNIE directory? but I'm not successully
![2019-03-18 11-39-00屏幕截图](https://user-images.githubusercontent.com/22451062/54505413-ad0e3680-4972-11e9-9309-67878d970b86.png)

**Comment by bfjia1** [comment]
> @jiabinfeng I pip install paddlepaddle too, mv the pretrain script under the ERNIE directory? but I'm not successully
> ![2019-03-18 11-39-00屏幕截图](https://user-images.githubusercontent.com/22451062/54505413-ad0e3680-4972-11e9-9309-67878d970b86.png)

![image](https://user-images.githubusercontent.com/31401864/54530978-2d5a8900-49bf-11e9-9a23-bf410a67f40b.png)
 i just run the code in command line previously, when i see your pic, i try to run this code in pycharm, 
first i met the same problem as you, this is caused by python env, so i change it and done all

**Comment by Zengpr** [comment]
@jiabinfeng I have create a new env, and pip install paddlepaddle-gpu, but I still met the problem 
![2019-03-19 09-04-04屏幕截图](https://user-images.githubusercontent.com/22451062/54573242-83aee280-4a26-11e9-917c-7adc5bd766f1.png)

**Comment by LCG22** [comment]
我也遇到了同样的问题，目前只能在 cmd 中运行

**Comment by Zengpr** [comment]
我cmd都不行呀

**Comment by LCG22** [comment]
> 我cmd都不行呀

或者你应该试试 Anaconda prompt

**Comment by Zengpr** [comment]
@LCG22 什么意思

**Comment by LCG22** [comment]
> @LCG22 什么意思

类似 cmd 的

**Comment by kuke** [comment]
@Zengpr 可能你的环境中存在多个python环境，你可以解释一下运行 script 的时候与cmd启动的是同一个python解释器

**Comment by Zengpr** [comment]
@kuke 直接把pretrain.sh的内容在cmd运行成功了，谢谢！
