### ISSUE TITLE
Experiment using state of the art optimizer

### ISSUE THREAD

**Issue by LifeIsStrange** [PaddlePaddle/ERNIE#300]
RAdam is consistently better than adam.
https://arxiv.org/pdf/1908.03265v1

Lookahead merits to be tried too https://arxiv.org/pdf/1907.08610v1.pdf
Maybe it can be used on top of RAdam.

**Comment by ak47-1234** [comment]
this is good research direction

**Comment by nbcc** [comment]
> RAdam is consistently better than adam.
> https://arxiv.org/pdf/1908.03265v1
> 
> Lookahead merits to be tried too https://arxiv.org/pdf/1907.08610v1.pdf
> Maybe it can be used on top of RAdam.

they do a great job! worth a try.

**Comment by LifeIsStrange** [comment]
Wait!
"Maybe it can be used on top of RAdam"
My intuition turned out to be right! 

There is now a ready made combination of both Optimizers:
https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d
This is the one you should try, Ranger.

https://forums.fast.ai/t/meet-ranger-radam-lookahead-optimizer/52886

Some insights:
https://forums.fast.ai/t/how-we-beat-the-5-epoch-imagewoof-leaderboard-score-some-new-techniques-to-consider/53453

Edit:
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

https://github.com/mgrankin/over9000
Over9000 show that it's rangerLARS is even better than Ranger.

**Comment by LifeIsStrange** [comment]
@nbcc so did it not bring any positive result or was the research postponed?

Ranger is continuously improving, 
They have now added a new technique called gradient centralization that has once again beaten the state of the art
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

**Comment by LifeIsStrange** [comment]
@nbcc friendly reminder this is a promising research direction for ERNIE 4.0
