### ISSUE TITLE
运行过程中电脑关机，程序还没有运行完，再开机发现多了一个checkpoint文件夹，有没有可能恢复继续运行？

### ISSUE THREAD

**Issue by haosiqing** [PaddlePaddle/ERNIE#306]
运行过程中电脑关机，程序还没有运行完，再开机发现多了一个checkpoint文件夹，有没有可能恢复继续运行？

![11](https://user-images.githubusercontent.com/50686292/63923428-21e4b100-ca79-11e9-9370-a8f184059de1.png)
![22](https://user-images.githubusercontent.com/50686292/63923435-24470b00-ca79-11e9-86fd-bb34b1ea8e75.png)
![33](https://user-images.githubusercontent.com/50686292/63923438-25783800-ca79-11e9-8396-d8a4b4d40d7c.png)

**Comment by haosiqing** [comment]
![11](https://user-images.githubusercontent.com/50686292/63923458-3163fa00-ca79-11e9-9f7e-3c8847b03066.png)
![22](https://user-images.githubusercontent.com/50686292/63923467-332dbd80-ca79-11e9-8fd3-2074b1845864.png)
![33](https://user-images.githubusercontent.com/50686292/63923470-345eea80-ca79-11e9-8338-6c7560a6365a.png)

**Comment by ak47-1234** [comment]
如果checkpoint有已保存模型，可以重新加载，继续训练

**Comment by haosiqing** [comment]
> 如果checkpoint有已保存模型，可以重新加载，继续训练

但我不知道有没有保存模型，哪个是已保存模型，可以帮我看一下吗

**Comment by ak47-1234** [comment]
每个step_*就是一个模型，你可以加载最后一个

**Comment by haosiqing** [comment]
> 每个step_*就是一个模型，你可以加载最后一个

非常感谢您的耐心回答！但是我不知道用什么样的加载语句来加载最后一个模型，在网上查了一些命令语句好像也不适用于这个问题

**Comment by haosiqing** [comment]
> 每个step_*就是一个模型，你可以加载最后一个

我使用init_checkpoint加载了最后一个模型，发现还是从epoch0开始训练10个epoch，我之前已经训练到了epoch7，怎样才可以接着中断时候继续训练而不是从epoch0开始呢，直接修改参数epoch=3可以吗

**Comment by ak47-1234** [comment]
这个是从新编号的
