### ISSUE TITLE
请问这个qid是什么？为什么在训练的时候加上？而推理的时候去掉

### ISSUE THREAD

**Issue by wang001** [PaddlePaddle/ERNIE#307]
https://github.com/PaddlePaddle/ERNIE/blob/088a5ce635e9f1529a17cfe8f477bb9427f65ec0/reader/task_reader.py#L347

**Comment by ak47-1234** [comment]
qids是每个query的唯一标示，如果是排序任务的时候是有用的

**Comment by wang001** [comment]
谢谢
