### ISSUE TITLE
ernie是否可以将三句话作为输入进行分类

### ISSUE THREAD

**Issue by Kevinlsy** [PaddlePaddle/ERNIE#311]
我的输入是个三元组：格式如下： 
`**[CLS]A[SEP]B[SEP]C[SEP]**`

A:是query，B和C是推荐的title。我的目的：是想对AB之间相关性和AC之间的相关性进行比较，label（0：代表AB的相关性>AC, 1:代表AB的相关性<AC）
当用SEP分割时：
tokens:`[CLS]你的名字[SEP]名字是什么[SEP]名字叫[SEP]`
text_type_id:`0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2`

这样的输入会报错：不太清楚代码哪里规定了text_type_id只能是[0,1]
![image](https://user-images.githubusercontent.com/18109329/64099549-1e646900-cd9c-11e9-9f44-4d22c2a45fc4.png)

如果我想用ERNIE达到这个分类的目的，怎么处理输入或者有什么其他更好的办法？

**Comment by nbcc** [comment]
建议使用 triplet loss 来处理这类问题，实现见：https://github.com/PaddlePaddle/models/tree/4a534f48cad1f8711251e0a2480e2607aa88bf63/PaddleNLP/similarity_net

**Comment by Kevinlsy** [comment]
> 建议使用 triplet loss 来处理这类问题，实现见：https://github.com/PaddlePaddle/models/tree/4a534f48cad1f8711251e0a2480e2607aa88bf63/PaddleNLP/similarity_net

@nbcc 我看了下上面的代码，我应该需要把Ernie弄成双塔，然后左右塔的参数共享，损失函数是hinge_loss，这样大致没有问题把？能和我说下你hi的账号吗？如果有问题，能hi上直接问你吗？ 谢谢。

**Comment by nbcc** [comment]
> > 建议使用 triplet loss 来处理这类问题，实现见：https://github.com/PaddlePaddle/models/tree/4a534f48cad1f8711251e0a2480e2607aa88bf63/PaddleNLP/similarity_net
> 
> @nbcc 我看了下上面的代码，我应该需要把Ernie弄成双塔，然后左右塔的参数共享，损失函数是hinge_loss，这样大致没有问题把？能和我说下你hi的账号吗？如果有问题，能hi上直接问你吗？ 谢谢。

hinge_loss 或 logloss 都可以。
