### ISSUE TITLE
哪个脚本是运行mask的finetuning任务的

### ISSUE THREAD

**Issue by yowrhihoil** [PaddlePaddle/ERNIE#312]

**Comment by MrPig** [comment]
能再描述清楚一点么？目前finetune的任务里面没有mask相关的任务，也不需要对输入进行mask。不过Pretrain的过程是有mask相关的任务：Masked LM

**Comment by yowrhihoil** [comment]
> 能再描述清楚一点么？目前finetune的任务里面没有mask相关的任务，也不需要对输入进行mask。不过Pretrain的过程是有mask相关的任务：Masked LM

只经过pretrain完的模型，可以直接预测mask任务吗？我以为也要finetune才行，我想训练适用于我自己数据的mask模型呢？

**Comment by MrPig** [comment]
1）pretrain后的模型，可以直接用于完形填空类似的任务（预测mask的词）
2）pretrain消耗的GPU资源比较大，如果没有足够的GPU资源，建议还是直接用ernie pretrain好的模型

**Comment by yowrhihoil** [comment]
> 1）pretrain后的模型，可以直接用于完形填空类似的任务（预测mask的词）
> 2）pretrain消耗的GPU资源比较大，如果没有足够的GPU资源，建议还是直接用ernie pretrain好的模型

原来如此，可是预测mask掉的词的脚本，好像也没找到

**Comment by MrPig** [comment]
这个需求比较小众，没有提供对应预测脚本，可以参考一下pretrain的源码改一下

**Comment by yowrhihoil** [comment]
> 这个需求比较小众，没有提供对应预测脚本，可以参考一下pretrain的源码改一下

谢谢，已经没问题了
