### ISSUE TITLE
运行predict_classfier.py报错Type names and field names must be valid identifiers: "['text_a']"

### ISSUE THREAD

**Issue by silverspruce** [PaddlePaddle/ERNIE#318]
使用predict_classfier.py加载模型进行批量预测，报错提示Type names and field names must be valid identifiers: "['text_a']"，预测的文本格式为单列tsv文件，标签名为text_a，如果改为两列['text_a','label'],其中label列中数据填空‘’，运行不报错。正确的预测文件格式应该是怎样的？

**Comment by silverspruce** [comment]
使用predict_classfier.py加载模型进行批量预测，报错提示Type names and field names must be valid identifiers: "['text_a']"，预测的文本格式为单列tsv文件，标签名为text_a，如果改为两列['text_a','label'],其中label列中数据填空‘’，运行不报错。正确的预测文件格式应该是怎样的？

**Comment by tianxin1860** [comment]
请确保本地更新到最新的代码，正确的预测文件格式是: text_a、text_b(可选)

**Comment by Magic-Fy** [comment]
> 请确保本地更新到最新的代码，正确的预测文件格式是: text_a、text_b(可选)

 The code has been updated latest, but same problem with @silverspruce.The input file has only one column, with first row "text_a". Please have a try.

Is it related to the input format? My train file is like "label\ttext_a".

**Comment by operaculus** [comment]
with the lastest code, the "label" column are required for inference
