### ISSUE TITLE
core.31749 ERNIE部署在centos下，生产大量的文件。文件名叫做core.31xx。每一个文件大概有1G左右

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#320]
![image](https://user-images.githubusercontent.com/28988355/64663169-83dfe600-d47d-11e9-8164-9c12fd10509b.png)

**Comment by tianxin1860** [comment]
请描述一下具体操作，执行了哪个脚本？数据格式是什么？
