### ISSUE TITLE
sequenceUnpadOp访问空指针

### ISSUE THREAD

**Issue by buaasky** [PaddlePaddle/ERNIE#321]
ernie模型未做修改，只修改了输入数据。

*** Aborted at 1568186213 (unix time) try "date -d @1568186213" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGFPE (@0x7f07a4276f29) received by PID 13469 (TID 0x7f0804608700) from PID 18446744072168632105; stack trace: ***
@ 0x7f0803dbe160 (unknown)
@ 0x7f07a4276f29 paddle::operators::math::UnpaddingLoDTensorFunctor<>::operator()()
@ 0x7f07a397a79f paddle::operators::SequenceUnpadOpKernel<>::Compute()
@ 0x7f07a397a943 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EJNS0_9operators21SequenceUnpadOpKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_lEEEEclEPKcSI_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
@ 0x7f07a43eebbc paddle::framework::OperatorWithKernel::RunImpl()
@ 0x7f07a43eb3ff paddle::framework::OperatorBase::Run()
@ 0x7f07a2f329cb paddle::framework::Executor::RunPreparedContext()
@ 0x7f07a2f33620 paddle::framework::Executor::Run()
@ 0x7f07a2e47fed _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL13pybind11_initEvEUlRNS2_9framework8ExecutorERKNS4_11ProgramDescEPNS4_5ScopeEibbE64_vIS6_S9_SB_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNEST_
@ 0x7f07a2e7b414 pybind11::cpp_function::dispatcher()
@ 0x7f08040d955f PyEval_EvalFrameEx
@ 0x7f08040db86d PyEval_EvalCodeEx
@ 0x7f08040d89fc PyEval_EvalFrameEx
@ 0x7f08040db86d PyEval_EvalCodeEx
@ 0x7f08040d89fc PyEval_EvalFrameEx
@ 0x7f08040db86d PyEval_EvalCodeEx
@ 0x7f08040db9a2 PyEval_EvalCode
@ 0x7f0804104782 PyRun_FileExFlags
@ 0x7f0804105af9 PyRun_SimpleFileExFlags
@ 0x7f080411b82d Py_Main
@ 0x7f0803318bd5 __libc_start_main
@ 0x4007a1 (unknown)
@ 0x0 (unknown)

**Comment by tianxin1860** [comment]
麻烦帖一下你的输入数据
