### ISSUE TITLE
Problem with run_drcd.sh

### ISSUE THREAD

**Issue by wead-hsu** [PaddlePaddle/ERNIE#322]
- I was going to replicate the results of DRCD with ERNIE and encountered a problem. I did as follows:

  1. Download ERNIE1.0 (max_len_512) (2.0 is not available yet) into a directory. i.e., /home/weidi.xwd/weidi.xwd/models/ERNIE_1.0_max-len-512/ 
  2. Install the paddlepaddle and download the ERNIE project.
  3. Download DRCD dataset into a directory, i.e., /home/weidi.xwd/weidi.xwd/data/raw/DRCD-master/.
  4. Modify the MODEL_PATH and TASK_DATA_PATH as :

`
set -eux

export FLAGS_eager_delete_tensor_gb=0
export FLAGS_sync_nccl_allreduce=1
export CUDA_VISIBLE_DEVICES=0,1,2,3
MODEL_PATH="/home/weidi.xwd/weidi.xwd/models/ERNIE_1.0_max-len-512/"
TASK_DATA_PATH="/home/weidi.xwd/weidi.xwd/data/raw/DRCD-master/"

python ./finetune_launch.py  \
    --nproc_per_node 8 \
    --selected_gpus 0,1,2,3,4,5,6,7 \
    --node_ips $(hostname -i) \
    --node_id 0 \
run_mrc.py --use_cuda true\
                    --batch_size 16 \
                    --in_tokens false\
                    --use_fast_executor true \
                    --checkpoints ./checkpoints \
                    --vocab_path ${MODEL_PATH}/vocab.txt  \
                    --ernie_config_path ${MODEL_PATH}/ernie_config.json \
                    --do_train true \
                    --do_val true \
                    --do_test true \
                    --verbose true \
                    --save_steps 1000 \
                    --validation_steps 100 \
                    --warmup_proportion 0.0 \
                    --weight_decay  0.01 \
                    --epoch 2 \
                    --max_seq_len 512 \
                    --do_lower_case true \
                    --doc_stride 128 \
                    --train_set ${TASK_DATA_PATH}/drcd/train.json \
                    --dev_set ${TASK_DATA_PATH}/drcd/dev.json \
                    --test_set ${TASK_DATA_PATH}/drcd/test.json \
                    --learning_rate 5e-5 \
                    --num_iteration_per_drop_scope 1 \
                    --init_pretraining_params ${MODEL_PATH}/params \
                    --skip_steps 10
`
Then, an error is thrown:

![image](https://user-images.githubusercontent.com/7287692/64684045-f4efbf80-d4b6-11e9-94ad-85723acae139.png)

**Comment by wead-hsu** [comment]
Anybody helps?

**Comment by tianxin1860** [comment]
> Anybody helps?

Please check the `--init_pretraining_param` config,   which must be  a correct directory contains model parameters; 
![image](https://user-images.githubusercontent.com/6829601/64783350-28574a80-d59a-11e9-89b5-334cf1be69d3.png)
