### ISSUE TITLE
XNLI test数据集有多少数据

### ISSUE THREAD

**Issue by shizhediao** [PaddlePaddle/ERNIE#323]
你好，我看ERNIE paper汇报的是2.5K in test dataset which is different from mine.
Could you give me details?

**Comment by shizhediao** [comment]
有没有数据集链接？谢谢

**Comment by tianxin1860** [comment]
> 有没有数据集链接？谢谢

文档中有提供数据下载地址: [数据下载](https://ernie.bj.bcebos.com/task_data_zh.tgz)

**Comment by shizhediao** [comment]
非常感谢
那么论文中有个小错误，XNLI TEST # = 5K, not 2.5K
只是一个minor问题，感谢提供数据集！
