### ISSUE TITLE
is encode() api available?

### ISSUE THREAD

**Issue by ares5221** [PaddlePaddle/ERNIE#328]
such as https://github.com/hanxiao/bert-as-service by xiaohan, is ernie have the encode() function 
and make it easier to encode a sentence to a vector

**Comment by OleNet** [comment]
The service will be released in early October.
You can refer to [here](https://github.com/PaddlePaddle/ERNIE#faq1-how-to-get-sentencetokens-embedding-of-ernie) for now.

**Comment by ares5221** [comment]
> The service will be released in early October.
> You can refer to [here](https://github.com/PaddlePaddle/ERNIE#faq1-how-to-get-sentencetokens-embedding-of-ernie) for now.

got it ,thks
