### ISSUE TITLE
显存不足报错了，有什么办法可以解决？

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#329]
[INFO] 2019-09-22 23:04:45,993 [run_sequence_labeling.py:  262]:        epoch: 0, progress: 992/20864, step: 10, loss: 0.134486, f1: 0.000000, precision: 0.000000, recall: 0.000000, speed: 0.492997 steps/s
W0922 23:04:48.649623 32055 system_allocator.cc:121] Cannot malloc 64.0002 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.5. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0
F0922 23:04:48.649775 32055 legacy_allocator.cc:201] Cannot allocate 64.000000MB in GPU 0, available 60.062500MBtotal 11996954624GpuMinChunkSize 256.000000BGpuMaxChunkSize 5.246019GBGPU memory used: 10.955627GB

**Comment by jtyoui** [comment]
![image](https://user-images.githubusercontent.com/28988355/65405370-6829f780-de0e-11e9-8ffa-b9cdcf3e63ba.png)

**Comment by jtyoui** [comment]
![image](https://user-images.githubusercontent.com/28988355/65405398-84c62f80-de0e-11e9-9e8d-56861967b548.png)

**Comment by jtyoui** [comment]
![image](https://user-images.githubusercontent.com/28988355/65409163-92cd7d80-de19-11e9-9179-31520b758258.png)

**Comment by oyxuan-11** [comment]
可以把改一下FLAGS 的值在跑一下
建议改动的FLAGS 设置如下：
FLAGS_fraction_of_gpu_memory_to_use=1
FLAGS_memory_fraction_of_eager_deletion=1	

FLAGS_reallocate_gpu_memory_in_mbenvironment=0.3这一行注释掉
