### ISSUE TITLE
ERNIE多机多卡多线程，fiunte分类任务，出现not ready endpoints

### ISSUE THREAD

**Issue by sunbrother99** [PaddlePaddle/ERNIE#330]
二机16卡finetune二分类任务，在run_classify.py之前调用finetune_lauch.py，第二节节点用不上，一直出现not ready endpointsL
![image](https://user-images.githubusercontent.com/24203046/65421073-632c6e80-de35-11e9-8e1e-ba6a3a634b49.png)
![image](https://user-images.githubusercontent.com/24203046/65421130-92db7680-de35-11e9-9e9c-e0754c143b42.png)
![image](https://user-images.githubusercontent.com/24203046/65421298-fe254880-de35-11e9-90fd-513e802c4150.png)

**Comment by Meiyim** [comment]
可否贴一下你启动的脚本？

**Comment by sunbrother99** [comment]
![image](https://user-images.githubusercontent.com/24203046/65424912-4f860580-de3f-11e9-9b49-06bc24b2dbd2.png)
![image](https://user-images.githubusercontent.com/24203046/65424971-7f350d80-de3f-11e9-95be-97185ccf943b.png)

![image](https://user-images.githubusercontent.com/24203046/65424998-8f4ced00-de3f-11e9-96e6-d1fa26a143ec.png)

**Comment by Meiyim** [comment]
针对多机这种情况，`--node_id`应该是一个变量，在0号机器上为0，在1号机器上应该为1。

**Comment by sunbrother99** [comment]
if args.is_distributed:
        trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))
        worker_endpoints_env = os.getenv("PADDLE_TRAINER_ENDPOINTS")
        current_endpoint = os.getenv("PADDLE_CURRENT_ENDPOINT")
        worker_endpoints = worker_endpoints_env.split(",")
        trainers_num = len(worker_endpoints)
        
        log.info("worker_endpoints:{} trainers_num:{} current_endpoint:{} \
              trainer_id:{}".format(worker_endpoints, trainers_num,
                                    current_endpoint, trainer_id))

        # prepare nccl2 env.
        config = fluid.DistributeTranspilerConfig()
        config.mode = "nccl2"
        t = fluid.DistributeTranspiler(config=config)
        t.transpile(
            trainer_id,
            trainers=worker_endpoints_env,
            current_endpoint=current_endpoint,
            program=train_program if args.do_train else test_prog,
            startup_program=startup_prog)
        nccl2_num_trainers = trainers_num
        nccl2_trainer_id = trainer_id
请问怎么在这段代码里吧train_id变成变量？

**Comment by sunbrother99** [comment]
PADDLE_TRAINER_ID这个环境变量可以是一个列表吗

**Comment by Meiyim** [comment]
PADDLE_TRAINER_ID会在 `finetune_launch.py`里自动设置，只需要将修改`—node_id`这个参数修改成对应的机器id即可

**Comment by sunbrother99** [comment]
请问怎么把--node_id这个参数设置成变量？脚本运行起来就改不了

**Comment by Meiyim** [comment]
node_id可以通过查询本机ip在`--node_ips`中的索引位置来获得，`--node_ips`是一个逗号分隔的列表，里面存放参与多机运算的所有机器的ip，需要您提前设置好。所有参与运算的机器`--node_ips`的值应该是一样的。
举个例子，有两台机器参与多机运算，其ip分别为：1.1.1.1， 1.1.1.2
则在第一台机器上`finetune_launch.py`应指定如下参数：
```script
python ./finetune_launch.py  \
    --nproc_per_node 8 \
    --selected_gpus 0,1,2,3,4,5,6,7 \
    --node_ips 1.1.1.1,1.1.1.2 \
    --node_id 0 \
    --current_node_ip 1.1.1.1
    ...
```
在另一台机器上：
```script
python ./finetune_launch.py  \
    --nproc_per_node 8 \
    --selected_gpus 0,1,2,3,4,5,6,7 \
    --node_ips 1.1.1.1,1.1.1.2 \
    --node_id 1 \
    --current_node_ip 1.1.1.2
    ...
```
其中`--node_id`的值可以通过这样一段python程序算出来：
```python
node_id = node_ips.index(current_node_ip)
```

**Comment by sunbrother99** [comment]
这个意思是不是再每个机器上都需要执行Python脚本，而不能在一台主节点上直接执行一个脚本完事。
或者说，paddlepaddl的分布式没有主节点，子节点之分，每个机器都是主节点？

**Comment by sunbrother99** [comment]
我的问题解决了，出现我提问的情况是因为集群的617系列端口没有开。。。。

**Comment by Meiyim** [comment]
在每个机器上都需要启动训练脚本。一般来来说可以通过集群调度来做到这一点，例如mpirun
