### ISSUE TITLE
请问是否有在新数据上继续fineturn的接口

### ISSUE THREAD

**Issue by woyijkl1** [PaddlePaddle/ERNIE#331]
就像word2vec一样，加载预训练模型后，在小数据集上继续fineturning

**Comment by oyxuan-11** [comment]
你可以参考这个链接里面的fine-tuning 教程：https://github.com/PaddlePaddle/ERNIE#fine-tuning
你可以把小数据的格式调整为fine-tuning 对应任务的格式，然后加载ERNIE 预训练模型做fine-tuning
