### ISSUE TITLE
InferenceClient的请求参数，可以提供一个demo吗？

### ISSUE THREAD

**Issue by xiaonian0430** [PaddlePaddle/ERNIE#336]
from propeller.service.client import InferenceClient
client = InferenceClient('tcp://localhost:8113')
result = client(sentence_id, position_id, token_type_id, input_mask)

**Comment by Meiyim** [comment]
client的请求参数取决于`save_inference_model`时,指定的网络输入。您截的例子对应的是用`predict_classifier.py`进行`save_inference_model`，该脚本指定了4个输入参数。所以可以采用如下4个**numpy_array** 来调用client:

例子：
原文：“今天很热/ 今天是夏天”

sentence_id:  [[2, 23, 12, 24, 10, 5, 23, 12, 29, 49, 19, 5]]
position_id: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]
token_type_id: [[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]
input_mask: [[ 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1. ]]

另外，在ERNIE的finetune代码里也能找到使用`InferenceClient`的例子：https://github.com/PaddlePaddle/ERNIE/blob/30b892e3c029bff706337f269e6c158b0a223f60/distill/distill_chnsentocorp_with_propeller_server.py#L187
这个例子是采用`propeller`来完成`save_inference_model`的，所以只指定了两个输入，分别是上面的`sentence_id` 和`token_type_id`

**Comment by xiaonian0430** [comment]
可以提供命名实体识别的上线demo?
1）生成inference_model  demo
2）在线预测demo

**Comment by xiaonian0430** [comment]
> client的请求参数取决于`save_inference_model`时,指定的网络输入。您截的例子对应的是用`predict_classifier.py`进行`save_inference_model`，该脚本指定了4个输入参数。所以可以采用如下4个**numpy_array** 来调用client:
> 
> 例子：
> 原文：“今天很热/ 今天是夏天”
> 
> sentence_id: [[2, 23, 12, 24, 10, 5, 23, 12, 29, 49, 19, 5]]
> position_id: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]
> token_type_id: [[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]
> input_mask: [[ 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1. ]]
> 
> 另外，在ERNIE的finetune代码里也能找到使用`InferenceClient`的例子：
> 
> https://github.com/PaddlePaddle/ERNIE/blob/30b892e3c029bff706337f269e6c158b0a223f60/distill/distill_chnsentocorp_with_propeller_server.py#L187
> 
> 
> 这个例子是采用`propeller`来完成`save_inference_model`的，所以只指定了两个输入，分别是上面的`sentence_id` 和`token_type_id`

可以提供命名实体识别的上线demo?
1）生成inference_model demo
2）在线预测demo
