### ISSUE TITLE
如何利用 Fine-tuning 得到的模型对短文本进行命名实体识别？

### ISSUE THREAD

**Issue by xiaonian0430** [PaddlePaddle/ERNIE#338]
需要能够InferenceClient客户端，方便做成服务，用于线上预测

**Comment by WeiyueSu** [comment]
保存成infererce_model后，可以使用propeller一键部署成server，参考https://github.com/PaddlePaddle/ERNIE/blob/develop/propeller_xnli_demo.ipynb
