### ISSUE TITLE
will support tensorflow in the future?

### ISSUE THREAD

**Issue by linzaihui** [PaddlePaddle/ERNIE#340]
I've red the readme.md and found that ERNIE is just a micro-innovation based on BERT, but BERT is really a innovation. Learning text with priori knowledge is quite like what we humans do. For consideration of maintainence, we'd like to do the same improvement on BERT based on tensorflow instead of doing something on another platform. You know, information, like document, help, etc. for PaddlePaddle is not enough, except building a much larger echo in the feature to build the confidence of developers of AI.

**Comment by WeiyueSu** [comment]
No plan for tf now. Newer version of Paddlepaddle(v1.6) will release in Nov, with better api, doc, etc.
