### ISSUE TITLE
InferenceClient SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/ERNIE#341]
from propeller.service.client import InferenceClient
  File "propeller/service/client.py", line 77
    async def get(coroutine_idx=0, num_coroutine=1):
            ^
SyntaxError: invalid syntax

python2.7.16
在用propeller包服务 然后各种报错啊

**Comment by Meiyim** [comment]
目前InferenceServer的server端和client端都仅能在python3.5+上使用。
另外python2.7将会在19年末被抛弃。后续的项目维护主要以python3为主。

**Comment by janelu9** [comment]
> 目前InferenceServer的server端和client端都仅能在python3.5+上使用。
> 另外python2.7将会在19年末被抛弃。后续的项目维护主要以python3为主。

但是 ernie 不只支持python2.7吗

**Comment by Meiyim** [comment]
目前的ERNIE 同时支持Python2/3
