### ISSUE TITLE
sentence pair分类任务改成四分类

### ISSUE THREAD

**Issue by zhengyima** [PaddlePaddle/ERNIE#342]
除了将sh脚本中的num_labels改为4，还需要改什么吗？

跑的结果比BERT差很多，怀疑有问题
我的label为0,1,2,3。

**Comment by tianxin1860** [comment]
> 除了将sh脚本中的num_labels改为4，还需要改什么吗？
> 
> 跑的结果比BERT差很多，怀疑有问题
> 我的label为0,1,2,3。

如果做4分类的话，只需要将 num_label 改成4，同时将训练数据、测试数据集替换为自己的业务数据；其余参数 learning_rate、batch_size、weight_decay 的调整都会对效果有影响，需要自己调优;
