### ISSUE TITLE
微调时不能稳定地梯度下降是什么原因呢

### ISSUE THREAD

**Issue by ciwenjia** [PaddlePaddle/ERNIE#344]
![image](https://user-images.githubusercontent.com/37259833/67091309-e2b42000-f1de-11e9-937c-edb1aa726f9b.png)
![image](https://user-images.githubusercontent.com/37259833/67091375-0b3c1a00-f1df-11e9-97a5-04040245135b.png)

**Comment by tianxin1860** [comment]
1.  可能是训练数据中有脏数据
2.  可以尝试调小学习率
