### ISSUE TITLE
请问哪里可以下载ernie 2.0中文的预训练模型？

### ISSUE THREAD

**Issue by CChengz** [PaddlePaddle/ERNIE#346]

**Comment by XIAOLINSHINE** [comment]
为了让大家更方便、快捷、高效的使用ERNIE，我们正在做易用性更强的ERNIE平台化服务工作，届时会与ERNIE2.0模型同步开放给大家，届时欢迎大家使用。
您可以进入ERNIE官方交流QQ群：760439550，最新消息都会在群内同步给大家。

**Comment by shishishu** [comment]
> 为了让大家更方便、快捷、高效的使用ERNIE，我们正在做易用性更强的ERNIE平台化服务工作，届时会与ERNIE2.0模型同步开放给大家，届时欢迎大家使用。
> 您可以进入ERNIE官方交流QQ群：760439550，最新消息都会在群内同步给大家。

Any updates?

**Comment by mbabby** [comment]
> 为了让大家更方便、快捷、高效的使用ERNIE，我们正在做易用性更强的ERNIE平台化服务工作，届时会与ERNIE2.0模型同步开放给大家，届时欢迎大家使用。
> 您可以进入ERNIE官方交流QQ群：760439550，最新消息都会在群内同步给大家。

有个大概的时间吗？

**Comment by Meiyim** [comment]
请移步[EasyDL专业版](https://ai.baidu.com/easydl/pro)，可以直接使用ERNIE-2.0 进行finetune
