### ISSUE TITLE
propeller server RuntimeError: Cant run the envent loop

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/ERNIE#348]
环境paddle-1.5.2.post97 cuda9 python3.6
存储模型是用的
save_inferrence_model(path,exe,[srd,type,pos,mask],[prob],train_program)
用目录下的prospeller起服务的后，推断时出现了如下错误，不知是何故：
![微信图片_20191022153301](https://user-images.githubusercontent.com/24219258/67265868-5dcc4d80-f4e1-11e9-899a-c017e30f81a2.jpg)

**Comment by Meiyim** [comment]
我能复现这个问题，有点奇怪。如果把client端jupyter notebook代码抄到一个python文件中并执行便没有问题。。

**Comment by janelu9** [comment]
@Meiyim 那可能是jupyter也起了loop.  此外，我想服务的功能是 直接输入句子 输出json 然后中间过程是数据处理>ernie>sklearn>结果 这样的话是否外面还要用python再包一层

**Comment by Meiyim** [comment]
sklearn的逻辑如果放在客户端做的话，直接继承`InferenceClient`(`ernie/service/client.py`)，改写`__call__`方法就可以了。
