### ISSUE TITLE
批量预测和单条数据预测结果差别很大

### ISSUE THREAD

**Issue by semal** [PaddlePaddle/ERNIE#351]
使用 ERNIE 1.0 进行命名实体预测，批量预测的结果和单条数据预测的结果差别很大，是不是因为 padding 的时候带来的 0 填充导致的？有没有办法解决或优化？

**Comment by dingsiyu** [comment]
1、padding一般不会影响结果，input_mask会把padding的部分掩盖掉。
2、批量预测的结果和单条数据预测 --- 我是不是可以理解为batch_size=1和batch_size>1时的结果差异比较大？
3、有具体的log打印信息吗？或者能提供一个最小可复现单元吗

**Comment by semal** [comment]
> 1、padding一般不会影响结果，input_mask会把padding的部分掩盖掉。
> 2、批量预测的结果和单条数据预测 --- 我是不是可以理解为batch_size=1和batch_size>1时的结果差异比较大？
> 3、有具体的log打印信息吗？或者能提供一个最小可复现单元吗

可以理解为2，预测时输入数据的长度是单条字符串的长度，批量时长度都会扩展到最长字符串的长度，ERNIE 默认的日志没有相关的输出，我可以提供一下接口返回的结果对比：
![image](https://user-images.githubusercontent.com/5009351/68000230-383a0380-fc9a-11e9-8812-e52168583174.png)
![image](https://user-images.githubusercontent.com/5009351/68000237-44be5c00-fc9a-11e9-8342-03119d0ebea4.png)
这是一个分类任务模型推理的结果，可以看到 embedding 发生的微小的变化..

**Comment by Meiyim** [comment]
这可能是一个潜在的问题，请问是使用哪个工具预测的打分结果？
是命名实体识别任务还是分类任务有此问题，或者说都有此问题？
另外您使用的是哪一个版本的paddle？

**Comment by semal** [comment]
> 这可能是一个潜在的问题，请问是使用哪个工具预测的打分结果？
> 是命名实体识别任务还是分类任务有此问题，或者说都有此问题？
> 另外您使用的是哪一个版本的paddle？

我使用的 load_inference_model 函数和 GPU executor。两个任务都有此问题，另外我使用的是 1.5.1 版本的 paddlepaddle。

**Comment by Meiyim** [comment]
如果是自己调用的paddle API。可以再检查下：是否同一条输入每次预测都会有偏差；还是不同的padding方式导致预测结果有偏差。
另外可以的话再贴一下复现代码。

**Comment by semal** [comment]
> 如果是自己调用的paddle API。可以再检查下：是否同一条输入每次预测都会有偏差；还是不同的padding方式导致预测结果有偏差。
> 另外可以的话再贴一下复现代码。

同样的输入每一次预测都是相同的结果，只有批量和单条的区别。

**Comment by semal** [comment]
> 如果是自己调用的paddle API。可以再检查下：是否同一条输入每次预测都会有偏差；还是不同的padding方式导致预测结果有偏差。
> 另外可以的话再贴一下复现代码。

找到原因了，原来是 input_mask 生成的代码有问题..
