### ISSUE TITLE
预测时出现addle.fluid.core_avx.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/ERNIE#355]
在单卡单机上出现问题，无法运行
paddle.fluid.core_avx.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: unknown error at [/paddle/paddle/fluid/platform/gpu_info.cc:97]

详细错误信息
  File "/home/work/src/event_relation_mt_models.py", line 39, in <module>
    max_seq_len=max_seq_len, batch_size=batch_size)
  File "/home/work/paddle_gpu_env/python/lib/python2.7/site-packages/baidu/kgx/models/mt_ernie_classifier.py", line 89, in __init__
    self.__start_model()
  File "/home/work/paddle_gpu_env/python/lib/python2.7/site-packages/baidu/kgx/models/mt_ernie_classifier.py", line 93, in __start_model
    dev_list = fluid.cuda_places()
  File "/home/work/paddle_gpu_env/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 136, in cuda_places
    device_ids = _cuda_ids()
  File "/home/work/paddle_gpu_env/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 101, in _cuda_ids
    device_ids = six.moves.range(core.get_cuda_device_count())
paddle.fluid.core_avx.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: unknown error at [/paddle/paddle/fluid/platform/gpu_info.cc:97]
PaddlePaddle Call Stacks:
0       0x7f71aba8de10p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f71aba8e189p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f71adbf70bcp paddle::platform::GetCUDADeviceCount() + 1036
3       0x7f71aba89abap
4       0x7f71abac0d36p
5       0x7f72fa472989p PyEval_EvalFrameEx + 28553
6       0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
7       0x7f72fa472345p PyEval_EvalFrameEx + 26949
8       0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
9       0x7f72fa472345p PyEval_EvalFrameEx + 26949
10      0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
11      0x7f72fa472345p PyEval_EvalFrameEx + 26949
12      0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
13      0x7f72fa3ebf85p
14      0x7f72fa3b9df3p PyObject_Call + 67
15      0x7f72fa3c89cdp
16      0x7f72fa3b9df3p PyObject_Call + 67
17      0x7f72fa427bafp
18      0x7f72fa42446fp
19      0x7f72fa3b9df3p PyObject_Call + 67
20      0x7f72fa46f4a6p PyEval_EvalFrameEx + 15014
21      0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
22      0x7f72fa4751f2p PyEval_EvalCode + 50
23      0x7f72fa489e7cp PyImport_ExecCodeModuleEx + 140
24      0x7f72fa48a1dep
25      0x7f72fa48b0d9p
26      0x7f72fa48bd37p PyImport_ImportModuleLevel + 471
27      0x7f72fa4699ffp
28      0x7f72fa3b9df3p PyObject_Call + 67
29      0x7f72fa46b417p PyEval_CallObjectWithKeywords + 71
30      0x7f72fa46f8c7p PyEval_EvalFrameEx + 16071
31      0x7f72fa4750bdp PyEval_EvalCodeEx + 2061
32      0x7f72fa4751f2p PyEval_EvalCode + 50
33      0x7f72fa49df42p PyRun_FileExFlags + 146
34      0x7f72fa49f2d9p PyRun_SimpleFileExFlags + 217
35      0x7f72fa4b500dp Py_Main + 3149
36      0x7f72f96b2bd5p __libc_start_main + 245
37            0x4007a1p

gpu信息
![image](https://user-images.githubusercontent.com/6512760/67680180-b01bdb80-f9c5-11e9-87ac-c9bd5822d6f9.png)

**Comment by Meiyim** [comment]
看起来像是cuda版本的问题，
可否进入你的python，然后贴一下运行下面这些命令的输出：
```python
import paddle; print(paddle.__version__)
import paddle.fluid as f; f.install_check.run_check()
```

**Comment by littlepan0413** [comment]
运行结果如下
![image](https://user-images.githubusercontent.com/6512760/67730021-7d59fd80-fa2e-11e9-978d-3cbf0567c703.png)


> 看起来像是cuda版本的问题，
> 可否进入你的python，然后贴一下运行下面这些命令的输出：
> 
> ```python
> import paddle; print(paddle.__version__)
> import paddle.fluid as f; f.install_check.run_check()
> ```

**Comment by Meiyim** [comment]
如果你是在一台GPU机器上运行，
首先确认你的cuda安装无误(需要使用于PaddlePaddle相对应的cuda版本，建议为cuda9)。
然后确认cudnn，cuda动态库在你的LD_LIBRARY_PATH中。比如可以这样设置你的环境变量：
```scipt
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64/:/usr/local/cudnn/cudnn_v7.6.30_cuda9/lib64
```

你可以尝试修复你的环境直到以下python能够成功运行：
```python
import paddle.fluid as f; f.install_check.run_check()
```

**Comment by liupluswei** [comment]
跟用户线下沟通了，升级之后可以看到调用cudaGetDeviceCount 返回错误值30，官网文档显示是unknown error。 对比其他机器之后发现属于机器环境问题，重启机器就好了，StackOverflow上的类似问题：https://stackoverflow.com/questions/25755471/cudagetdevicecount-returned-errorunknown-code-30
