### ISSUE TITLE
小数据集预训练的时候，next_sentence_label 什么时候设置成0

### ISSUE THREAD

**Issue by woyijkl1** [PaddlePaddle/ERNIE#356]
如题

**Comment by Meiyim** [comment]
根据BERT NSP-loss的定义，
当输入数据中的句子为上下文关系时(也就是说来自同一片doc的连续片段）， next_sentence_label设置为0；反之，当输入句子分别来自两篇无关文档时， 则该label设置为1.
实际上0和1的取值可以返过来，并不影响模型训练。

**Comment by ghost** [comment]
> 根据BERT NSP-loss的定义，
> 当输入数据中的句子为上下文关系时(也就是说来自同一片doc的连续片段）， next_sentence_label设置为0；反之，当输入句子分别来自两篇无关文档时， 则该label设置为1.
> 实际上0和1的取值可以返过来，并不影响模型训练。

我看实例数据里边怎么还有的label是2 ？？？
