### ISSUE TITLE
使用python -m propeller.tools.start_server，报错。

### ISSUE THREAD

**Issue by austinkk** [PaddlePaddle/ERNIE#358]
用propeller.tools.start_server启动好ernie模型，调用萃取模型脚本，报错 

> Exception: /paddle/paddle/fluid/operators/lookup_table_op.cu:43 Assertion `id < N` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 18000, but got 1073741824. Please check input value.

看了下我的 input
[[   1   96  128 1603  204   62 1114    2  706  809 1172  226  128 1528
  3976  208  249 2310   18   21   96  289   65  369   52   96  128 1528
  3976  208  249    8  128 1528 1603  953  100  128  361    2]] [[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1]]
并没发现任何问题。求解答。

**Comment by jerrywgz** [comment]
从报错信息来看是lookup_table的输入id越界了，是不是input跟embedding数量没对上啊？导致生成了默认值 1073741824这个数值看着像是未初始化的数

可以在embeding前面使用 layers.Print(layers.reduce_max(input))看下最大的id是多少

**Comment by austinkk** [comment]
> 从报错信息来看是lookup_table的输入id越界了，是不是input跟embedding数量没对上啊？导致生成了默认值 1073741824这个数值看着像是未初始化的数
```python         
            new_pts = [serv_utils.slot_to_numpy(s) for s in slots.slots]
            for i in new_pts:
                log.debug(i)
            pts = [serv_utils.slot_to_paddlearray(s) for s in slots.slots]
            for i in pts:
                log.debug(i.as_ndarray())
            ret = predictor(pts)
```
我在propeller/service/server.py打了log，发现我用utils把slots转换成np.array没有问题。
[[[    1]  [   96]   [  256]   [  701] ...]] 数据是这样的
但是我用serv_utils.slot_to_paddlearray转成paddletensor后，用tensor.as_ndarray()看了下,就变成[[[4809844403097042944]   [4913216088361140224]   [4978518282980089856]]]这样了

**Comment by Meiyim** [comment]
首先考虑下paddle的版本，是否是我们目前支持的版本。
目前我们在paddle 1.5.1 和 1.5.2上进行过测试。
另外，请检查你提供的ndarray的dtype，确认下是否输入为np.int64，而非np.int32。

**Comment by austinkk** [comment]
> 首先考虑下paddle的版本，是否是我们目前支持的版本。
> 目前我们在paddle 1.5.1 和 1.5.2上进行过测试。
> 另外，请检查你提供的ndarray的dtype，确认下是否输入为np.int64，而非np.int32。

dtype是没问题的，我版本用的是1.6.0，所以这样看是版本问题= =

**Comment by Meiyim** [comment]
1.6.0测试目前还在进行中，所以目前定位到是`serv_utils.slot_to_paddlearray`这一步有非预期行为。我们会重点看下这块的兼容性。
