### ISSUE TITLE
做lcqmc数据集什么样的参数最好啊，batch_size,epoch,lr等？

### ISSUE THREAD

**Issue by wxlduter** [PaddlePaddle/ERNIE#359]
为什么我有时32好有时64好

**Comment by Meiyim** [comment]
各个任务的推荐配置你可以从这一节里找到：
https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#%E8%BF%90%E8%A1%8C%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE

finetune任务因为具有较大的波动性。所以建议你每组配置跑5遍，取一个平均指标来评估哪一组finetune参数更好。
