### ISSUE TITLE
ernie是基于字训练还是基于词训练的啊

### ISSUE THREAD

**Issue by wxlduter** [PaddlePaddle/ERNIE#361]

**Comment by PROoshio** [comment]
中文是基于词的

**Comment by Meiyim** [comment]
开源的ERNIE1.0中文模型，输入粒度中文单字。

**Comment by wq343580510** [comment]
基于字训练，但是预训练的时候是mask词级别或者短语级别的连续字符片段

**Comment by jfkey** [comment]
> 基于字训练，但是预训练的时候是mask词级别或者短语级别的连续字符片段

这些都是在处理数据格式阶段（预处理）完成的是么？
