### ISSUE TITLE
where can we find ERNIE tiny?

### ISSUE THREAD

**Issue by brightmart** [PaddlePaddle/ERNIE#364]
ERNIE_TINY什么时候开源？还找不到呢。
ernie_tiny的报道https://cloud.tencent.com/developer/news/468388

**Comment by kirayummy** [comment]
ERNIE Tiny本周进行了发布，预计下周会开源出来，欢迎使用：）

**Comment by kirayummy** [comment]
> ERNIE_TINY什么时候开源？还找不到呢。
> ernie_tiny的报道https://cloud.tencent.com/developer/news/468388

https://ernie.bj.bcebos.com/ernie_tiny.tar.gz

**Comment by yguo33** [comment]
请问ERNIE_TINY的源码有没有开源

**Comment by Meiyim** [comment]
https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#tune-ernie-tiny

**Comment by mikezhang95** [comment]
你好，请问 静态图版本的ernie tiny的代码开源了吗
