### ISSUE TITLE
server not ready; not ready endpoints

### ISSUE THREAD

**Issue by Heavenlinguistics** [PaddlePaddle/ERNIE#368]
错误：
![image](https://user-images.githubusercontent.com/27318679/69021578-435b9600-09f3-11ea-951c-a4be72bb0018.png)
跑的是run_drcd.sh 脚本:  
![image](https://user-images.githubusercontent.com/27318679/69021825-1a87d080-09f4-11ea-9594-4f838388c794.png)
用4个gpu分了4个进程去跑，其中第一个进程的log总是报"server not ready, wait 3 sec to retry" "not ready endpoints"的错误。  
其他可能的相关信息：  
1.第3个进程的json文件写入出现了“ raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"的错误。估计是写入的数据为空。  
2. ernie 版本: ERNIE 1.0 Base for Chinese with params config and vocabs  
3. 操作系统版本：Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-58-generic x86_64)  
4. cuda版本：cuda9.0

**Comment by oyjxer** [comment]
检查一下json文件是否可以正常读入，"server not ready, wait 3 sec to retry"是由于某进程没有正常启动，导致的等待

**Comment by Meiyim** [comment]
使用`finetune_launch.py`进行多卡启动时，各个进程的log都会重定向到`log/job.log.x`里，可以根据错误信息再排查一下

**Comment by Heavenlinguistics** [comment]
> 使用`finetune_launch.py`进行多卡启动时，各个进程的log都会重定向到`log/job.log.x`里，可以根据错误信息再排查一下



> 检查一下json文件是否可以正常读入，"server not ready, wait 3 sec to retry"是由于某进程没有正常启动，导致的等待
json文件没有办法正常读入。怎样才能保证进程正常启动呢？是要打开服务器上的endpoints吗？因为它一直报not ready endpoints...

**Comment by Heavenlinguistics** [comment]
> 检查一下json文件是否可以正常读入，"server not ready, wait 3 sec to retry"是由于某进程没有正常启动，导致的等待
@oyjxer json文件没有办法正常读入。怎样才能保证进程正常启动呢？是要打开服务器上的endpoints吗？因为它一直报not ready endpoints...

**Comment by oyjxer** [comment]
先确认一下是什么json文件不能正常读入

**Comment by lllulll** [comment]
用free命令查一下，发现交换内存几乎已经用完。因此用docker stop [容器名]，在用docker restart [容器名]，交换内存就空出来了。不过训练一段时间后，又会出现相同的问题。重新这样做就好了。。我遇见的是这样的问题。 希望对你有用
