### ISSUE TITLE
训练完成之后报"无法分配内存(cannot malloc memory)"

### ISSUE THREAD

**Issue by Heavenlinguistics** [PaddlePaddle/ERNIE#370]
训练完成之后报了无法分配内存的错误：
![image](https://user-images.githubusercontent.com/27318679/69300526-633ac600-0c4e-11ea-9b6f-949df0855b21.png)
由下图可知训练已经完成:  
![image](https://user-images.githubusercontent.com/27318679/69300230-8749d780-0c4d-11ea-9833-7d1002e9dde1.png)
只训练了两个epoch,且上面的log已经显示输出了最后的验证结果和测试结果。且查看checkpoints文件夹也输出了训练到最后一个step的checkpoint。  
所以为什么已经成功训练完了还会报出无法分配内存的错误呢？这样的错误是否会影响已经保存的checkpoint的效果呢？

**Comment by oyjxer** [comment]
是否有其他任务占用gpu，问题可以稳定复现吗？

**Comment by Heavenlinguistics** [comment]
@oyjxer 没有其他任务。用最后生成的checkpoint在测试集和验证集上跑，得到的f1和em都不错。但就是不知道为什么训练完成了以后还报这样的错误。。。

**Comment by oyjxer** [comment]
提供一下日志吧，另外是否有代码改动
