### ISSUE TITLE
README中的时间延迟是否写反了？

### ISSUE THREAD

**Issue by buildcharger** [PaddlePaddle/ERNIE#373]
如下图：
![image](https://user-images.githubusercontent.com/12854979/69503880-31c93f80-0f59-11ea-9bf7-1939ca17007a.png)
ERNIE-tiny和ERNIE2.0的延迟似乎写反了

**Comment by Meiyim** [comment]
感谢建议，此处系笔误。

**Comment by Meiyim** [comment]
fixed in #374
