### ISSUE TITLE
requirement.txt sklearn==0.0 安装失败

### ISSUE THREAD

**Issue by semal** [PaddlePaddle/ERNIE#376]
![image](https://user-images.githubusercontent.com/5009351/69720502-b54b8200-114d-11ea-81fa-07921caa4389.png)
安装这个包的时候报错：
Could not install packages due to an EnvironmentError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))

**Comment by MrPig** [comment]
还有其他错误日志么？如果有的话可以贴出来看一下。如果仅仅是sklearn那行报错的话，可以尝试把那行删掉，然后自己安装一个sklearn
