### ISSUE TITLE
希望能增加不同 pooling 的策略

### ISSUE THREAD

**Issue by semal** [PaddlePaddle/ERNIE#377]
![image](https://user-images.githubusercontent.com/5009351/69729385-2ba5af80-1161-11ea-820a-0d702b131549.png)
参考 bert-as-service，希望向量服务器增加不同的 pooling 策略..

**Comment by MrPig** [comment]
目前ERNIE的向量服务器可以取出每一层的所有输出，可以针对自己的需求做一些pooling。
