### ISSUE TITLE
8卡速度和单卡一样

### ISSUE THREAD

**Issue by xiaoxuesheng1234** [PaddlePaddle/ERNIE#378]
The number of CUDAPlace, which is used in ParallelExecutor, is 8. And the Program will be copied 8 copies。
我看8个显卡都占满了，但速度和单卡一样，求大神帮忙解决一下。

**Comment by xiaoxuesheng1234** [comment]
补充一下，用的是ernie_tiny

**Comment by Lizhengo** [comment]
麻烦看下显存占用情况

**Comment by xiaoxuesheng1234** [comment]
![5ACEA2B436261229B6932F985017BFC4](https://user-images.githubusercontent.com/33617075/69942561-99662880-151f-11ea-9a36-d18e182542d2.jpg)

**Comment by Lizhengo** [comment]
您是怎么判断速度一样的？是训练一轮的时候没有变短吗？

**Comment by Lizhengo** [comment]
您是怎么判断速度一样的？是训练一轮的时间没有变短吗？

**Comment by xiaoxuesheng1234** [comment]
steps/sec: 2.06705  根据这个。在单卡，双卡，4卡，8卡这几种情况下，这个值都是一样的。

**Comment by xiaoxuesheng1234** [comment]
![image](https://user-images.githubusercontent.com/33617075/69945104-d6341e80-1523-11ea-9771-6b4cad453e7d.png)

**Comment by Lizhengo** [comment]
麻烦你再看下训练一轮的时间

**Comment by Meiyim** [comment]
在同步数据并行的设置下，每个step意味着参与训练的每一张卡都进行了一次forwad/backword. 虽然多卡下steps/sec没有变化。但是实际上同时间内相比单卡训练，模型多见过了了“卡数”倍的样本。

若在多卡训练中没有根据数据量 相应地调节 max_steps的话，则相比单卡会多训练"卡数"个epoch。

**Comment by xiaoxuesheng1234** [comment]
@Meiyim  所以单卡和8卡在相同的max_steps下，8卡训练的epoch会是单卡的8倍是吗？

**Comment by xiaoxuesheng1234** [comment]
@Meiyim 如果把steps/sec理解为每张卡的速度那我就明白了，另外’同步数据并行‘，这个需要额外设置吗？我直接调用的./example/finetune_classifier.py脚本。辛苦啦~

**Comment by Meiyim** [comment]
> 单卡和8卡在相同的max_steps下，8卡训练的epoch会是单卡的8倍

是的

**Comment by xiaoxuesheng1234** [comment]
@Meiyim 那我就明白了，谢谢您。另外‘同步数据并行’需要额外设置吗？我直接调用的./example/finetune_classifier.py脚本。

**Comment by xiaoxuesheng1234** [comment]
> 麻烦你再看下训练一轮的时间

@Lizhengo 也谢谢你~麻烦了~

**Comment by xiaoxuesheng1234** [comment]
> 麻烦你再看下训练一轮的时间

@Lizhengo  也谢谢你啦，麻烦了~

**Comment by Meiyim** [comment]
> 另外‘同步数据并行’需要额外设置吗？

这个是目前仅支持的模式，不需要其他设置。

**Comment by xiaoxuesheng1234** [comment]
> > 另外‘同步数据并行’需要额外设置吗？
> 
> 这个是目前仅支持的模式，不需要其他设置。

嗯嗯，再次感谢！
