### ISSUE TITLE
ERNIE/ernie/utils/args.py 里边的prepare_log方法里os.path.exists少加了一个s

### ISSUE THREAD

**Issue by Dilyar93** [PaddlePaddle/ERNIE#379]
![image](https://user-images.githubusercontent.com/17738610/70208376-5ea30100-1768-11ea-9518-88fa731b27b8.png)

ERNIE/ernie/utils/args.py 里边的prepare_log方法里os.path.exists少加了一个s，会报错

**Comment by Lizhengo** [comment]
感谢您的反馈，我们尽快修复

**Comment by Meiyim** [comment]
fixed in #381
