### ISSUE TITLE
Error in using the CPU version of paddlepaddle-1.5.2

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/ERNIE#380]
My environment is Python3.6 and paddlepaddle-1.5.2(cpu version) 
I download the model of "ERNIE 1.0 Base for Chinese(max-len-512)"
I run the example of lcqmc task and I got a Exception :

"I1205 17:34:24.159621 28051 parallel_executor.cc:334] The number of CPUPlace, which is used in ParallelExecutor, is 32. And the Program will be copied 32 copies
I1205 17:34:59.254444 28051 build_strategy.cc:340] SeqOnlyAllReduceOps:0, num_trainers:1
Traceback (most recent call last):
  File "./ernie/run_classifier.py", line 447, in <module>
    main(args)
  File "./ernie/run_classifier.py", line 257, in main
    train_exe.run(fetch_list=[])
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 672, in run
    return_numpy=return_numpy)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 534, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator softmax_with_cross_entropy error.
Python Call stacks: 
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1774, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6425, in softmax_with_cross_entropy
    'axis': axis
  File "~/ERNIE/ernie/finetune/classifier.py", line 111, in create_model
    logits=logits, label=labels, return_softmax=True)
  File "./ernie/run_classifier.py", line 119, in main
    is_regression=args.is_regression)
  File "./ernie/run_classifier.py", line 447, in <module>
    main(args)
C++ Call stacks: 
 at [/paddle/paddle/fluid/operators/math/cross_entropy.cc:56]
PaddlePaddle Call Stacks: 
0       0x7f91ea0b3270p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f91ea0b35e9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f91eb110473p paddle::operators::math::CrossEntropyFunctor<paddle::platform::CPUDeviceContext, float>::operator()(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, bool, int, int) + 739
3       0x7f91ea4861cep paddle::operators::SoftmaxWithCrossEntropyKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 1566
4       0x7f91ea486413p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SoftmaxWithCrossEntropyKernel<float>, paddle::operators::SoftmaxWithCrossEntropyKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f91eb410ae7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
6       0x7f91eb411251p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f91eb40c1f4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 260
8       0x7f91eb1fcf13p
9       0x7f91eb1fcbacp paddle::framework::details::ComputationOpHandle::RunImpl() + 124
10      0x7f91eb1eec4cp paddle::framework::details::OpHandleBase::Run(bool) + 28
11      0x7f91eb1d31a6p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
12      0x7f91eb1d1f0fp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
13      0x7f91eb1d22cfp
14      0x7f91ea2c6353p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
15      0x7f91ea1738a7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
16        0x318b20cb23p pthread_once + 83
17      0x7f91eb1cdb72p
18      0x7f91ea174e64p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
19      0x7f91f692a6e0p
20        0x318b207851p
21        0x318aee767dp clone + 109

terminate called without an active exception"

**Comment by jamjarred** [comment]
Did you find a fix for this?
