### ISSUE TITLE
ernie代码在处理batch数据时是否存在bug？

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/ERNIE#382]
https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/reader/task_reader.py
![image](https://user-images.githubusercontent.com/6512760/70375752-b98d5180-193c-11ea-8049-f26f95ca10d3.png)
这里如果dev_count > 1，最后循环结束 all_dev_batches内数据长度小于dev_count就不会处理了？造成数据丢失？

**Comment by Meiyim** [comment]
多卡训练的时候，训练数据里最后一批样本若出现 "样本数<卡数"的情况时，会舍弃这一批样本。因为没有充足的样本以供多卡训练。一般来说认为这样的是不会影响训练结果的。

或者您可以尝试使用`propeller`来完成训练过程，在`propeller.Dataset`的`padded_batch`中由于数据流事先被repeat了无穷遍，所以不会出现舍弃最后一批样本的情况。

使用`propeller`进行finetune可以参考：https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#%E5%88%A9%E7%94%A8propeller%E8%BF%9B%E8%A1%8C%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91
