### ISSUE TITLE
加载finetune好的ernie发现很多权重加载不了（保存的模型中也没有对应权重）

### ISSUE THREAD

**Issue by bit-pku-zdf** [PaddlePaddle/ERNIE#383]
问题：使用ernie进行finetune，下载的模型是
这样，finetune之后保存的模型少了很多变量，
原来的fc.c_0没有了，只有带beta 和moment的，请问这个是什么原因呢？
环境：在孔明集群训练
log:http://yq01-sys-hic-p40-0060.yq01.baidu.com:8388/v1/slurmjobs/155440/workspace

**Comment by dingsiyu** [comment]
能把finetuning保存模型的变量生成log发上来吗？ernie在finetuning之后，除了预训练任务相关的参数，其他的是不会少的
