### ISSUE TITLE
请问设置use_multi_gpu_test=true的情况为什么预测时还是仅使用了一张卡？

### ISSUE THREAD

**Issue by QianShengWu** [PaddlePaddle/ERNIE#384]

**Comment by jiweibo** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/26377421/70620491-670ca780-1c52-11ea-84f6-a645206cc30e.png">

看上去两个分支都是走的单卡，辛苦负责人修一下

**Comment by Meiyim** [comment]
实际上多卡预测是一个未完成的功能，目前这个功能没有积极维护。一个核心问题是当样本数<卡数的时候，怎么分配。
为了解决这个问题，我们干脆实现了一个自动分发的多卡server，请参考：
1. https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#%E5%90%91%E9%87%8F%E6%9C%8D%E5%8A%A1%E5%99%A8
2. https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#%E5%9C%A8%E7%BA%BF%E9%A2%84%E6%B5%8B
