### ISSUE TITLE
同一条输入每次预测结果不同

### ISSUE THREAD

**Issue by hweidream** [PaddlePaddle/ERNIE#388]
用ERNIE做序列标注任务，模型部分代码用的是1.0的，每次输入相同时，ret_infers给出不同的结果，概率也不一样。

**Comment by WeiyueSu** [comment]
是如何跑预测的呢？预测时注意把program设置test=True

**Comment by hweidream** [comment]
test_prog = test_prog.clone(for_test=True)，是这个吗

**Comment by hweidream** [comment]
确实是这个问题，感谢
