### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by talhaanwarch** [PaddlePaddle/ERNIE#391]
I am getting following error
ValueError: need at least one array to concatenate

Complete reproduceable file is as follows
https://github.com/talhaanwarch/ERNIE_OLID/blob/master/ERNIE.ipynb

**Comment by tianxin1860** [comment]
> I am getting following error
> ValueError: need at least one array to concatenate
> 
> Complete reproduceable file is as follows
> https://github.com/talhaanwarch/ERNIE_OLID/blob/master/ERNIE.ipynb

Please check `probs` is a list of array, it seems that your `probs` contains no valid array

**Comment by talhaanwarch** [comment]
pardon please. how can i check that. i am unable to find any such option
