### ISSUE TITLE
In-place reshaping is not compatible with ONNX

### ISSUE THREAD

**Issue by winston-zillow** [PaddlePaddle/ERNIE#395]
When trying to export the model to ONNX using paddle2onnx, the in-place reshapings used by ERNIE cause error since ONNX doesn't seem to support in-place operation. Please consider changing `in_place` to `False`.

Pull request at https://github.com/PaddlePaddle/ERNIE/pull/394

**Comment by Meiyim** [comment]
if `in_place` is set to `False`, cound ERNIE be exported to ONNX format, and runs on ONNX compatilbe framework(prtorch/ tf) ?

**Comment by winston-zillow** [comment]
@Meiyim yes it works for me.
