### ISSUE TITLE
Why is the fine tuning process executed 5 times in the SST-2 task?

### ISSUE THREAD

**Issue by AMR-KELEG** [PaddlePaddle/ERNIE#399]
https://github.com/PaddlePaddle/ERNIE/blob/da04e0b44fed78217dc4dd86edad020b2792cb04/script/en_glue/ernie_base/SST-2/task.sh#L20

I am familiarizing with the ERNIE model and found that the finetuning process is executed 5 times with the same random seed (1).
Could you please tell me what is the purpose of doing so?

Thanks

**Comment by Meiyim** [comment]
This seed does not effect the initialize of model weight. it only fix the data pipeline.

**Comment by AMR-KELEG** [comment]
> it only fix the data pipeline.

Could you please elaborate what a data pipeline is? And what's the effect of `i` on this pipeline?

**Comment by Meiyim** [comment]
it means that train data will be shuffled with same random seed during 5 runs.
`i` has no effect in this script, it's a "dummy argument".

**Comment by AMR-KELEG** [comment]
Oh, I see.
Thanks :smile:
