### ISSUE TITLE
BERT模型train.py估算memory问题

### ISSUE THREAD

**Issue by joshuia** [PaddlePaddle/ERNIE#4]
![image](https://user-images.githubusercontent.com/7981476/53866060-9c34fb00-402b-11e9-8c34-280a2cefaf59.png)
BERT模型，发现在估算memory use的时候，batch_size做了处理，为什么要这样做呢？我理解这两者似乎不相关？

**Comment by kuke** [comment]
@joshuia 这里的batch size是tokens总数
