### ISSUE TITLE
Can you evaluate ERNIE2.0(zh) model in the benchmark of CLUE?

### ISSUE THREAD

**Issue by yechens** [PaddlePaddle/ERNIE#400]
ERNIE especially ERNIE2.0 has achieved very brilliant result in a number of NLP tasks, and making great contribution to the development of NLP. Our organization, CLUE, is devoted to promoting the progress of Chinese NLP. We has chosen 9 representative Chinese tasks and the leaderboard is open now (including human's performance). We sincerely hope you can evaluate ERNIE models in our benchmark !

CLUE Group: https://github.com/CLUEbenchmark/CLUE
CLUE Benchmark: https://www.cluebenchmarks.com/

**Comment by Meiyim** [comment]
Thanks for the invitation, but we don't have the plan for CLUE yet.
