### ISSUE TITLE
获取embedding错误

### ISSUE THREAD

**Issue by niantianlei** [PaddlePaddle/ERNIE#403]
使用FAQ1的方式抽取embedding，发现输出不符合预期
输入为
![in](https://user-images.githubusercontent.com/24364049/72676973-3aaa3d80-3ad2-11ea-8b44-c4e7e107158c.png)
输出为
![1](https://user-images.githubusercontent.com/24364049/72676995-60cfdd80-3ad2-11ea-9c8a-8ed71dc3b23d.png)
很多0.999  计算cos距离时，差距也不太明显

**Comment by Meiyim** [comment]
> 很多0.999 

关于这一点是一个transformer已知特性，产出的logits有极端化趋势。

> 计算cos距离时，差距也不太明显

我试了下前两句的cos 为0.93

**Comment by niantianlei** [comment]
> > 很多0.999
> 
> 关于这一点是一个transformer已知特性，产出的logits有极端化趋势。
> 
> > 计算cos距离时，差距也不太明显
> 
> 我试了下前两句的cos 为0.93

第一个和第三个的cos是0.7     请问这样的结果是正常的吗？    看起来区分度并不高
