### ISSUE TITLE
fetch embedding error

### ISSUE THREAD

**Issue by niantianlei** [PaddlePaddle/ERNIE#405]
I want to obtain d400 embedding then modify `hidden_size` to 400.
it has error as follow:
![aee38e6c85f0aaf55fe362a13](https://user-images.githubusercontent.com/24364049/72711272-a8726a00-3ba3-11ea-93b3-9749ad8306e8.png)

**Comment by PROoshio** [comment]
You should not initialize the model with another model which has a shape of (18000, 768)

**Comment by niantianlei** [comment]
> You should not initialize the model with another model which has a shape of (18000, 768)

This means I cant change the vector dimension ？

**Comment by PROoshio** [comment]
Yes
