### ISSUE TITLE
关于FAQ1的embedding预测结果相似度较高问题

### ISSUE THREAD

**Issue by lunlu** [PaddlePaddle/ERNIE#408]
采用FAQ1，对于“请问一下西直门站怎么走”与“昨天老师又留了好多作业”获取embedding后，采用余弦相似度判断，两者之间为0.82，这合理吗？有点高了吧

**Comment by oyjxer** [comment]
1.一个检查数据数据编码是否正确（utf-8）
2.bert，ernie等模型产出的向量cos普遍较高，需要相对的看（看应该相似的是否大于不相似的）
