### ISSUE TITLE
请问是否能够提供特征提取接口方便使用？

### ISSUE THREAD

**Issue by kaijien** [PaddlePaddle/ERNIE#41]

**Comment by LCG22** [comment]
同求

**Comment by tianxin1860** [comment]
@Kaijien @LCG22 
我们近期会支持这个功能；

**Comment by tianxin1860** [comment]
获取句子 Embedding 和 token Embeddings 的工具已发布，具体使用方式可参考 [README](../blob/develop/ERNIE/README.md) **FAQ** 一节
