### ISSUE TITLE
取ernie 2.0 embedding的相关问题

### ISSUE THREAD

**Issue by Akeepers** [PaddlePaddle/ERNIE#410]
想问下如何取ernie 2.0 的token -level embedding? readme中给出的[FAQ1: How to get sentence/tokens embedding of ERNIE?](https://github.com/PaddlePaddle/ERNIE#faq1-how-to-get-sentencetokens-embedding-of-ernie)是针对ernie 1.0的

方便给个demo吗

**Comment by MrPig** [comment]
ERNIE2.0 暂时不支持提取token-level embedding，目前ERNIE2.0预训练模型可以在https://ai.baidu.com/easydl/pro 这个平台上使用。

**Comment by Akeepers** [comment]
那请问下，ERNIE2.0 支持提取sentence-level embedding吗？如果可以，能不能通过seq_len来得到token_level的 embedding

**Comment by Akeepers** [comment]
【upadate】我在ernie/model/ernie.py里找到了get_sequence_output 这个API，感觉是可以取sentence embedding的。我修改了ernie_encoder.py 里的代码：

* line 29: from model.ernie_v1 import ErnieConfig, ErnieModel 改为了  from model.ernie import ErnieConfig, ErnieModel
* line 70, 调用ErnieModel的地方额外加了task_ids作为输入

这样改了之后，得到了readme中的输出
