### ISSUE TITLE
请问多标签分类任务的数据格式应该是什么样的？

### ISSUE THREAD

**Issue by lpl22-github** [PaddlePaddle/ERNIE#411]
列名应该是什么？数据准备好之后只需要修改num_label就可以了么？

**Comment by MrPig** [comment]
可以参考ERNIE finetune任务中的XNLI任务，那个任务也是多分类任务，并且label 是字符串，此时需要提供一份额外的label map 文件，将字符串label 映射到数字ID，具体的数据格式可以将XNLI 数据集下载参考。

**Comment by lpl22-github** [comment]
> 可以参考ERNIE finetune任务中的XNLI任务，那个任务也是多分类任务，并且label 是字符串，此时需要提供一份额外的label map 文件，将字符串label 映射到数字ID，具体的数据格式可以将XNLI 数据集下载参考。

可能我的表达有点不清楚，我想完成的是多标签的分类任务，而不是多分类任务:)
比如本来我的列名是：ID，label_a，label_b，label_c，每个label下面只对应1或0

**Comment by DannyIsFunny** [comment]
你好，当前ernie只支持单标签分类任务，如果想多标签分类任务需要对源码进行修改

**Comment by lpl22-github** [comment]
> 你好，当前ernie只支持单标签分类任务，如果想多标签分类任务需要对源码进行修改

好的，谢谢
