### ISSUE TITLE
run_sequence_labeling only accepts "\x02" as delimiter regardless of the language.

### ISSUE THREAD

**Issue by jacklxc** [PaddlePaddle/ERNIE#412]
I am trying to use ERNIE for English NER task on customized dataset. After exploration, it works only when the tokens are separated by "\x02" instead of " ". This is not intuitive to use and not documented anywhere.

**Comment by MrPig** [comment]
Data processing code of all finetune task is in ernie/reader/task_reader.py. And sequence labeling task  use SequenceLabelReader class to process data. The definition of delimiter is in following code (line 401-402). You can modify it in this place.
![image](https://user-images.githubusercontent.com/3120446/75000914-d0066c00-549a-11ea-8552-ed0b9539378d.png)
