### ISSUE TITLE
想请教一下Ernie训练数据格式问题

### ISSUE THREAD

**Issue by whiker92** [PaddlePaddle/ERNIE#413]
做文本二分类，训练数据格式必须是：label text_a，然后第一列必须是数字么？ 
可以将第一行更改掉么，第一列可以是字符串么？改的函数文件是哪里呢

**Comment by dingsiyu** [comment]
ernie是非明文输入，如果你是明文，可以先根据dict，将原始明文转为id，相应函数很简单，可以自行实现，也可参考tokenization.py文件
