### ISSUE TITLE
Can I use an ERNIE checkpoint to extract embeddings+vocabulary?

### ISSUE THREAD

**Issue by wickedsprout** [PaddlePaddle/ERNIE#416]
Is there a snippet available that I can use to extract the embedding matrix with the corresponding vocabulary?

**Comment by Meiyim** [comment]
you can dump the embedding matrix into numpy pickle and do whatever you want.

dump the embedding with propeller tools (make sure there is a slash at the end of `/PATH/TO/ERNIE/params/`):
```script
python3 ./propeller/tools/ckpt_inspector.py  dump /PATH/TO/ERNIE/params/ --to ./output
```

load the pickle file with numpy:
```python
 np.load('output/word_embedding')
```

**Comment by wickedsprout** [comment]
@Meiyim, thank you!
How do I find out which embedding vector corresponds to each WordPiece though?

**Comment by Meiyim** [comment]
you can look into vocab file (e.g. vocab.txt):
```script
[PAD]
[unused0]
[unused1]
[unused2]
[unused3]
[unused4]
[unused5]
[unused6]
[unused7]
...
excited
sank
ho
athens
1872
denver
welfare
suburb
athletes
trick
diverse                                                                                                                                                                                                     belly                                                                                                                                                                                                       exclusively
```
each line corresponds to a wordpiece, the line number(starts from 0) is the embedding id. you can lookup the embedding matrix with this id to get the vector.

**Comment by wickedsprout** [comment]
Thanks!
