### ISSUE TITLE
请问dbqa中如何显示模型回答的结果

### ISSUE THREAD

**Issue by ln23415** [PaddlePaddle/ERNIE#42]
你好，感觉的模型很棒，但是请问dbqa中如何显示模型回答的结果？我在源码中也没有看到训练模型时读取text_a和text_b的代码，并且test.tsv作为测试不应该没有label吗？

**Comment by tianxin1860** [comment]
> 你好，感觉的模型很棒，但是请问dbqa中如何显示模型回答的结果？我在源码中也没有看到训练模型时读取text_a和text_b的代码，并且test.tsv作为测试不应该没有label吗？

1. 在评估阶段可以对同1个qid下不同 answer 的打分进行排序输出最终答案；

2. 数据组织形式为tsv文件，[reader/task_rader.py](https://github.com/PaddlePaddle/LARK/blob/develop/ERNIE/reader/task_reader.py) 读入tsv文件时会解析文件表头字段: text_a、text_b、qid、label ; 具体数据格式可通过README中提供的**任务数据下载**链接下载查看； 

3. test.tsv 中加入 label 作为模型真实线上预测性能的评估；

**Comment by xiaosdawn** [comment]
你好，我也有同样的疑问，去查看了显示结果的部分，貌似这个结构的定义包含在graph里面了。而且里面不包含“答案”：
即finetune/classifier.py文件中的：
graph_vars = {
         "loss": loss,
         "probs": probs,
         "accuracy": accuracy,
         "labels": labels,
         "num_seqs": num_seqs,
         "qids": qids
     }
不知道是不是理解错了，还请指点一下，这个模型产生的答案具体在哪里？ @tianxin1860

**Comment by TianTian-O1** [comment]
同问
