### ISSUE TITLE
对于sentence reordering task，随机打乱segment的实现在脚本什么位置？

### ISSUE THREAD

**Issue by jfkey** [PaddlePaddle/ERNIE#420]
关于：将一个sentence划分为M个segments，随机打乱segments，通过一个分类任务去预测打乱的顺序类别。
疑问1：打乱segments在哪个脚本文件的哪个函数实现的呢？
疑问2：sentence reordering 的损失在哪个脚本文件的哪个函数实现的呢？

**Comment by Meiyim** [comment]
这两个策略属于pretrain阶段策略(来自ERNIE2.0)，在本代码库中并未涉及。
实际上通过重新制作pretrain数据可以实现这两点。pretrain数据的格式请参考https://github.com/PaddlePaddle/ERNIE/blob/develop/README.zh.md#%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86
