### ISSUE TITLE
ERNIE在Windows上异步并行运算问题

### ISSUE THREAD

**Issue by Shelly111111** [PaddlePaddle/ERNIE#421]
我在Windows上调试ERNIE，发现相同的代码在AI Studio可以正常运行，在Windows本地上却卡在一个地方动不了，且并不报错，程序也仍然运行，最长时间运行半小时后，也不会报错，用单步调试，定位为run_classifier.py的第257行train_exe.run(fetch_list=[])，前面所有代码都能正常输出，而后续的代码无法执行。我猜测是异步并行运算代码在Windows与Linux执行方式可能有所不同。以下是我的环境配置。
硬件环境：CPU i7-8700k，内存32G，显卡NVDIA1080 8G独显
软件环境：Windows 10专业版，Visual Studio2019，Python 3.7

**Comment by WeiyueSu** [comment]
可以先确认下train_data_generator是否能正常输出数据，目前Windows环境支持得比较少，最好切换Linux环境来运行。
