### ISSUE TITLE
在test阶段如何使用多卡？

### ISSUE THREAD

**Issue by wangty163** [PaddlePaddle/ERNIE#425]
在训练阶段，配置了多张gpu卡进行训练，在val（test）阶段，看起来只使用了一张gpu卡在跑数据，导致速度很慢，有什么方法能在val（test）阶段使用多张gpu卡吗？

**Comment by CJHdreamore** [comment]
现在的finetune代码已经支持多机测试，还未开源

**Comment by PROoshio** [comment]
finetune的多卡测试代码已经ready，还未开源。
