### ISSUE TITLE
ERNIE 2.0 中文模型

### ISSUE THREAD

**Issue by InsaneLife** [PaddlePaddle/ERNIE#427]
请问ERNIE 2.0 中文模型有开放出来的计划吗？

**Comment by PROoshio** [comment]
为了让大家更方便、快捷、高效的使用ERNIE，我们正在做易用性更强的ERNIE平台化服务工作，届时会与ERNIE2.0模型同步开放给大家，届时欢迎大家使用。
您可以进入ERNIE官方交流QQ群：760439550，最新消息都会在群内同步给大家。

**Comment by Meiyim** [comment]
see #346 
请移步[EasyDL专业版](https://ai.baidu.com/easydl/pro)，可以直接使用ERNIE-2.0 进行finetune

**Comment by InsaneLife** [comment]
能直接提供下载链接吗，做离线实验

**Comment by Meiyim** [comment]
根据我们最近整体AI平台化的规划；还无法提供直接下载链接；请见谅。

**Comment by InsaneLife** [comment]
那为什么英文就可以公开呢，这块和平台化不冲突吧？

**Comment by cdj0311** [comment]
本来还用了一阵paddle，就是看到paddle开放了很多模型，但是ernie2.0英文版都出来好久了也不开放中文版，没办法只能抛弃paddle回到用tensorflow了。

**Comment by mvb-ai** [comment]
哎，期待开源

**Comment by xiamaozi11** [comment]
催更

**Comment by hugofgh** [comment]
哎，期待开源

**Comment by ChenzhengUESTC** [comment]
> 本来还用了一阵paddle，就是看到paddle开放了很多模型，但是ernie2.0英文版都出来好久了也不开放中文版，没办法只能抛弃paddle回到用tensorflow了。

是的，真是小家子气。
