### ISSUE TITLE
 请问ERNIE有tensorflow版本吗？

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#429]

**Comment by oyjxer** [comment]
暂时无tensorflow版本

**Comment by Meiyim** [comment]
第三方的开发者有一些不错的工作，
see 
https://github.com/thunlp/ERNIE
https://github.com/nghuyong/ERNIE-Pytorch
https://github.com/hotpads/ERNIE-for-the-Rest-of-Us
https://github.com/ArthurRizar/tensorflow_ernie
