### ISSUE TITLE
propeller在线预测

### ISSUE THREAD

**Issue by xiaoqingydf** [PaddlePaddle/ERNIE#431]
使用propeller构建在线预测服务端时，出现僵尸子进程，是什么原因？不过服务倒是能正常预测
![image](https://user-images.githubusercontent.com/20808676/80056450-d4acd680-8556-11ea-8031-89b58a6e4726.png)

**Comment by Meiyim** [comment]
server进程会在每一个卡上启动一个worker进程用于处理真正的gpu计算: https://github.com/PaddlePaddle/ERNIE/blob/develop/propeller/service/server.py#L115
所以实际上这个子进程才负责具体的计算；
