### ISSUE TITLE
Jupter Notebook

### ISSUE THREAD

**Issue by BigSalmon2** [PaddlePaddle/ERNIE#432]
Would you be able to add a Jupter Notebook?

**Comment by Meiyim** [comment]
You can find a tutorial of Ernie text classification in [AI studio](https://aistudio.baidu.com/aistudio/projectdetail/427482), which is a Jupyter notebook server(with free GPU).

**Comment by BigSalmon2** [comment]
Thank you so much. This is very helpful!
