### ISSUE TITLE
ERNIE的分词(字)问题

### ISSUE THREAD

**Issue by ZhengQuancheng** [PaddlePaddle/ERNIE#437]
ERNIE是使用tokenization.py 里的 CharTokenizer() 来分词(字)的吗？
我自己测试的时候，发现tokenization.CharTokenizer()存在这么一个问题：
例如：text = '大家好%werw-', CharTokenizer(text)的结果为['[UNK]']  ==> 这是因为text中的'%'和‘-’不在vocab.txt中

但是，tokenization.FullTokenizer(text)的结果为['大', '家', '好', '[UNK]', 'we', '##r', '##w', '[UNK]']

为什么要设计CharTokenizer()函数呢?当有“非法”出现时，它直接返回['[UNK]']，原本句子的结构都被破坏了。我在训练时，texts中很有可能出现“非法字符”,那这个非法句子就应该作废吗？

**Comment by MrPig** [comment]
CharTokenizer会直接将文本按空格切分成多个Token，如果文本不包含空格的话，可能整个句子就被当做一个词了，所以OOV了，而FullTokenizer会在中文字的前后加入空格，然后再按空格切分。具体细节可以看tokenization.py

**Comment by ZhengQuancheng** [comment]
使用paddlehub导入ERNIE，模型训练时使用了哪一个方法？
模型预测时（文本未处理），使用了哪一个方法？

**Comment by qmzorvim123** [comment]
![image](https://user-images.githubusercontent.com/46865239/82742805-fe932c00-9d94-11ea-86a0-3fb41d8fd30a.png)
请问这个sentence_type_id怎么创建呢？
