### ISSUE TITLE
如何扩充词库

### ISSUE THREAD

**Issue by wanyue-wy** [PaddlePaddle/ERNIE#438]
我的训练数据中有很多名称会被解析为unk，但我的下游任务必须获得这些名称的embedding，所以所有名称都被解析成相同的UNK向量会极度影响任务结果，我想请教一下大家应该如何扩充词库？
我试过直接在vocab.txt文件后添加词汇、修改ernie_config.json中的vocab_size，然后在word_embedding文件中的矩阵的基础上，增加了相应词汇的词向量，它们的值为float64类型的随机向量。但这样在训练时会报错，提示：

**InvalidArgumentError:** Tensor holds the wrong type, it holds float, but desires to be double.**
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < elementwise_add > error]

所以我应该如何扩充词库？新的词哪怕是随机向量也没关系，只要他们不同即可。

**Comment by MrPig** [comment]
你训练数据中名称是中文么？如果是中文的话按字切分不应该存在很多UNK的，英文有可能存在。如果非要添加新的词，建议重做词表后，自己重新训练一个模型。没有尝试过直接在word_embedding文件上加，新加的词向量没有训过效果肯定也不好的，建议还是自己重新训一下模型。
