### ISSUE TITLE
from paddle.fluid.layers import core出现错误

### ISSUE THREAD

**Issue by 425985877** [PaddlePaddle/ERNIE#439]
```
>>> from paddle.fluid.layers import core
/home/disk2/zhaoshen02/model/convert/python36/lib/python3.6/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:38: UserWarning: [Errno 13] Permission denied.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
/home/disk2/zhaoshen02/model/convert/python36/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
W0514 10:20:54.407647 19234 init.cc:128] Compiled with WITH_GPU, but no GPU found in runtime.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: type "VarBase" is already registered!
```

导入时出现问题，请问如何解决？

**Comment by baiyfbupt** [comment]
看起来是Paddle安装的有问题，建议用以下命令检查一下
```python
import paddle.fluid as fluid
fluid.install_check.run_check()
```
可以更新到更新版本的Paddle试下，比如1.7.2或1.8.0

**Comment by 425985877** [comment]
> ```python
> fluid.install_check.run_check()
> ```
>>> fluid.install_check.run_check()
Running Verify Fluid Program ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/disk2/zhaoshen02/model/convert/python36/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 62, in run_check
    ) if not core.is_compiled_with_cuda() else core.CUDAPlace(0))
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97]
PaddlePaddle Call Stacks:
0       0x7fad3721f1d0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fad3721f549p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fad390abe2cp paddle::platform::GetCUDADeviceCount() + 1036
3       0x7fad371ffdd4p
4       0x7fad37251cbep
5       0x7fae629229fdp _PyCFunction_FastCallDict + 557
6       0x7fae628c9686p _PyObject_FastCallDict + 406
7       0x7fae628c975ep _PyObject_Call_Prepend + 206
8       0x7fae628c941ap PyObject_Call + 106
9       0x7fae62941f89p
10      0x7fae6293a803p
11      0x7fae628c957bp _PyObject_FastCallDict + 139
12      0x7fae629baf18p
13      0x7fae629bfb56p _PyEval_EvalFrameDefault + 16774
14      0x7fae629ba440p
15      0x7fae629bb364p
16      0x7fae629bfb56p _PyEval_EvalFrameDefault + 16774
17      0x7fae629badaep
18      0x7fae629bb3ddp PyEval_EvalCodeEx + 109
19      0x7fae629bb42bp PyEval_EvalCode + 59
20      0x7fae629f5d73p
21      0x7fae629f6016p PyRun_InteractiveLoopFlags + 118
22      0x7fae629f687ep PyRun_AnyFileExFlags + 62
23      0x7fae62a12407p Py_Main + 3479
24            0x400bbcp main + 364
25      0x7fae61ba2bd5p __libc_start_main + 245
26            0x400c7dp


这是？

**Comment by baiyfbupt** [comment]
paddle安装状态有问题，建议重新安装一下paddle
