### ISSUE TITLE
请问如何对finetune好的ernie使用fluid.save_inference_model呢？

### ISSUE THREAD

**Issue by ChaunceyBai98** [PaddlePaddle/ERNIE#441]

**Comment by ChaunceyBai98** [comment]
finetune是按照github上教程走的，只是修改了自己的数据集，没有改网络结构啥的。save_inference_model的文档我也看了，主要是不知道feeded_var_names, target_vars这两个参数ernie下应该写啥。

**Comment by ChaunceyBai98** [comment]
摘自https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
#数据输入及训练过程
#保存预测模型。注意，用于预测的模型网络结构不需要保存标签和损失。

fluid.io.save_inference_model(dirname=path, feeded_var_names=['img'], target_vars=[predict], executor=exe)
-----------------------------------------------------------------
这上面的exe复制粘贴到自己的程序里就行么？

**Comment by Lizhengo** [comment]
用fluid.io.save_inference_model的目的是？如果网络结构不变的话建议直接用train.py里的save_persistables, 不需传入feed_var和target_var

**Comment by ChaunceyBai98** [comment]
我想用AIstudio的部署功能。话说我是用ernie微调做了一个文本分类，我看finetune教程里有个注释说是加了全连接层，我也不太确定变没变了，-_-||，您说的用save_persistable能做成inference_model么？我在save-inference-model的教程里找不到相关说明。

**Comment by Lizhengo** [comment]
要做成inference_model需要使用fluid.io.save_inference_model，传入feeded_var_names和target_vars。feeded_var_names就是模型要输入什么，就是ernie的一些输入，参考train.py里create_model函数里的几个输入。
![image](https://user-images.githubusercontent.com/28192236/82169835-504f3880-98f5-11ea-8b70-5c5ceafd28ad.png)
target_vars就根据你的需求来定了看你想输出哪个变量了。

**Comment by ChaunceyBai98** [comment]
做的文本分类，想要模型返回的label，应该怎么写啊，-_-||

**Comment by ChaunceyBai98** [comment]
![image](https://user-images.githubusercontent.com/24198574/82170434-fc455380-98f6-11ea-83a5-3dc0418f4e9a.png)
![image](https://user-images.githubusercontent.com/24198574/82170459-0ff0ba00-98f7-11ea-8649-0b5d417086bd.png)
这是我写的代码，最后那个fluid.io.save_inference_model写的不对，不会写，┭┮﹏┭┮。

**Comment by Lizhengo** [comment]
feeded_var_names就是模型要输入什么，就是ernie的一些输入，target_vars就是你要输出什么。
