### ISSUE TITLE
save_inference_model报错

### ISSUE THREAD

**Issue by hweidream** [PaddlePaddle/ERNIE#443]
参考ernie中的infer_classify.py代码写的mrc的inference模型，在调用save_inference_model时报错如下：

![image](https://user-images.githubusercontent.com/17971652/82215550-2b38e500-994a-11ea-9181-2b1baa7eee26.png)

**Comment by QianShengWu** [comment]
我运行原始的infer_classifyer.py也报同样的错

**Comment by hweidream** [comment]
> 我运行原始的infer_classifyer.py也报同样的错

我找到原因是因为模型input没写全，你可以check下你的是否正确

**Comment by QianShengWu** [comment]
> > 我运行原始的infer_classifyer.py也报同样的错
> 
> 我找到原因是因为模型input没写全，你可以check下你的是否正确

        inputs = [array2tensor(ndarray) for ndarray in [src_ids, sent_ids, pos_ids, input_mask]]

写全了啊，还是出错
