### ISSUE TITLE
fp16模型预测报错

### ISSUE THREAD

**Issue by yaobh** [PaddlePaddle/ERNIE#451]
您好，
        使用旧版代码fine-tuning的fp16的模型，c++前向预测的时候会出Core，报如下的错，请问这是什么问题？
训练模型：
        ernie:repro分支； paddle:1.7.2版本
c++预测：
        代码：repro分支inference/gpu/inference.cc  paddle版本：1.8.0_release

InvalidArgumentError: The DataType of multihead_matmul Op's duplicable Variable BiasQK must be consistent. The current variable type is (::paddle::platform::float16), but the previous variable type is (float). at (Paddle-release-1.8/paddle/fluid/framework/operator.cc:1298)

**Comment by kirayummy** [comment]
试试1.7.2的paddle inference版本？

**Comment by Meiyim** [comment]
C++预测代码并没有在fp16  输入上测试过；若想进行fp16量化加速；最好采用paddle tensorRT方案；相关的使用问题及教程 可以在Paddle官方github提出。

**Comment by yaobh** [comment]
> 试试1.7.2的paddle inference版本？

1.7.2的paddle inference，加载模型都会出错

**Comment by yaobh** [comment]
> C++预测代码并没有在fp16 输入上测试过；若想进行fp16量化加速；最好采用paddle tensorRT方案；相关的使用问题及教程 可以在Paddle官方github提出。

打开了 paddle tensorRT的设置

**Comment by Meiyim** [comment]
@yaobh 
搬运一下paddle方面相关教程：
https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html
https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/python/paddle_trt/infer_trt_ernie.py
