### ISSUE TITLE
install ERNIE ERROR

### ISSUE THREAD

**Issue by shaoshuaig** [PaddlePaddle/ERNIE#453]
安装ERNIE报错，
1. git 安装文档命令报错
pip install -r requirement.txt 改改改成 pip install -r requirements.txt,只有requirements.txt这个文件
2. 安装 ernie 需要 paddlepaddle-gpu 版本，希望文档可以再完善一点，现在一直报错

**Comment by Meiyim** [comment]
相关readme以及安装指引已经在PR: #455 中更新；
现在paddle的依赖不在requirments.txt中了；毕竟有的人有GPU有的人没有（如果跑训练的话；还是推荐使用GPU；否则相当慢；没有的话可以尝试在AIStudio上申请）
可以检查下是否还有得疑问。
