### ISSUE TITLE
怎样让ERNIE模型每次训练的结果都是一样的？

### ISSUE THREAD

**Issue by ZhengQuancheng** [PaddlePaddle/ERNIE#454]
我使用PaddleHub加载ERNIE模型，相关参数数据集都没改过，但是我每次的运行结果都不一致。
我该怎样设置参数(比如随机数种子)来使模型每次运行的结果都一致

**Comment by Lizhengo** [comment]
dropout去掉

**Comment by kinghuin** [comment]
Hi @ZhengQC666666  关于paddlehub的问题欢迎在https://github.com/PaddlePaddle/PaddleHub/issues 提问
您是希望在finetune的时候保证运行结果一致吗？ 
我们还未提供固定所有随机的功能，您可以尝试以下做法：
参考https://github.com/PaddlePaddle/PaddleHub/issues/529 固定program seed，
同时也要关闭reader中的shuffle保证输入数据一致， https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/paddlehub/reader/nlp_reader.py#L253

**Comment by daizh** [comment]
据我了解，现在是无法保证两次训练的结果完全一致的

**Comment by ZhengQuancheng** [comment]
多谢啦
