### ISSUE TITLE
ERNIE demo 命令有误

### ISSUE THREAD

**Issue by shaoshuaig** [PaddlePaddle/ERNIE#456]
python3 ./demo/finetune_classifier_dygraph.py \
    --from_pretrained ernie_1.0 \
    --data_dir ./data/xnli

实际上应该是
python3 ./demo/finetune_classifier_dygraph.py \
    --from_pretrained ernie-1.0 \
    --data_dir ./data/xnli

**Comment by kirayummy** [comment]
Thanks, we will fix it.
