### ISSUE TITLE
这么久了还不开放中文模型，难道在中文上效果不好？

### ISSUE THREAD

**Issue by cdj0311** [PaddlePaddle/ERNIE#460]
这么久了还不开放中文模型，难道在中文上效果不好？

**Comment by dingsiyu** [comment]
关于ernie在中文各个数据集上的效果，具体可以参考论文或github主页上公布的结果。另外，中文模型已经公布，但并未采用直接开源的方式，而是与textone框架绑定发布，可以easydl平台上使用，https://ai.baidu.com/tech/nlp_custom

**Comment by cdj0311** [comment]
说白了就是要拿2.0版的赚钱呗？
