### ISSUE TITLE
Number of places must be 1 in dygraph mode

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#463]
`[WARNING] 2020-05-24 23:17:34,694 [modeling_ernie.py:  224]:	param:classifier.bias not set in pretrained model, skip
/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:718: UserWarning: Varibale [ mlm_bias mlm.weight mlm.bias mlm_ln.weight mlm_ln.bias ] are not used, because not included in layers state_dict
  format(" ".join(unused_para_list)))
Traceback (most recent call last):
  File "ERNIE/demo/finetune_ner_dygraph.py", line 136, in <module>
    for step, (ids, sids, aligned_label, label, orig_pos) in enumerate(tqdm(train_ds.start())):
  File "/mnt/ERNIE/propeller/paddle/data/functional.py", line 77, in start
    r.decorate_batch_generator(_gen, places=places)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1678, in decorate_batch_generator
    self._loader.set_batch_generator(reader, places)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 947, in set_batch_generator
    "Number of places must be 1 in dygraph mode"
AssertionError: Number of places must be 1 in dygraph mode`

**Comment by Meiyim** [comment]
这个是在启动`DataLoader`时未指定单卡环境所致；
解决方案1.
显式设置`export CUDA_VISIBLE_DEVICES=0`从而让python进程只能见到一张卡。

方案2.
将`train_dataset.start()`方法修改为`train_dataset.start(fluid.CUDAPlace(0))`

demo系列代码近期会fix这个问题

**Comment by jtyoui** [comment]
> 这个是在启动`DataLoader`时未指定单卡环境所致；
> 解决方案1.
> 显式设置`export CUDA_VISIBLE_DEVICES=0`从而让python进程只能见到一张卡。
> 
> 方案2.
> 将`train_dataset.start()`方法修改为`train_dataset.start(fluid.CUDAPlace(0))`
> 
> demo系列代码近期会fix这个问题

多谢,已解决
