### ISSUE TITLE
怎么去使用finetune_ner_dygraph

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#467]
请问一下:
   我跑完这个代码: https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py  
请问跑完之后怎么去使用呢??

我根据代码去使用得到的结果全是预测6,
`['这', '也', '是', '美', '国', '、', '俄', '罗', '斯', '等', '石', '油', '、', '天', '然', '气', '都', '很', '丰', '富', '的', '国', '家', '搞', '代', '用', '燃', '料', '的', '原', '因']
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]`
很显然美国和俄罗斯都没有识别出现,

我不知道是不是我的测试代码有问题.
测试代码:
```python
        with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)
            place = fluid.CUDAPlace(0) if self.gpu else None
            with graph.base._switch_tracer_mode_guard_(is_train=False):
                model.eval()
                for step, (ids, sids, aligned_label, label, orig_pos) in enumerate(test_ds.start(place)):
                    chine, pre_labels = [], []
                    for id_ in ids.numpy():
                        chine.append(list(map(lambda x: self.index_vocab.get(x, 0), id_)))
                    loss, logic = model(ids, sids, labels=aligned_label)
                    for pos, lo, la in zip(orig_pos.numpy(), logic.numpy(), label.numpy()):
                        _dic = OrderedDict()
                        for p, l in zip(pos, lo):
                            _dic.setdefault(p, []).append(l)
                        del _dic[-100]
                        merged_lo = np.array([np.array(l).mean(0) for _, l in six.iteritems(_dic)])
                        merged_pred = np.argmax(merged_lo, -1)
                        la = la[np.where(la != -100)]
                        if len(la) > len(merged_pred):
                            print('accuracy loss due to truncation: label len:%d, truncate to %d' % (
                                len(la), len(merged_pred)))
                            merged_pred = np.pad(merged_pred, [0, len(la) - len(merged_pred)], mode='constant',
                                                 constant_values=-100)
                        pre_labels.append(merged_pred)
                    for c, l in zip(chine, pre_labels):
                        print(c)
                        print(l)
                        print()
                    return
```

**Comment by Meiyim** [comment]
最好还是在测试集上评估一下整体的指标（如:f1)是否正常，再具体看case。
从这个预测代码来看貌似没有大问题；所以需要怀疑模型在存储的时候可能并没有把最好的checkpoint存下来；

**Comment by jtyoui** [comment]
> 最好还是在测试集上评估一下整体的指标（如:f1)是否正常，再具体看case。
> 从这个预测代码来看貌似没有大问题；所以需要怀疑模型在存储的时候可能并没有把最好的checkpoint存下来；

请问一下,finetune_ner_dygraph有没有infer代码?只有训练的吗?

**Comment by Meiyim** [comment]
目前的确只包含train以及evaluate部分

**Comment by liruishaer** [comment]
希望提供一下finetune_ner_dygraph 的 infer代码！

finetuen_ner_dygraph.py只需要save_dygraph()么？不用save_inference_model()么？

**Comment by jtyoui** [comment]
> 希望提供一下finetune_ner_dygraph 的 infer代码！
> 
> finetuen_ner_dygraph.py只需要save_dygraph()么？不用save_inference_model()么？

不用save_inference_model,我只用了save_dygraph都可以预测.我预测的方法如下:
```python
 with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)
```

**Comment by liruishaer** [comment]
我使用该链接( https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py)所对应代码训练微调模型，使用save_dygraph保存模型。

使用如下方法加载模型：
 `with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)
`
在执行model.set_dict(para_dict)时，会报错：
`
  File "tt.py", line 36, in <module>
    model.set_dict(para_dict,use_structured_name=True)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 665, in set_dict
    use_structured_name=use_structured_name)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 710, in load_dict
    key_name, use_structured_name))
RuntimeError: Parameter not found, Can't not find [ pooler.weight ] in stat_dictuse_structured_name is set to [True]
`
我查看了一下para_dict中的所有参数名，确实没有pooler.weight参数。

我的主要目的是使用微调后的模型进行加载、预测，怎么解决这个问题呢？

**Comment by liruishaer** [comment]
我使用该链接( https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py)所对应代码训练微调模型，使用save_dygraph保存模型。

使用如下方法加载模型：
`with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)`


在执行model.set_dict(para_dict)时，会报错：
`File "tt.py", line 36, in <module>
    model.set_dict(para_dict,use_structured_name=True)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 665, in set_dict
    use_structured_name=use_structured_name)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 710, in load_dict
    key_name, use_structured_name))
RuntimeError: Parameter not found, Can't not find [ pooler.weight ] in stat_dictuse_structured_name is set to [True]
`

我查看了一下para_dict中的所有参数名，确实没有pooler.weight参数。

我的主要目的是使用微调后的模型进行加载、预测，怎么解决这个问题呢？

**Comment by liruishaer** [comment]
我使用该链接( https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py)所对应代码训练微调模型，使用save_dygraph保存模型。

使用如下方法加载模型：
``` python
with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)
```

在执行model.set_dict(para_dict)时，会报错：
File "tt.py", line 36, in <module> model.set_dict(para_dict,use_structured_name=True) File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 665, in set_dict use_structured_name=use_structured_name) File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 710, in load_dict key_name, use_structured_name)) RuntimeError: Parameter not found, Can't not find [ pooler.weight ] in stat_dictuse_structured_name is set to [True]

我查看了一下para_dict中的所有参数名，确实没有pooler.weight参数。

我的主要目的是使用微调后的模型进行加载、预测，怎么解决这个问题呢？

**Comment by liruishaer** [comment]
我使用该链接( https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py)所对应代码训练微调模型，使用save_dygraph保存模型。

使用如下方法加载模型：
```python
with graph.guard():
            para_dict, _ = graph.load_dygraph(self.save_model)
            model = ErnieModelForTokenClassification.from_pretrained(
                self.pretreatment_model,
                num_labels=len(self.labels_index) + 1)
            model.set_dict(para_dict)
```
在执行model.set_dict(para_dict)时，会报错：
```shell
File "tt.py", line 36, in <module>
    model.set_dict(para_dict,use_structured_name=True)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 665, in set_dict
    use_structured_name=use_structured_name)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/dygraph/layers.py", line 710, in load_dict
    key_name, use_structured_name))
RuntimeError: Parameter not found, Can't not find [ pooler.weight ] in stat_dictuse_structured_name is set to [True]
```

我查看了一下para_dict中的所有参数名，确实没有pooler.weight参数。

我的主要目的是使用微调后的模型进行加载、预测，怎么解决这个问题呢？

**Comment by Meiyim** [comment]
序列标注任务确实不需要用到pooler;
你在执行from_pretrained方法的时候可以加入`has_pooler=False`，这样加载的时候也能对的上了；
参考：https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_ner_dygraph.py#L167
