### ISSUE TITLE
通过累计损失模拟大batch

### ISSUE THREAD

**Issue by luckysheep861** [PaddlePaddle/ERNIE#468]
paddle有没有类似pytorch中，通过累计损失，一定step之后再反向传播，从而达到模拟大batch size的方法？

**Comment by GT-ZhangAcer** [comment]
PaddlePaddle支持重计算，不需要累积梯度就可以达到同显存扩大几倍batch size的效果，而且对整体速度影响不大。
使用文档可以参考：https://paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_recompute.html#batch

**Comment by luckysheep861** [comment]
> PaddlePaddle支持重计算，不需要累积梯度就可以达到同显存扩大几倍batch size的效果，而且对整体速度影响不大。
> 使用文档可以参考：https://paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_recompute.html#batch

感谢，在32G V100中使用ERNIE2.0large, max_seq_len=512, batch size从8提升至24.
