### ISSUE TITLE
ERNIE-GEN 什么时候发布中文版预训练模型？

### ISSUE THREAD

**Issue by jiezouguihuafu** [PaddlePaddle/ERNIE#469]

**Comment by dingsiyu** [comment]
之后有计划会发，现在可以用ernie1.0热启动，finetune生成任务

**Comment by Meiyim** [comment]
关于使用ERNIE1.0完成seq2seq生成任务，我这边有一个非常初期的例子可供参考（效果还在调试中不代表最终性能）：https://aistudio.baidu.com/aistudio/projectdetail/502844

**Comment by jiezouguihuafu** [comment]
> 关于使用ERNIE1.0完成seq2seq生成任务，我这边有一个非常初期的例子可供参考（效果还在调试中不代表最终性能）：https://aistudio.baidu.com/aistudio/projectdetail/502844

![image](https://user-images.githubusercontent.com/37527295/82975395-e595af80-a00e-11ea-849a-69655f6e3100.png)
灰常感谢您的分享，但是页面打不开。

**Comment by Meiyim** [comment]
请重试，后续这个链接会也会有更新，可以多刷刷

**Comment by bojone** [comment]
催更
