### ISSUE TITLE
NER任务fintune 显存12G可以运行吗？

### ISSUE THREAD

**Issue by cloudXia777** [PaddlePaddle/ERNIE#47]

**Comment by tianxin1860** [comment]
> _No description provided._

@cloudXia777 
我们的测试环境是P40, 显存22G；你可以在12G 环境下尝试，如果爆显存不足问题的话，可以尝试调小 batch_size 参数

**Comment by cloudXia777** [comment]
> > _No description provided._
> 
> @cloudXia777
> 我们的测试环境是P40, 显存22G；你可以在12G 环境下尝试，如果爆显存不足问题的话，可以尝试调小 batch_size 参数

非常感谢！ 我会测试一下
