### ISSUE TITLE
demo中自然语言推断XNLI的结果没有达到宣称值

### ISSUE THREAD

**Issue by leo038** [PaddlePaddle/ERNIE#475]
自然语言推断任务中， ERNIE-base 在XNLI 数据集上的宣称精度是79.7%， 但是跑实际demo只有76.6%（中间过程中的最好精度是79.0%）， 用的pretrain_model为ERNIE 1.0 Base 中文。 脚本为demo/finetune_classifier_dygraph.py。请问要达到宣称精度需要修改demo中的参数吗？

**Comment by Meiyim** [comment]
新版的Demo为了提升易用性做了一些改动；你可以通过`--use_lr_decay`并指定`--max_steps`启用linear warmup，应该可以取得更好的效果；
另外，paper中的测试方式为随机 finetune 5遍并取dev集合最佳acc的平均值。

这个demo 力求简单易用；若希望考察所有细节并复现paper，请移步:https://github.com/PaddlePaddle/ERNIE/blob/repro/script/zh_task/ernie_base/run_xnli.sh

**Comment by Meiyim** [comment]
运行以下脚本5遍；计算最佳acc的平均值为：0.804338
```shell
python3 ./ernie_d/demo/finetune_classifier_dygraph.py \
    --from_pretrained ernie-1.0 \
    --data_dir ./data/xnli/ \
    --bsz 32 \
    --lr 5e-5 \
    --epoch 3 \
    --use_lr_decay \
    --max_seqlen 128 \
    --max_steps $((392702 * 3/32))  \
```

log请见附件
[xnli-log.tar.gz](https://github.com/PaddlePaddle/ERNIE/files/4706951/xnli-log.tar.gz)

**Comment by leo038** [comment]
> 运行以下脚本5遍；计算最佳acc的平均值为：0.804338
> 
> ```shell
> python3 ./ernie_d/demo/finetune_classifier_dygraph.py \
>     --from_pretrained ernie-1.0 \
>     --data_dir ./data/xnli/ \
>     --bsz 32 \
>     --lr 5e-5 \
>     --epoch 3 \
>     --use_lr_decay \
>     --max_seqlen 128 \
>     --max_steps $((392702 * 3/32))  \
> ```
> 
> log请见附件
> [xnli-log.tar.gz](https://github.com/PaddlePaddle/ERNIE/files/4706951/xnli-log.tar.gz)

Thank you!
