### ISSUE TITLE
make pretrain data 找不到module paddel

### ISSUE THREAD

**Issue by BinzhuWang** [PaddlePaddle/ERNIE#483]
我在运行 make pretrain data 的时候，显示一直找不到 Paddle 这是怎么回事呢？ ModuleNotFoundError: No module named 'paddle'

**Comment by GT-ZhangAcer** [comment]
这个情况是当前Python环境下没有安装paddlepaddle，建议通过以下步骤进行检查：
1. 确认当前项目Python环境所在位置，如：C:/python37/python.exe。可通过以下代码得到sitepackages路径，该目录的上级或上上级为Python环境主目录，该目录包含python.exe文件。
`import site; site.getsitepackages()`
2. 在终端中运行代码`C:/python37/python.exe -m pip list`以获取当前Python环境第三方库安装情况。
3. 确认当前环境中是否包含paddlepaddle或paddlepaddel-gpu、若不包含，需要通过`C:/python37/python.exe -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple`安装。
