### ISSUE TITLE
README中提供的示例inference_model不可用

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/ERNIE#492]
https://github.com/PaddlePaddle/ERNIE github给的“你也可从此处下载一个预先制作好的ernie-1.0 base模型的 inference_model”，https://ernie.bj.bcebos.com/ernie1.0_zh_inference_model.tar.gz 下下来的模型，使用时报错  

Cannot open file pretrain/inf_model//__model__

![image](https://user-images.githubusercontent.com/11084132/84354086-dc9e0400-abf2-11ea-9fd7-f33e8bcb0381.png)

**Comment by Meiyim** [comment]
你需要将路径指向解压后的文件夹内的文件夹(`pooler`等)，例如
```python
python3 -m propeller.tools.start_server -m ./inf_model/pooler  -p 8881
```

各个子文件夹分别代表第N层的hidden 或 pooler 的输出tensor.

**Comment by Ramlinbird** [comment]
OK，解决了。谢谢～
