### ISSUE TITLE
动态图特征抽取器，静态图模型，运行时cuda初始化报错

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/ERNIE#496]
请教一个问题，想用ernie_tiny动态图作为一个输入处理器，得到句子的向量表达，作为特征输入到后面的模型中，如下图
![image](https://user-images.githubusercontent.com/11084132/84613556-05c1db80-aef6-11ea-91bb-492d3480558c.png)
运行时报错
![image](https://user-images.githubusercontent.com/11084132/84613575-1c683280-aef6-11ea-9fdc-335025dbcb79.png)
请问这个如何解决呢？谢谢～

**Comment by GT-ZhangAcer** [comment]
PaddlePaddle、CUDA、CUDNN版本是多少呢？

**Comment by Meiyim** [comment]
顺便说一下，示例代码里的tokenizer有误，因为ERNIE Tiny是ERNIE全系列里唯一一个采用中文词粒度输入的模型，所以需要使用`ErnieTinyTokenizer`这个类；并需要提前安装LAC（`pip install LAC`）模块。

鉴于最近baidu-LAC开源后，接口做了一些修改，目前的`ErnieTinyTokenizer`可能执行会报错；你可以参考[这个commit](https://github.com/Meiyim/ERNIE/commit/b484d9b19a1da11ff4871d8122a88d1ccaa16f43) 先修改一下`tokenizer_ernie.py`的代码，后续会有PR修复这个兼容性问题
