### ISSUE TITLE
ernie(dynamic)使用示例xnli语料fine_tune后，调用预测服务InferenceClient，返回结果问题

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/ERNIE#498]
使用xnli微调后
先启动了微调保存的inference_model，在linux上调用示例中的预测服务
```
from propeller.service.client import InferenceClient
from ernie.tokenizing_ernie import ErnieTokenizer

client = InferenceClient('tcp://localhost:8881')
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
ids, sids = tokenizer.encode('hello world')
ids = np.expand_dims(ids, 0)
sids = np.expand_dims(sids, 0)
result = client(ids, sids)
```
返回结果为
```
[array([[-0.0460582 , 0.28323928, -0.00521138]], dtype=float32)]
```
这个numpy array代表了什么含义呢？
如果我把输入改为（看了方法参数encode(text,pair)）
```
ids, sids = tokenizer.encode('你好世界','你好中国')
```
结果为
```
[array([[-0.08907083, -0.28950262, -0.01538226]], dtype=float32)]
```
如果是三个类别的概率，但加和并不为1，所以返回的array的含义是什么呢？

**Comment by Meiyim** [comment]
取决于调用`TracedLayer.trace`时model.forward函数的output是什么。
如果你采用的是[这个例子](https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_classifier_dygraph.py#L139)
那么这个输出的tensor即为模型的logits，也就是模型在softmax前的结果。需要softmax才有概率的含义。

**Comment by lerry-lee** [comment]
@Meiyim 明白了，谢谢~
如果我要进行二分类任务，就仿照或改写finetune_classifier_dygraph.py就可以了吧

**Comment by Meiyim** [comment]
所有句子分类任务都可以在这个demo基础上修改。

**Comment by lerry-lee** [comment]
@Meiyim 好的谢谢~
