### ISSUE TITLE
pretrain和finetune 支持多GPU计算吗，多个显卡都能用于模型实际的计算？

### ISSUE THREAD

**Issue by xuehui0725** [PaddlePaddle/ERNIE#50]

**Comment by tianxin1860** [comment]
@xuehui0725  `export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7` 即可开始8卡pretrain 或者 finetune

**Comment by xuehui0725** [comment]
8卡是都可以用于计算吗？还是实际上只能用一个卡计算，虽然还指定了其他卡，但仅仅是占着，并没有实际用于计算？
