### ISSUE TITLE
使用finetune_sentiment_analysis_dygraph.py训练模型报错

### ISSUE THREAD

**Issue by dmsong-star** [PaddlePaddle/ERNIE#501]
用4张2080Ti训练模型报错
----------------------
Error Message Summary:
----------------------
Error: Place CUDAPlace(0) is not supported, Please check that your paddle compiles with WITH_GPU option or check that your train process hold the correct gpu_id if you use Executor at (/paddle/paddle/fluid/platform/device_context.cc:67)

还有一个报错信息是AttributeError: 'Popen' object has no attribute 'join'

**Comment by tianxin1860** [comment]
> ## 用4张2080Ti训练模型报错
> ## Error Message Summary:
> Error: Place CUDAPlace(0) is not supported, Please check that your paddle compiles with WITH_GPU option or check that your train process hold the correct gpu_id if you use Executor at (/paddle/paddle/fluid/platform/device_context.cc:67)
> 
> 还有一个报错信息是AttributeError: 'Popen' object has no attribute 'join'
请帖一下这2个报错的截图

**Comment by dmsong-star** [comment]
![image](https://user-images.githubusercontent.com/66770729/85292802-08f93080-b4cf-11ea-9e73-2b23836ee8ca.png)
![image](https://user-images.githubusercontent.com/66770729/85292904-2d550d00-b4cf-11ea-9f30-4fd6a373f56f.png)
![image](https://user-images.githubusercontent.com/66770729/85292964-4067dd00-b4cf-11ea-9724-627711a6dbc2.png)
![image](https://user-images.githubusercontent.com/66770729/85293014-51b0e980-b4cf-11ea-95ca-ab6ebf7dda2c.png)

然后从
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
开始的这段报错重复三次，后面是最后一段报错
![image](https://user-images.githubusercontent.com/66770729/85293208-9b99cf80-b4cf-11ea-86f2-d20354814da8.png)

**Comment by tianxin1860** [comment]
> ## 用4张2080Ti训练模型报错
> ## Error Message Summary:
> Error: Place CUDAPlace(0) is not supported, Please check that your paddle compiles with WITH_GPU option or check that your train process hold the correct gpu_id if you use Executor at (/paddle/paddle/fluid/platform/device_context.cc:67)
> 
> 还有一个报错信息是AttributeError: 'Popen' object has no attribute 'join'
先配置成单卡，可以正常训练吗？

**Comment by dmsong-star** [comment]
配置成单卡可以训练，4张卡报错之后子线程不会停止，但是训练精度不足，单卡训练如果acc能到75%的话4卡只能到50%

**Comment by tianxin1860** [comment]
> 配置成单卡可以训练，4张卡报错之后子线程不会停止，但是训练精度不足，单卡训练如果acc能到75%的话4卡只能到50%

单卡条件下，使用 0 卡也可以正常训练？

**Comment by dmsong-star** [comment]
是的

**Comment by haozhe-an** [comment]
我这里也同样遇到『AttributeError: 'Popen' object has no attribute 'join'』的报错，请问有什么解决方案或者排查错误的技巧吗？谢谢。

**Comment by Meiyim** [comment]
```shell
AttributeError: 'Popen' object has no attribute 'join'
```
这个是`paddle.distributed.launch` 报的错误；`paddle.distributed.launch`只是一个多进程管理器，不涉及训练核心逻辑，并不是直接原因。

直接原因一般来说在前面的log中，上面提到 
> 开始的这段报错重复三次

这是因为除了0号卡以外的三个进程都报错了并且全部输出在了终端上。
你可以在`paddle.distributed.launch`后面加入`--log_dir ./log` 来将不同进程的错误重定向到文件，从而方便排查。

最后还请检查下分布式代码修改是否正确； **单卡代码并不能直接进行分布式训练**； 若需要分布式训练还请按照[这个demo](https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_classifier_dygraph_distributed.py#L101)修改；

一般来说你需要：

1. 调用`paddle.fluid.dygraph.parallel.prepare_context()`；
2. 用`paddle.fluid.dygraph.DataParallel`来包裹你的model；
3. 调用`model.scaled_loss` 来根据分布式卡数缩放loss；
4. 调用`model.apply_collective_grads()`来进行跨机同步式通信；
