### ISSUE TITLE
ERNIE-GEN 训练过程中评估时报错 Can't locate XML/Parser.pm in @INC 

### ISSUE THREAD

**Issue by Weili-NLP** [PaddlePaddle/ERNIE#502]
![image](https://user-images.githubusercontent.com/25901705/85219773-2ea40e00-b3d9-11ea-8383-9521f71ae3b0.png)
训练一个epoc后执行评估，pyrouge评估摘要结果报错，请问需要修改什么环境变量吗？用的都是开源代码默认配置。

**Comment by zhanghan1992** [comment]
需要安装下perl的xml解析包： yum install perl-XML-Parser
