### ISSUE TITLE
生成中文词向量

### ISSUE THREAD

**Issue by hvuehu** [PaddlePaddle/ERNIE#503]
你好，ERNIE模型能够生成中文的词级别向量，而不是生成字级别向量么？

**Comment by tianxin1860** [comment]
> 你好，ERNIE模型能够生成中文的词级别向量，而不是生成字级别向量么？

你好，当前开源的 ERNIE 模型支持生成字级别的向量和句子级别的动态向量；不支持生成词级别的向量

**Comment by hvuehu** [comment]
好的，谢谢

> > 你好，ERNIE模型能够生成中文的词级别向量，而不是生成字级别向量么？
> 
> 你好，当前开源的 ERNIE 模型支持生成字级别的向量和句子级别的动态向量；不支持生成词级别的向量

**Comment by guowhite** [comment]
想问下句子级别向量 是 通过哪个api实现的呢 @tianxin1860
