### ISSUE TITLE
BERT init_checkpoint

### ISSUE THREAD

**Issue by Jackie127** [PaddlePaddle/ERNIE#51]
请问BERT run_classifier.py中init_checkpoint要如何设置，示例中没有

**Comment by tianxin1860** [comment]
@Jackie127 

用 run_classifier.py 做finetune 不需要配置 init_checkpoint，具体配置可参考 [README](https://github.com/PaddlePaddle/LARK/tree/develop/BERT) **Fine-tuning 任务** 一节
