### ISSUE TITLE
ernie-tiny finetune的脚本

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/ERNIE#510]
请问有ernie-tiny finetune的脚本吗

**Comment by Meiyim** [comment]
ernie tiny的代码跟普通ernie fineunte一致，区别在于前处理的切词部分。
一般来说，在demo 中将tokenizer改为`ErnieTinyTokenizer`即可。

我在[附件](https://github.com/PaddlePaddle/ERNIE/files/4872063/tiny.tar.gz)中上传一个实例代码作为参考，执行脚本：
```shell
python ./test_tiny.py \
    --from_pretrained hub/ernie_tiny/ \
    --data_dir ./data/xnli/ \
    --bsz 32 \
    --lr 5e-5 \
    --epoch 3 \
    --use_lr_decay \
    --max_seqlen 128 \
    --max_steps $((392702 * 3/32))
```

**Comment by kennyLSN** [comment]
lax.lexer() 方法报错了，帮忙看看是不是版本的问题

**Comment by kennyLSN** [comment]
> ernie tiny的代码跟普通ernie fineunte一致，区别在于前处理的切词部分。
> 一般来说，在demo 中将tokenizer改为`ErnieTinyTokenizer`即可。
> 
> 我在[附件](https://github.com/PaddlePaddle/ERNIE/files/4872063/tiny.tar.gz)中上传一个实例代码作为参考，执行脚本：
> 
> ```shell
> python ./test_tiny.py \
>     --from_pretrained hub/ernie_tiny/ \
>     --data_dir ./data/xnli/ \
>     --bsz 32 \
>     --lr 5e-5 \
>     --epoch 3 \
>     --use_lr_decay \
>     --max_seqlen 128 \
>     --max_steps $((392702 * 3/32))
> ```

lax.lexer() 方法报错了，帮忙看看是不是版本的问题

**Comment by Meiyim** [comment]
是版本问题，更新代码即可

**Comment by kennyLSN** [comment]
> 是版本问题，更新代码即可

请问，你代码是那个版本的LAC？

**Comment by Meiyim** [comment]
不是lac的版本；意思是你重新pull一下本代码库

**Comment by kennyLSN** [comment]
> 不是lac的版本；意思是你重新pull一下本代码库

看到了，最新用的jieba
