### ISSUE TITLE
ernie-tiny 使用GPU finetune

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/ERNIE#513]
用GPU finetune的时候，会报importError:libcublas.so cannot open shared object file...

但是在cuda lib中是有libcublas.so.9.0的，请问这种情况该怎么做？

**Comment by Meiyim** [comment]
检查libcublas.so.9.0是否存在LD_LIBRARY_PATH中，并且检查cuda/cudnn版本是否和paddle版本能够匹配。

你可以通过以下指令快速检查安装环境是否成功配置。如果仍然有问题的话，也可以再贴一下下述指令的输出结果。

```
 python -c 'import paddle.fluid as f;f.install_check.run_check()'
```

**Comment by kennyLSN** [comment]
> 检查libcublas.so.9.0是否存在LD_LIBRARY_PATH中，并且检查cuda/cudnn版本是否和paddle版本能够匹配。
> 
> 你可以通过以下指令快速检查安装环境是否成功配置。如果仍然有问题的话，也可以再贴一下下述指令的输出结果。
> 
> ```
>  python -c 'import paddle.fluid as f;f.install_check.run_check()'
> ```
Error: Failed to find dynamic library: libcublas.so(libcublas.so: cannot open share object file: No such file or directory)

和跑gpu报错是一样的，
其中服务器上的安装的cuda9.0，cudnn是7.2，不知道会不会有影响，paddlepaddle-gpu是1.7.1.post97
