### ISSUE TITLE
ERNIE static graph 是否支持增量训练

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/ERNIE#514]
意思是第一次在预训练模型基础上微调，以后继续在上次微调的基础上接着微调训练.
直接更改`init_pretraining_params`为上次保存的checkpoints是否可以？

**Comment by Meiyim** [comment]
用`--init_checkpoint`指定热启动模型。`--init_pretraining_params `用于加载预训练模型（仅限静态图代码）

**Comment by lerry-lee** [comment]
> 用`--init_checkpoint`指定热启动模型。`--init_pretraining_params `用于加载预训练模型（仅限静态图代码）

非常感谢！

**Comment by lerry-lee** [comment]
①请问使用增量学习时，参数设置有没有什么建议呢？目的是想保留已有的一些知识并学习新的知识；
②请问paddle增量训练，也就是指定热启动模型的训练方法，是如何保证模型的持续学习能力的呢？也就是如何在遗忘和学习之间取得平衡的，有没有相关资料学习一下呢？
