### ISSUE TITLE
when will the approach for the champion VCR datasets can be supported?

### ISSUE THREAD

**Issue by runzeer** [PaddlePaddle/ERNIE#515]

**Comment by yinweichong** [comment]
scheduled to be supported in August, 2020.

**Comment by yinweichong** [comment]
sorry to notice that this work is postponed to Sep due to some emergency project.

**Comment by TangDonnie** [comment]
The pre-trained models of ERNIE-ViL and code for downstream VCR task have been released. https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-vil

**Comment by HimariO** [comment]
@TangDonnie will the code that generates image features LMDB files be released too?

**Comment by TangDonnie** [comment]
Our organization of visual features is modified from ViLBERT, thus we directly use the data from it. You can download them in https://github.com/jiasenlu/vilbert_beta/tree/master/data.
