### ISSUE TITLE
使用repro分支下的ernie-gen 报错

### ISSUE THREAD

**Issue by niantianlei** [PaddlePaddle/ERNIE#516]
运行环境python==2.7.14  paddle-gpu=1.7.2     训练的是demo数据，预训练模型使用ernie_base_2.0英文版  错误如下
![image](https://user-images.githubusercontent.com/24364049/86996923-74394700-c1df-11ea-9e18-e7c350f0c4c8.png)

**Comment by zhanghan1992** [comment]
使用ernie_2.0 finetune，这里要改成ernie_config中的 sent_type_vocab_size 需要改成 type_vocab_size
