### ISSUE TITLE
请问支持其他类型的预训练语言模型权重吗？

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/ERNIE#519]
paddle hub支持roberta等其他模型，ernie怎么加载呢？

**Comment by Meiyim** [comment]
目前不支持，请用paddlehub

**Comment by Maybewuss** [comment]
> 目前不支持，请用paddlehub

我尝试用ernie加载hub上down下来的权重，发现报错Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
