### ISSUE TITLE
pretrain.sh运行报错

### ISSUE THREAD

**Issue by Jackie127** [PaddlePaddle/ERNIE#52]
运行script文件夹下的pretrain.sh运行报错，TypeError:a bytes-like object is required,not 'str' 程序也一直出不来结果

**Comment by azuredsky** [comment]
![图片](https://user-images.githubusercontent.com/3139866/55215341-694de380-5234-11e9-8757-a0d25d726057.png)
我也是

**Comment by torans** [comment]
@azuredsky @Jackie127 
line = line.strip().split(";")
->
line = line.strip().split(";".encode(encoding="utf-8"))
