### ISSUE TITLE
VCR任务的代码

### ISSUE THREAD

**Issue by Frankszc** [PaddlePaddle/ERNIE#523]
您好，请问什么时候可以公布VCR任务的代码和预训练模型？
谢谢您

**Comment by yinweichong** [comment]
预期8月份公布。

**Comment by Frankszc** [comment]
好的，谢谢

**Comment by yinweichong** [comment]
sorry, 由于高优项目插入, VCR相关代码和预训练模型开放延后至9月

**Comment by TangDonnie** [comment]
ERNIE-ViL预训练模型和VCR任务代码已开源，https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-vil
