### ISSUE TITLE
Readme中dbqa下载的数据是空的

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/ERNIE#524]
readme给出的[dbqa数据集](https://ernie-github.cdn.bcebos.com/data-dbqa.tar.gz)里面啥也没有

**Comment by Meiyim** [comment]
这是一处失误，感谢指正。
下载链接已经更新：https://ernie-github.cdn.bcebos.com/data-dbqa.tar.gz

**Comment by wangxicoding** [comment]
[情感分类数据集](https://ernie-github.cdn.bcebos.com/data-chnsenticorp.tar.gz)的test集合也有问题，只有一条数据 @Meiyim

**Comment by Meiyim** [comment]
已经修复 情感分类数据集的问题。感谢指正
