### ISSUE TITLE
Ernie1.0 how to use 2 gpu not 8 gpu.

### ISSUE THREAD

**Issue by CuiMingyu** [PaddlePaddle/ERNIE#526]
When I change number of GPUs from 8 to 2, in log it shows an error below.

server not ready,  wait 3 second to retry...

Could you give me some suggestions about this error? Many thanks.

**Comment by Meiyim** [comment]
Can you provide your train script and full log?

you can use `CUDA_VISIBLE_DEVICES` to specify GPUs before training, and launch your training script via `paddle.dsitributed.launch`, for example:

```shell
export CUDA_VISIBLE_DEVICES=2,4,7
python paddle.distributed.launch finetune_classifier_dygraph_distributed.py ...
```
