### ISSUE TITLE
请问如何给ernie加入新的词呢？

### ISSUE THREAD

**Issue by wangleiai** [PaddlePaddle/ERNIE#528]

**Comment by Meiyim** [comment]
ernie1.0 base的embedding大小 是18000，而vocab.txt词表只有17964个token，所以你实际上可以利用剩余的空间来存放你的新词。
简单来说你只需要把新词以wordpiece的规范加入到 vocab.txt里，即可被正确地tokenize.  只要产出的id在18000以内，都不会出错。

英文模型同理

**Comment by wangleiai** [comment]
好的，谢谢！
