### ISSUE TITLE
Fine-tuning ernie-gen for different languages

### ISSUE THREAD

**Issue by alibi123** [PaddlePaddle/ERNIE#530]
Is it possible to fine-tune ernie-gen for other languages. I've tried to use multilingual bert's vocab file and change vocab_size in model config, but if I do so, pretrained model weights cannot be loaded.

Did anyone try to do that?

**Comment by Meiyim** [comment]
ernie-gen vocab contains english alphabet only, and was pretrained only on english corpus.
i don't think finetune from scratch on a multi-lingal scenario will work.

if vocab file is changed, you need to pretrain the model from scratch. however pretraining code is not provided in this repo.

**Comment by secsrexion** [comment]
@Meiyim 
Hello , from what i understood there is no difference between the pre-training and the fine-tuning technique , do you think that we can pretrain with the fintuning code ?

**Comment by Meiyim** [comment]
yes, the training code is bascially the same.
the main difference is data preprocessing pipeline. you need to implement a dynamic pipeline to selecte a random span of input sentence(source side) and move them to target side. see 3.1 section of ERNIE-gen paper for detail.

**Comment by secsrexion** [comment]
Hello 
i'm sorry for replying late i was a little occupied , thank you for your answer you are right i checked the paper , so basicly by adding the data processing pipline and feed it to the same code provided in this repo we'll be able to re-train the model from scratch ?
