### ISSUE TITLE
ERNIE-VIL

### ISSUE THREAD

**Issue by zizheng777** [PaddlePaddle/ERNIE#531]
什么时候开源ERNIE-VIL的代码？

**Comment by yinweichong** [comment]
预期8月份。

**Comment by zizheng777** [comment]
> 预期8月份。

请问有最新消息吗？

**Comment by weiyx16** [comment]
9月会有消息吗

**Comment by yinweichong** [comment]
sorry, 由于高优项目插入, 代码开源延后至9月

**Comment by Pter61** [comment]
大致9月多少呢？请问，这边想作baseline。。。但是没代码

**Comment by TangDonnie** [comment]
ERNIE-ViL预训练模型和VCR任务代码已开源，https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-vil

**Comment by Liu0329** [comment]
@TangDonnie 请问是不是没有预训练的代码，也没有object, attribute, relation相关的代码是吗？

**Comment by TangDonnie** [comment]
是的，当前只开源了finetuning相关代码。
