### ISSUE TITLE
【论文复现】finetune_sentiment_analysis_dygraph.py 中出现grad_clip未定义的错误。

### ISSUE THREAD

**Issue by maotiamo** [PaddlePaddle/ERNIE#537]
查了下optimiza.py文件中的AdamW类进行初始化时，确实没有grad_clip参数，导致出现了错误。
将finetune_sentiment_analysis_dygraph.py文件中104行中的参数删除后，程序能够正常运行。
也许是我有哪里没有注意到，是自己错误导致程序无法运行。

**Comment by Meiyim** [comment]
这个问题是因为梯度裁剪(gradient clip)部分的paddle API频繁改动，导致代码不兼容。
目前开源的代码是以paddle 1.8.1做为基础。 

paddle 1.8.1 的optimizer 允许接受grad_clip 做为参数, 参见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/optimizer_cn/AdamOptimizer_cn.html#adamoptimizer
