### ISSUE TITLE
任务中的2标签是什么意思？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/ERNIE#543]
![image](https://user-images.githubusercontent.com/40688514/90582015-49d7a200-e1ff-11ea-8493-cb3d747157a1.png)

**Comment by Meiyim** [comment]
NSP任务仅在pretrain中使用。
这个截图来自于MNLI数据集，是finetune时使用的数据集合，此阶段没有NSP任务。 这个label为2的意思是：上下句是蕴含关系。

关于pretrain/finetune的概念还请参考BERT,ERNIE,ERNIE 2.0 paper.

**Comment by ghost** [comment]
所以说不支持pretrain？
