### ISSUE TITLE
请问在下载model进行gzip的时候 permission denied问题该怎么解决

### ISSUE THREAD

**Issue by zxhhh97** [PaddlePaddle/ERNIE#546]
报错位置：
D:\Python\anaconda3\lib\gzip.py in __init__(self, filename, mode, compresslevel, fileobj, mtime)
    161             mode += 'b'
    162         if fileobj is None:
--> 163             fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
    164         if filename is None:
    165             filename = getattr(fileobj, 'name', '')

PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\TEMP\\tmp6x21utgg'

**Comment by JKwanghao** [comment]
遇到同样问题

**Comment by JKwanghao** [comment]
> 报错位置：
> D:\Python\anaconda3\lib\gzip.py in **init**(self, filename, mode, compresslevel, fileobj, mtime)
> 161 mode += 'b'
> 162 if fileobj is None:
> --> 163 fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
> 164 if filename is None:
> 165 filename = getattr(fileobj, 'name', '')
> 
> PermissionError: [Errno 13] Permission denied: 'C:\Windows\TEMP\tmp6x21utgg'

看了一下代码，是因为在下载model文件时候，保存在windows采用 with tempfile.NamedTemporaryFile() as f:（file_utils.py的第30行）而tempfile.NamedTemporaryFile创建临时文件在windows没有权限打开

**Comment by Meiyim** [comment]
可以暂时选择手动从本repo的预训练模型列表中直接下载模型并解压到本地使用。

**Comment by kinghuin** [comment]
windows 遇到同样的问题

**Comment by xrzlizheng** [comment]
遇到同样问题
