### ISSUE TITLE
warning: Could not find remote branch dygraph to clone.怎么解决？

### ISSUE THREAD

**Issue by cheeryoung79** [PaddlePaddle/ERNIE#547]
我在执行git clone https://github.com/PaddlePaddle/ERNIE.git -b dygraph --single-branch ./ERNIE时报warning: Could not find remote branch dygraph to clone，请问如何解决？

**Comment by Meiyim** [comment]
dygraph分支现在已经移除，请直接clone develop分支

**Comment by cheeryoung79** [comment]
谢谢，clone成功!
