### ISSUE TITLE
No module named 'propeller'该怎么办

### ISSUE THREAD

**Issue by cheeryoung79** [PaddlePaddle/ERNIE#548]
我在aistudio中paddle1.8下用!pip install paddle-ernie安装 ernie，执行from propeller import log时报No module named 'propeller'，该如何处理？

**Comment by cheeryoung79** [comment]
问题解决了，没加sys.path.append('./ERNIE')

**Comment by shynxon** [comment]
@cheeryoung79 请问sys.path.append('./ERNIE')加在哪里呀
