### ISSUE TITLE
RuntimeError: Parameter file [ ./ernie1.0_for_cmrc2019.pdparams ] not exists怎么办？

### ISSUE THREAD

**Issue by cheeryoung79** [PaddlePaddle/ERNIE#551]
我在执行sd,_ = D.load_dygraph('./ernie1.0_for_cmrc2019') # 加载基于cmrc 数据集训练的阅读理解模型，时，报RuntimeError: Parameter file [ ./ernie1.0_for_cmrc2019.pdparams ] not exists怎么办？

**Comment by tianxin1860** [comment]
> 我在执行sd,_ = D.load_dygraph('./ernie1.0_for_cmrc2019') # 加载基于cmrc 数据集训练的阅读理解模型，时，报RuntimeError: Parameter file [ ./ernie1.0_for_cmrc2019.pdparams ] not exists怎么办？

请问运行的哪个脚本？

**Comment by cheeryoung79** [comment]
运行ask ERNIE项目
