### ISSUE TITLE
ERNIE2.0 中文的预训练模型近期会放出来吗

### ISSUE THREAD

**Issue by tujie-jiangye** [PaddlePaddle/ERNIE#556]

**Comment by XIAOLINSHINE** [comment]
暂时没有开源，ERNIE2.0中文目前已经集成到了更易用的平台上，大家可以试用一下: https://wenxin.baidu.com/wenxin/cloud。
平台现在所有资源都是免费的，内置了很多NLP经典网络，可以更易用地完成NLP任务。

**Comment by tujie-jiangye** [comment]
不错的平台，感谢介绍
