### ISSUE TITLE
产出ERNIE向量报错

### ISSUE THREAD

**Issue by KaiyuanGao** [PaddlePaddle/ERNIE#557]
您好，我按照release2.0分支下的 **FAQ1** 教程获取ERNIE句子向量，运行ernie_encode.py文件报错。

![image](https://user-images.githubusercontent.com/33422503/92457192-8131e100-f1f6-11ea-9409-fb70d59cc2b3.png)

麻烦看看，谢谢！

**Comment by Meiyim** [comment]
see #504

**Comment by KaiyuanGao** [comment]
> see #504

谢谢，已解决。
另外，加上reshape后无法将checkpoint转为inference_model，报错信息为**ValueError: var reshape2_48.tmp_0 not in this block**，请问这要怎么解决呢？
谢谢！

**Comment by Meiyim** [comment]
这个属于paddle使用问题，据我所知save_inference_model时会进行 子图裁剪，如果指定的输入输出并没有被使用，则会被裁剪掉。这个逻辑经常会导致上述错误。更细致的问题可以到paddle 的github repo提出.
