### ISSUE TITLE
Windows中ernie下载错误&运行时类型错误

### ISSUE THREAD

**Issue by kinghuin** [PaddlePaddle/ERNIE#559]
复现方式
```python
import paddlehub as hub
module = hub.Module(name='ernie_gen')    # windows报gzip的错误，linux不会
module.finetune(train_path=r'C:\\test.txt', use_gpu=False, max_steps=5, batch_size=1, max_encode_len=5, max_decode_len=5, log_interval=1)   # windows报tensor类型错误，linux不会
```
其中C:\\test.txt可以随便构建2行
```
1    a    b
2    c    d
```
这个module的源码可见 [这里](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/hub_module/modules/text/text_generation/ernie_gen/module.py)
基本就是本repo下示例的封装

gzip的错误同 https://github.com/PaddlePaddle/ERNIE/issues/546
tensor类型的错误见：
![image](https://user-images.githubusercontent.com/11913168/92719304-88dbbc00-f395-11ea-80db-7fb2b4c6bfd5.png)

**Comment by Meiyim** [comment]
问题可复现，近期修复。
