### ISSUE TITLE
动态图版本的 ERNIE-GEN 链接失效

### ISSUE THREAD

**Issue by herb711** [PaddlePaddle/ERNIE#561]
说明里面有提到

动态图版本的 ERNIE-GEN 代码更加简洁灵活，使用请参考 ERNIE-GEN Dygraph。

但对应链接点进去，并不是  ERNIE-GEN Dygraph的代码。

想请教， ERNIE-GEN Dygraph 的源代码开放吗？能否给出链接

**Comment by Meiyim** [comment]
https://github.com/PaddlePaddle/ERNIE/tree/develop/experimental/seq2seq

**Comment by herb711** [comment]
这个只是预训练的一个例子，我想了解的是ERNIE-GEN Dygraph的代码。这个有开源吗？

**Comment by Meiyim** [comment]
源码在此
https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/seq2seq/finetune_seq2seq_dygraph.py
