### ISSUE TITLE
ernie 动态图fine-tuning报错： KeyError

### ISSUE THREAD

**Issue by mapingshuo** [PaddlePaddle/ERNIE#562]
![image](https://user-images.githubusercontent.com/23031310/93079767-36650d00-f6bf-11ea-9d80-6125b001d807.png)

**Comment by mapingshuo** [comment]
![image](https://user-images.githubusercontent.com/23031310/93081227-8349e300-f6c1-11ea-92dc-930253b690df.png)

**Comment by Meiyim** [comment]
可能是featureColumn的定义跟数据的格式对不上。label列并不是存放的label，需要更多信息才能定位。

**Comment by mapingshuo** [comment]
源码的vocab_dict写错了，和train/1的格式没对上，源码：
https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_classifier_dygraph.py#L72
改成如下就可以：
https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_classifier_dygraph_distributed.py#L66

**Comment by mapingshuo** [comment]
这俩脚本的vocab_dict应该统一一下

**Comment by Meiyim** [comment]
这个dict是任务相关的，起到label_mapping的作用。第一个是以XNLI任务做为demo， 第二个是以MNLI做为demo。

**Comment by mapingshuo** [comment]
> 这个dict是任务相关的，起到label_mapping的作用。第一个是以XNLI任务做为demo， 第二个是以MNLI做为demo。

了解
