### ISSUE TITLE
Single sentence multi class classification

### ISSUE THREAD

**Issue by sasuke96** [PaddlePaddle/ERNIE#564]
Hi 
I want to understand what type of pre preprocessing will i have to do to my data and what are the changes i have to do in SST2 script and run_classfier code to solve a single sentence multi class classification problem using ernie 2.0 Large
I have around 182 labels( they are in text format)
do i have to add label_map_config file in script?
is there any change required in run_classifier code?

**Comment by PROoshio** [comment]
Changing the value of num_label is also needed.
![image](https://user-images.githubusercontent.com/35445537/94097828-d78b5a80-fe59-11ea-89e9-ab6b24ad0570.png)
