### ISSUE TITLE
能否给出一个preprocess 文件

### ISSUE THREAD

**Issue by zhaolulul** [PaddlePaddle/ERNIE#57]
因为想试一下你们预训练的模型  我在处理我自己的数据过程中 不知道你们（ 利用百度内部词法分析工具对句对数据进行字、词、实体等不同粒度的切分，然后基于 tokenization.py 中的 CharTokenizer 对切分后的数据进行 token 化处理，得到明文的 token 序列及切分边界，）用的什么词法分析工具 是否方便公开

**Comment by wq343580510** [comment]
不需要分词  他们是预训练的时候使用了带分词的mask，而finetuning的时候跟bert一样都是基于字符级别，不需要分词就能得到结果。
