### ISSUE TITLE
Is there any methods can help me reproduce your performance in the GLUE benchmark? 

### ISSUE THREAD

**Issue by CosimoFang** [PaddlePaddle/ERNIE#575]
I trained ernie model according to your instruction, but I cannot reach the performance in the GLUE benchmark.

**Comment by zhanghan1992** [comment]
Finetune 5 times and take the median.

**Comment by CosimoFang** [comment]
> Finetune 5 times and take the median.

Well, of course I know that. Ernie2.0 had about 83.5 total score when the paper came out, but was improved to 90.4 several month later. Now I can only reproduce the results in the paper, so I wonder what methods you use to improve it so much.

**Comment by CosimoFang** [comment]
with ensembling and data augmentation, I can only improve the results to 85 total score.

**Comment by OleNet** [comment]
Thanks for your interest! We have improved the model within those months, but we do not yet have a plan to release those methods.
