### ISSUE TITLE
请问ERNIE-ViL视觉问答任务什么时候可以开源呢

### ISSUE THREAD

**Issue by Pter61** [PaddlePaddle/ERNIE#577]
请问ERNIE-ViL视觉问答任务什么时候可以开源呢，我们团队准备用做baseline，但是相对应的任务还没开源，所以现在想问问负责人大概什么时候可以开源。

**Comment by TangDonnie** [comment]
我们已经开源了ERNIE-ViL相关的模型结构和预训练模型，您可以仿照已经开源的VCR任务，进行一些简单的修改来得到VQA任务训练和预测。具体VQA任务开源还在计划中

**Comment by TangDonnie** [comment]
我们已经开源了ERNIE-ViL相关的模型结构和预训练模型，您可以仿照已经开源的VCR任务，进行一些简单的修改来得到VQA任务训练和预测。

**Comment by Pter61** [comment]
> 我们已经开源了ERNIE-ViL相关的模型结构和预训练模型，您可以仿照已经开源的VCR任务，进行一些简单的修改来得到VQA任务训练和预测。

好的，谢谢您！
