### ISSUE TITLE
ERNIE-GEN 可以用于多轮对话吗？

### ISSUE THREAD

**Issue by DesmonDay** [PaddlePaddle/ERNIE#579]
如题。

**Comment by zhanghan1992** [comment]
可以，数据格式参考persona-chat: https://ernie.bj.bcebos.com/persona_chat.tgz

**Comment by DesmonDay** [comment]
另外还想问问，中文的多轮对话也支持么

**Comment by DesmonDay** [comment]
自顶呀(๑˙ー˙๑) 求人回复～

 是不是我把ERNIE模型改成中文1.0版本，然后把语料改成中文对话，就可以进行中文多轮对话回复了呢？

**Comment by zhanghan1992** [comment]
需要先用中文多轮对话的训练数据finetune

**Comment by DesmonDay** [comment]
你好。我自己是原本想参考PaddleHub 的代码进行 finetune。但是对应的输入格式只能是文本序列。如果我自行进行角色区分的话，只能是在每轮对话之间添加特殊字符，想问问这样做合理吗？
