### ISSUE TITLE
请问如何获取输入句子的vector？

### ISSUE THREAD

**Issue by ohho-zb** [PaddlePaddle/ERNIE#58]

**Comment by whyoneisall** [comment]
同求，希望作者能给出中间层向量获取方式~~

**Comment by tianxin1860** [comment]
获取句子 Embedding 和 token Embeddings 的工具已发布，具体使用方式可参考 [README](../blob/develop/ERNIE/README.md) **FAQ** 一节

**Comment by Jackie127** [comment]
如何知道token embeddings的每一行对应哪个字符

**Comment by tianxin1860** [comment]
@Jackie127 
跟你的输入句子经过预处理后的 token 是一一对应的，例如：

`输入单句:  "好好学习，天天向上" `
`预处理后的单句为: "[CLS]好好学习，天天向上[SEP]"，共 11 个 token`
`那么返回的 Embedding 矩阵 W 就是 11 * 768 的矩阵，其中 W[0][:] 就是 "[CLS]" 对应的 embedding，W[1][:] 表示 "好" 对应的 embedding 
 `

**Comment by Jackie127** [comment]
如何获得句子经过处理后的token
