### ISSUE TITLE
save_dir中的模型如何转换为inference_model?

### ISSUE THREAD

**Issue by qwer10** [PaddlePaddle/ERNIE#582]
刚看paddle 和 ernie， 请指点一下

**Comment by oyjxer** [comment]
可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/save_load_variables.html

**Comment by qwer10** [comment]
> 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/save_load_variables.html

感谢！！！

**Comment by qwer10** [comment]
> 可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/coding_practice/save_load_variables.html

感谢！！！@oyjxer
