### ISSUE TITLE
ernie-vil pretained performance issue

### ISSUE THREAD

**Issue by yuewan2** [PaddlePaddle/ERNIE#583]
请问ernie-vil vcr-pretrained model 是还需要 fine-tuned 才能达到paper里的效果吗？我这边按照instruction直接用vcr-pretrain base model 做了vcr qa的inference但效果只有20%左右，想知道是什么原因。谢谢！
<img width="807" alt="Screen Shot 2020-10-27 at 22 38 23" src="https://user-images.githubusercontent.com/31550874/97651207-cffb3a80-1a31-11eb-94f8-db8b37adb3f5.png">

**Comment by TangDonnie** [comment]
是的，vcr-pretrained model是一个pretrained model，是不可以直接预测效果，需要进行finetuning。

**Comment by yuewan2** [comment]
感谢解答！
