### ISSUE TITLE
infer_classifyer.py结果不正确

### ISSUE THREAD

**Issue by gromzhu** [PaddlePaddle/ERNIE#584]
使用infer_classifyer.py加载模型预测每次结果都不一样。
paddle版本1.8。
代码来源repro分支。

**Comment by oyxuan-11** [comment]
您好，加载模型预测的结果可能会受到随机种子的影响，因此模型每次预测的结果会有波动

**Comment by y455471846b** [comment]
随机种子可以影响最后结果的吗？太可怕了
