### ISSUE TITLE
在使用ERNIE1.0模型做命名实体识别时出现了问题！

### ISSUE THREAD

**Issue by FYF1997** [PaddlePaddle/ERNIE#586]
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "demo/finetune_ner_dygraph.py", line 65, in <module>
    tokenizer = ErnieTokenizer.from_pretrained(args.from_pretrained)
  File "/home/fanyongfeng/NER/ERNIE/ernie/tokenizing_ernie.py", line 94, in from_pretrained
    if not pretrain_dir.exists():
AttributeError: 'str' object has no attribute 'exists'
INFO 2020-11-05 16:22:47,411 utils.py:274] terminate all the procs
ERROR 2020-11-05 16:22:47,411 utils.py:416] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-11-05 16:22:50,414 utils.py:274] terminate all the procs

用的数据集是MSRA的中文数据，模型是ERNIE1.0
python3 -m paddle.distributed.launch demo/finetune_ner_dygraph.py  --data_dir data/msra_ner --max_steps 10000 --from_pretrained pretrain_dir/model-ernie1.0 --save_dir output

**Comment by oyxuan-11** [comment]
您好，请贴一下运行脚本，paddle版本，以及配置信息

**Comment by FYF1997** [comment]
> 您好，请贴一下运行脚本，paddle版本，以及配置信息
已经解决了，谢谢回复！
