### ISSUE TITLE
Single GPU with error no nranks

### ISSUE THREAD

**Issue by tuority** [PaddlePaddle/ERNIE#590]
While retraining i met this issues:
**Command:**
!python3 -m paddle.distributed.launch \
--log_dir ./log  \
-- ./ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py \
--data_dir ./cnndm/cnndm \
--save_dir ./model \
--noise_prob 0.7 \
--label_smooth 0.1 \
--predict_output_dir ./pred \
--max_steps $((287113*30/64)) \
--from_pretrained ./ernie 

**Error:**
INFO 2020-11-10 03:51:16,368 launch.py:213] get cluster from args:job_server:None pods:['rank:0 id:None addr:127.0.0.1 port:None visible_gpu:[] trainers:["gpu:[\'0\'] endpoint:127.0.0.1:51215 rank:0"]'] job_stage_flag:None hdfs:None
INFO 2020-11-10 03:51:16,368 utils.py:372] start trainer proc:['/usr/bin/python3', '-u', './ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py', '--data_dir', './cnndm/cnndm', '--save_dir', './model', '--noise_prob', '0.7', '--label_smooth', '0.1', '--predict_output_dir', './pred', '--max_steps', '134584', '--from_pretrained', './ernie'] env:{'FLAGS_selected_gpus': '0', 'PADDLE_TRAINER_ID': '0', 'PADDLE_CURRENT_ENDPOINT': '127.0.0.1:51215', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.0.1:51215'}
INFO 2020-11-10 03:51:37,404 utils.py:274] terminate all the procs
ERROR 2020-11-10 03:51:37,404 utils.py:418] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-11-10 03:51:40,407 utils.py:274] terminate all the procs

**Log file:**
Traceback (most recent call last):
  File "./ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 319, in <module>
    seq2seq(ernie, tokenizer, args)
  File "./ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 254, in seq2seq
    scaled_loss = model.scale_loss(loss)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/parallel.py", line 333, in scale_loss
    if not self._is_data_parallel_mode():
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/parallel.py", line 457, in _is_data_parallel_mode
    return self._strategy.nranks > 1
AttributeError: 'NoneType' object has no attribute 'nranks'

**Comment by Meiyim** [comment]
see #477

**Comment by tuority** [comment]
But that question is for multi gpus, can i use 1 single gpu?

**Comment by HuimengZhang** [comment]
I have the same question here!  How can I use 1 single GPU?

**Comment by Meiyim** [comment]
maybe you could try setting `nrank=1`, and remove these lines to avoid collective communication:
```
D.parallel.prepare_context()
model = D.parallel.DataParallel(model, ctx)
...
scaled_loss = model.scale_loss(loss)
model.apply_collective_grads()
...

```
