### ISSUE TITLE
求教：ernie如果要使用领域数据pretrain，麻烦问下现在ernie tokenizer要怎么使用？

### ISSUE THREAD

**Issue by nicexw** [PaddlePaddle/ERNIE#593]
ernie如果要使用领域数据pretrain，麻烦问下现在ernie tokenizer要怎么使用？

**Comment by luming159** [comment]
我也想问，他们的说明文档太简陋了，而且我改了很久还是有bug，说是示例代码有误。

**Comment by WeiyueSu** [comment]
可以参考首页的示例
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
ids, _ = tokenizer.encode('hello world')
