### ISSUE TITLE
做NER，但是要迁移数据集，使用txt文档，数据集的组织方式一样，该怎么修改代码？

### ISSUE THREAD

**Issue by FYF1997** [PaddlePaddle/ERNIE#594]
数据集组织方式如下：
藏 书 本 来 就 是 所 有 传 统 收 藏 门 类 中 的 第 一 大 户 ， 只 是 我 们 结 束 温 饱 的 时 间 太 短 而 已 。 O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O 
以 家 乡 的 历 史 文 献 、 特 定 历 史 时 期 书 刊 、 某 一 名 家 或 名 著 的 多 种 出 版 物 为 专 题 ， 注 意 精 品 、 非 卖 品 、 纪 念 品 ， 集 成 系 列 ， 那 收 藏 的 过 程 就 已 经 够 您 玩 味 无 穷 了 。 O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O 
精 品 、 专 题 、 系 列 、 稀 见 程 度 才 是 质 量 的 核 心 。 O O O O O O O O O O O O O O O O O O O O O 
藏 书 的 数 量 多 少 不 能 反 映 收 藏 的 质 量 ， 更 不 是 工 薪 层 的 承 受 范 围 。 O O O O O O O O O O O O O O O O O O O O O O O O O O O O O 
书 籍 浩 如 烟 海 ， 靠 个 人 的 精 力 与 财 力 不 可 能 广 而 博 之 。 O O O O O O O O O O O O O O O O O O O O O O O O 
闲 钱 、 闲 地 方 、 闲 工 夫 固 然 重 要 ， 但 藏 书 要 有 文 化 底 蕴 ， 对 于 书 所 传 达 出 来 的 美 感 和 情 趣 ， 要 放 到 一 定 的 专 业 背 景 下 才 能 显 现 。 O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O 
对 于 靠 藏 品 增 值 来 致 富 的 说 法 ， 我 们 不 敢 非 议 ， 但 从 没 听 说 过 哪 位 藏 书 家 靠 书 发 财 了 。 O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O 
去 年 ， 我 们 又 被 评 为 “ 北 京 市 首 届 家 庭 藏 书 状 元 明 星 户 ” 。 O O O O O O O O O O B-LOC I-LOC I-LOC O O O O O O O O O O O O O 
然 而 海 外 图 书 价 格 奇 昂 ， 非 工 薪 层 所 能 承 受 。 O O O O O O O O O O O O O O O O O O O O 
我 俩 都 是 从 事 食 品 生 产 营 销 工 作 的 。 O O O O O O O O O O O O O O O O 

文本格式为TXT文档，编码方式为UTF-8，大佬指导一下，谢谢！原来的part.0文件之间的空格是stx，我试过直接把txt文本改成。o文本，但是运行的时候发生了错误！

**Comment by FYF1997** [comment]
如有代码可以给我发一下邮件：1548670824@qq.com，谢谢大佬们

**Comment by WeiyueSu** [comment]
原来的part.0应该是用"\2"分割符，可以使用python的replace(" ", "\2")直接全部替换就可以了
