### ISSUE TITLE
Hello, I want to use NER to predict new data and return the marked data

### ISSUE THREAD

**Issue by FYF1997** [PaddlePaddle/ERNIE#597]
Hello, I want to use NER to predict the new data and return the marked data, that is, I want to develop an interface by myself, I wonder if you have any good Suggestions, thank you for your advice!

**Comment by tianxin1860** [comment]
> Hello, I want to use NER to predict the new data and return the marked data, that is, I want to develop an interface by myself, I wonder if you have any good Suggestions, thank you for your advice!

Please refer [this code](https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie/run_sequence_labeling.py)

**Comment by FYF1997** [comment]
> > Hello, I want to use NER to predict the new data and return the marked data, that is, I want to develop an interface by myself, I wonder if you have any good Suggestions, thank you for your advice!
> 
> Please refer [this code](https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie/run_sequence_labeling.py)

OK! Thanks!
