### ISSUE TITLE
ERNIE运行Demo中的finetune_seq2seq_dygraph.py出现问题

### ISSUE THREAD

**Issue by herb711** [PaddlePaddle/ERNIE#598]
# 在ai studio中运行如下代码：

```
!python ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py \
--from_pretrained ernie-1.0 \
--data_dir work/datasets/medical \
--max_steps 128 \
--save_dir work/save
```

发生错误。错误显示如下：

[INFO] 2020-11-24 23:23:28,189 [modeling_ernie.py:  201]:	get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[DEBUG] 2020-11-24 23:23:28,190 [file_utils.py:   58]:	https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz cached in /home/aistudio/.paddle-ernie-cache
[DEBUG] 2020-11-24 23:23:28,190 [modeling_ernie.py:  242]:	init ErnieModel with config: {'attention_probs_dropout_prob': 0.1, 'hidden_act': 'relu', 'hidden_dropout_prob': 0.1, 'hidden_size': 768, 'initializer_range': 0.02, 'max_position_embeddings': 513, 'num_attention_heads': 12, 'num_hidden_layers': 12, 'type_vocab_size': 2, 'vocab_size': 18000, 'return_additional_info': True, 'has_pooler': False}
W1124 23:23:28.191437   207 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W1124 23:23:28.196331   207 device_context.cc:260] device: 0, cuDNN Version: 7.6.
[INFO] 2020-11-24 23:23:31,189 [modeling_ernie.py:  219]:	loading pretrained model from /home/aistudio/.paddle-ernie-cache/466eabcffd6d6a83ae9cb97dd1a167bd
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:717: UserWarning: Varibale [ pooler.weight pooler.bias ] are not used, because not included in layers state_dict
  format(" ".join(unused_para_list)))
[INFO] 2020-11-24 23:23:34,437 [tokenizing_ernie.py:   89]:	get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[DEBUG] 2020-11-24 23:23:34,437 [file_utils.py:   58]:	https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz cached in /home/aistudio/.paddle-ernie-cache
[DEBUG] 2020-11-24 23:23:34,447 [tokenizing_ernie.py:  134]:	regex: (\[PAD\])|(\[SEP\])|(\[UNK\])|(\[CLS\])|([a-zA-Z0-9]+|\S)
[INFO] 2020-11-24 23:23:34,449 [finetune_seq2seq_dygraph.py:   83]:	Training starts with args: Namespace(attn_token='[MASK]', beam_width=5, bsz=8, data_dir='work/datasets/medical', eval_bsz=20, eval_steps=5000, from_pretrained='ernie-1.0', inference_model_dir=None, init_checkpoint=None, label_smooth=0.1, length_penalty=1.0, lr=5e-05, max_decode_len=120, max_encode_len=640, max_steps=128, noise_prob=0.7, predict_output_dir=None, save_dir='work/save', skip_eval_steps=1, tgt_type_id=3, use_random_noice=False, warmup_proportion=0.1, wd=0.01)
[INFO] 2020-11-24 23:23:34,453 [feature_column.py:  353]:	reading raw files from work/datasets/medical/train/1.tsv
[INFO] 2020-11-24 23:23:34,453 [feature_column.py:  353]:	reading raw files from work/datasets/medical/dev/1.tsv
[DEBUG] 2020-11-24 23:23:34,453 [finetune_seq2seq_dygraph.py:  216]:	shard 0 of 1
[ERROR] 2020-11-24 23:23:34,456 [functional.py:   69]:	'[NOISE]'
Traceback (most recent call last):
  File "/home/aistudio/ERNIE/propeller/paddle/data/functional.py", line 66, in _gen
    for idx, i in enumerate(self.generator()):
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 240, in _gen
    buf = list(itertools.islice(iterable, batch_size))
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 74, in _gen
    buf.append(next(iterable))
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 148, in _gen
    for i in ret:
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "/home/aistudio/ERNIE/propeller/data/functional.py", line 137, in _gen
    yield fn(*i)
  File "ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 130, in map_fn
    tgt_ids = make_some_noice(tgt_ids) #corrupted
  File "ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 110, in make_some_noice
    noice_ids = np.ones_like(ids) * tokenizer.vocab['[NOISE]']
KeyError: '[NOISE]'
[WARNING] 2020-11-24 23:23:34,458 [   reader.py:  912]:	DygraphDataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 318, in <module>
    seq2seq(ernie, tokenizer, args)
  File "ERNIE/demo/seq2seq/finetune_seq2seq_dygraph.py", line 234, in seq2seq
    for step, data in enumerate(train_ds.start(place)):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 804, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by Meiyim** [comment]
看起来是数据流出的问题。
具体错误见这一行:
```python
noice_ids = np.ones_like(ids) * tokenizer.vocab['[NOISE]']
KeyError: '[NOISE]'
```
ernie-1.0并不是由ernie-gen训练产出，所以词表内并没有预置`[NOISE]`token，你可以在词表尾部找几个没用过的的token代替之.
