### ISSUE TITLE
英文的完形填空任务，相关的模型参数

### ISSUE THREAD

**Issue by ShiYaya** [PaddlePaddle/ERNIE#599]
在你们提供的链接中 [完形填空](https://aistudio.baidu.com/aistudio/projectdetail/433491)
我尝试去做英文的完形填空，发现效果很差，是因为这部分参数没有提供，`param:mlm_bias not set in pretrained model, skip`
请问，近期是否会 release 相关weights？

**Comment by tianxin1860** [comment]
> 完形填空

可以贴一下报错信息吗？

**Comment by ShiYaya** [comment]
使用模型：model_dir = 'ernie-2.0-large-en'
输出的错误信息如下
`![image-20201201093153338](https://i.loli.net/2020/12/01/eryj9Sg7IFiMEf8.png)`

**Comment by ShiYaya** [comment]
使用模型：model_dir = 'ernie-2.0-large-en'
输出的信息如下
[图片](https://i.loli.net/2020/12/01/eryj9Sg7IFiMEf8.png)

**Comment by tianxin1860** [comment]
> 使用模型：model_dir = 'ernie-2.0-large-en'
> 输出的信息如下
> [图片](https://i.loli.net/2020/12/01/eryj9Sg7IFiMEf8.png)

抱歉，因为评测 GLUE、SQuAD 相关任务评测不需要依赖 MLM 任务的参数，因此英文开源模型删掉了这部分参数。

**Comment by ShiYaya** [comment]
请问有开源的打算吗，因为借助这部分参数，可以展开其他的任务，期待你们会开源这部分参数
