### ISSUE TITLE
通过两种方式获得的ERNIE编码后的embedding不同？

### ISSUE THREAD

**Issue by BossRobin** [PaddlePaddle/ERNIE#601]
你好，我使用了两种方式来获取ERNIE编码的embedding表示：
第一种：https://github.com/PaddlePaddle/ERNIE/blob/repro/README.zh.md#faq1-%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%BE%93%E5%85%A5%E5%8F%A5%E5%AD%90%E8%AF%8D%E7%BB%8F%E8%BF%87-ernie-%E7%BC%96%E7%A0%81%E5%90%8E%E7%9A%84-embedding-%E8%A1%A8%E7%A4%BA
第二种：https://github.com/PaddlePaddle/ERNIE#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B
使用的模型是原始的ernie1.0模型。
当我使用这两种方式**编码一个句子时，得到的句子向量和token向量相同**。但是**当输入两个句子时，生成向量不同**。不太清楚是不是我输入格式的问题，求解。
第一种我的dev.tsv文件内容如下：
text_a\ttext_b\tlabel\n
hello world\thello world\t0
第二种我的输入如下：
...
ids, _ = tokenizer.encode('hello world', 'hello world')
...
环境：
paddlepaddle-gpu==1.8.0.post107
python==3.6.9
paddle-ernie==0.0.4.dev1

**Comment by Meiyim** [comment]
第二种的用法有点问题，你把`tokenizer.encode`返回值中的token_type_id给忽略了， 所以模型只看到了上句。

**Comment by BossRobin** [comment]
`import numpy as np
import paddle.fluid.dygraph as D
from ernie.tokenizing_ernie import ErnieTokenizer
from ernie.modeling_ernie import ErnieModel

D.guard().__enter__() 

model = ErnieModel.from_pretrained('ernie-1.0')   
model.eval()
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')

ids, _ = tokenizer.encode('hello world')
ids = D.to_variable(np.expand_dims(ids, 0)) 
pooled, encoded = model(ids)            
print(pooled.numpy()) `
请问在这个例子中，如何将token_type_id传到model中呢，我找不到相应的参数

**Comment by BossRobin** [comment]
还有一个问题，我发现使用第一种方法时，当我将数据集进行切分后，相同句子对得到的embedding并不相同，这是为什么呢？
比如
a.tsv
text_a\ttext_b\tlabel\n
hello world\thello world\t0
和b.tsv
text_a\ttext_b\tlabel\n
hello world\thello world\t0
hello ernie\thello ernie\t0
得到的a.tsv中的embedding和b.tsv中第一个embedding不相同

**Comment by Meiyim** [comment]
目前还是推荐使用第二种方法，也就是paddle1.8+动态图的代码完成这个功能。

**Comment by BossRobin** [comment]
好的，多谢回复
