### ISSUE TITLE
使用paddle serving时，如何在推理时自定义指定fetch返回变量用于保存模型

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/ERNIE#602]
`
client.predict(feed={"x": data}, fetch=["price"])
`
类似上面的“x"和"price"如何在代码中根据需求，自定义输入输出变量，比如分类任务取中间softmax结果返回，而不是最终的某个类别

**Comment by Meiyim** [comment]
最好改写一些代码来完成这个功能。
你可以继承`ernie.modeling_ernie.ErnieModel`来改写其中的`forward`方法。在调用forward过程中 中间的所有tensor你都可以拿到。
你可以参考[文本分类](https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/modeling_ernie.py#L361) 做为例子

**Comment by Meiyim** [comment]
paddle-serving相关的issue  请到paddle-serving 相关代码库提出。

**Comment by lerry-lee** [comment]
好的谢谢，其实我想用serving部署ERNIE文本分类模型，不过在save_model保存服务模型时，没有找到合适的输入和输出变量~因为我想要的输入和输出有的不是variable类型的- -
