### ISSUE TITLE
ERNIE2.0 中文版还没发布吗

### ISSUE THREAD

**Issue by flyerjia** [PaddlePaddle/ERNIE#603]
ERNIE2.0 中文版还发布吗

**Comment by XIAOLINSHINE** [comment]
是的，目前还没有开源。您如果想使用ERNIE2.0，建议您使用EasyDL平台或者文心NLP开发套件(旗舰版)，都预置了ERNIE2.0
EasyDL：https://ai.baidu.com/easydl/
文心NLP开发套件：https://wenxin.baidu.com/wenxin/sdk
