### ISSUE TITLE
ernie_gen的对话任务相关疑问

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/ERNIE#606]
背景:ernie_gen使用ernie-1.0初始化，做中文对话任务。
对话任务需要提供：role_type_size，我看默认是3，对应是user, bot, knowledge
1.如果我的任务不需要knowledge字段，ernie-1.0的pretrain model能复用么?
2.role_type我看是一问一答，支持用户连续说n个吗，即role_type连续几句都是0
3.ernie-1.0中的embedding表示（token/position/src_ids）要和ernie-gen 对话任务表示要是一样的吗

**Comment by oyjxer** [comment]
1. 可以
2. 可以吧用户连续说concat起来
3. 是

**Comment by lonelydancer** [comment]
@oyjxer 你好。 
对于问题3，ernie-1.0模型里好像并没有针对dialog数据的role embedding、turn_embedding等,这样就不一致了吧
