### ISSUE TITLE
加载模型失败runtimerror

### ISSUE THREAD

**Issue by q2044757581** [PaddlePaddle/ERNIE#607]
我跑ErnieModelForSequenceClassification的例子、
训练好的模型用paddle.fluid.save_dygraph(model.state_dict(), "./model/xxx")
然后加载模型 model.load_dict(stat_dict=paddle.fluid.load_dygraph("./model/xxx"))报错
RuntimeError:Parameter not found, Can"t not find [ln.weight] in stat+distuse_structured_name is set to [True]

**Comment by Meiyim** [comment]
请提供一下你的paddle版本。
你可以先确认一下'`./model/xxx.pdparams'`文件是否存在。
