### ISSUE TITLE
使用ernie finetune得到的模型做infer的时候报错

### ISSUE THREAD

**Issue by stillme617** [PaddlePaddle/ERNIE#608]
使用ernie finetune得到的模型做infer的时候报错，请问如何解决？
Error Message Summary:
InvalidArgumentError: The DataType of fused_fc_elenentwise_layernom Op's duplicable Variable Biasl must be consistent. The current variable type is (float)， but the previous variable type is (::paddle.platform::floatlb).  at(/paddle/paddle/fluid/franeuork/operator.cc: 1298)
[operator < fused_fc_elementwise_layernorm > error]

**Comment by Meiyim** [comment]
请问是如何产出inference_model的。看着像是op_fuse阶段出的错误，可以考虑将关闭一些inference时的优化策略。

**Comment by stillme617** [comment]
> 请问是如何产出inference_model的。看着像是op_fuse阶段出的错误，可以考虑将关闭一些inference时的优化策略。
在训练的时候启用了fp16混合精度训练--use_fp16 true，我觉得可能是这个原因。

**Comment by stillme617** [comment]
> 请问是如何产出inference_model的。看着像是op_fuse阶段出的错误，可以考虑将关闭一些inference时的优化策略。
环境设置的话具体是这样的
export FLAGS_eager_delete_tensor_gb=0
export FLAGS_fraction_of_gpu_memory_to_use=0.95
export FLAGS_sync_nccl_allreduce=1
export CUDA_VISIBLE_DEVICES=0,1

**Comment by Meiyim** [comment]
不开启`--use_amp`的话，不会出现这个问题么

**Comment by stillme617** [comment]
> 不开启`--use_amp`的话，不会出现这个问题么

对的，不开启的话是正常的。
还想请问您一个问题，infer_classifyer.py输出的结果是每个label的概率，有相关案例可以直接输出最高概率的结果么？

**Comment by pizzamen** [comment]
如果是use_fp16导致的问题的话，可以尝试把保存目录中的`xxx_master` 重命名为`xxx`(去掉`_master`后缀)。

> 有相关案例可以直接输出最高概率的结果么？

这个可以自行修改代码实现。对概率加入一个`argmax`即可。

**Comment by Meiyim** [comment]
如果是use_fp16导致的问题的话，可以尝试把保存目录中的`xxx_master` 重命名为`xxx`(去掉`_master`后缀)。

> 有相关案例可以直接输出最高概率的结果么？

这个可以自行修改代码实现。对概率加入一个`argmax`即可。

**Comment by stillme617** [comment]
> 如果是use_fp16导致的问题的话，可以尝试把保存目录中的`xxx_master` 重命名为`xxx`(去掉`_master`后缀)。
> 
> > 有相关案例可以直接输出最高概率的结果么？
> 
> 这个可以自行修改代码实现。对概率加入一个`argmax`即可。

好的，感谢
