### ISSUE TITLE
文本分类启动失败

### ISSUE THREAD

**Issue by hdyzhuxun** [PaddlePaddle/ERNIE#609]
我用的paddle2.0.0预处理数据集我下到本地了.请问放到模型里的开发和测试文件夹中的part.0文件是不用动的吧？就用这个格式么？？还是要改成TSV格式才可以啊.
我现在启动报错为：
[INFO] 2021-01-05 00:07:54,727 [feature_column.py: 350]: reading raw files from D:\Code\paddle\chnsenticorp\train\part.0 [INFO] 2021-01-05 00:07:54,727 [feature_column.py: 350]: reading raw files from D:\Code\paddle\chnsenticorp\dev\part.0 W0105 00:07:54.729367 14360 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 11.0 W0105 00:07:54.840369 14360 device_context.cc:330] device: 0, cuDNN Version: 8.0. param:classifier.weight not set in pretrained model, skip param:classifier.bias not set in pretrained model, skip WARNING:root:DataLoader reader thread raised an exception.
然后这是我的启动命令：
python finetune_classifier.py --from_pretrained="D:\Code\paddle\model-ernie1.0.1" --max_seqlen=128 --bsz=8 --data_dir="D:\Code\paddle\chnsenticorp" --epoch="2" --warmup_proportion=0.1 --lr="5e-5" --inference_model_dir="D:/Code/paddle/shuchumoxing" --save_dir="D:\Code\paddle\models_out"

**Comment by hdyzhuxun** [comment]
> 我用的paddle2.0.0预处理数据集我下到本地了.请问放到模型里的开发和测试文件夹中的part.0文件是不用动的吧？就用这个格式么？？还是要改成TSV格式才可以啊.
> 我现在启动报错为：
> `[INFO] 2021-01-05 00:07:54,727 [feature_column.py: 350]: reading raw files from D:\Code\paddle\chnsenticorp\train\part.0 [INFO] 2021-01-05 00:07:54,727 [feature_column.py: 350]: reading raw files from D:\Code\paddle\chnsenticorp\dev\part.0 W0105 00:07:54.729367 14360 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 11.0 W0105 00:07:54.840369 14360 device_context.cc:330] device: 0, cuDNN Version: 8.0. param:classifier.weight not set in pretrained model, skip param:classifier.bias not set in pretrained model, skip WARNING:root:DataLoader reader thread raised an exception.`
> 然后这是我的启动命令：
> `python finetune_classifier.py --from_pretrained="D:\Code\paddle\model-ernie1.0.1" --max_seqlen=128 --bsz=8 --data_dir="D:\Code\paddle\chnsenticorp" --epoch="2" --warmup_proportion=0.1 --lr="5e-5" --inference_model_dir="D:/Code/paddle/shuchumoxing" --save_dir="D:\Code\paddle\models_out"`

**Comment by Meiyim** [comment]
这份数据应该本来就是tsv格式的，我需要在windows环境上发现一下这个问题。
