### ISSUE TITLE
ernie 1.0 使用InferenceClient请求推理服务，服务出core报错

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/ERNIE#611]
你好，
我finetune了 zh_task/ernie_base/run_ChnSentiCorp.sh 任务，用infer_classiyer.py生成model后，启动服务。
用inferernce_client 请求服务，出core
core信息：
W0108 15:06:05.752475 12697 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
W0108 15:06:05.754022 12697 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0108 15:06:05.754050 12697 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0108 15:06:05.754053 12697 init.cc:214] The detail failure signal is:

W0108 15:06:05.754058 12697 init.cc:217] *** Aborted at 1610089565 (unix time) try "date -d @1610089565" if you are using GNU date ***
W0108 15:06:05.754962 12697 init.cc:217] PC: @                0x0 (unknown)
W0108 15:06:05.765040 12697 init.cc:217] *** SIGSEGV (@0x50) received by PID 12697 (TID 0x7fc77e498740) from PID 80; stack trace: ***
W0108 15:06:05.767349 12697 init.cc:217]     @     0x7fc77ded2040 (unknown)
W0108 15:06:05.770890 12697 init.cc:217]     @     0x7fc77e290c98 (unknown)
W0108 15:06:05.773365 12697 init.cc:217]     @     0x7fc77e29927d (unknown)
W0108 15:06:05.774482 12697 init.cc:217]     @     0x7fc77dffa1ef _dl_catch_exception
W0108 15:06:05.775518 12697 init.cc:217]     @     0x7fc77e29898a (unknown)
W0108 15:06:05.776628 12697 init.cc:217]     @     0x7fc77dff92bd (unknown)
W0108 15:06:05.777694 12697 init.cc:217]     @     0x7fc77dffa1ef _dl_catch_exception
W0108 15:06:05.778731 12697 init.cc:217]     @     0x7fc77dffa27f _dl_catch_error
W0108 15:06:05.779821 12697 init.cc:217]     @     0x7fc77dff93e9 __libc_dlopen_mode
W0108 15:06:05.780933 12697 init.cc:217]     @     0x7fc77dfc3f05 (unknown)
W0108 15:06:05.781955 12697 init.cc:217]     @     0x7fc77dc83907 __pthread_once_slow
W0108 15:06:05.783041 12697 init.cc:217]     @     0x7fc77dfc3fdf backtrace
W0108 15:06:05.789768 12697 init.cc:217]     @     0x7fc681d83815 paddle::platform::GetTraceBackString<>()
W0108 15:06:05.796608 12697 init.cc:217]     @     0x7fc681d83ba1 paddle::platform::EnforceNotMet::EnforceNotMet()
W0108 15:06:05.800225 12697 init.cc:217]     @     0x7fc683a6a7ea paddle::operators::MultiHeadMatMulOp::InferShape()
W0108 15:06:05.802749 12697 init.cc:217]     @     0x7fc684a54c06 paddle::framework::OperatorWithKernel::RunImpl()
W0108 15:06:05.806273 12697 init.cc:217]     @     0x7fc684a55193 paddle::framework::OperatorWithKernel::RunImpl()
W0108 15:06:05.807960 12697 init.cc:217]     @     0x7fc684a4e3d0 paddle::framework::OperatorBase::Run()
W0108 15:06:05.814075 12697 init.cc:217]     @     0x7fc6849f1cc3 paddle::framework::NaiveExecutor::Run()
W0108 15:06:05.820092 12697 init.cc:217]     @     0x7fc68218d66c paddle::AnalysisPredictor::Run()
W0108 15:06:05.822775 12697 init.cc:217]     @     0x7fc682062326 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind12_GLOBAL__N_121BindAnalysisPredictorEPNS_6moduleEEUlRNS2_17AnalysisPredictorERKSt6vectorINS2_12PaddleTensorESaISA_EEE_SC_IS8_SE_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESW_
W0108 15:06:05.823576 12697 init.cc:217]     @     0x7fc681dbe221 pybind11::cpp_function::dispatcher()
W0108 15:06:05.823698 12697 init.cc:217]     @     0x559f5899dac8 PyEval_EvalFrameEx
W0108 15:06:05.823783 12697 init.cc:217]     @     0x559f58993e0a PyEval_EvalCodeEx
W0108 15:06:05.823876 12697 init.cc:217]     @     0x559f589af94c (unknown)
W0108 15:06:05.823938 12697 init.cc:217]     @     0x559f5897f70e PyObject_Call
W0108 15:06:05.824028 12697 init.cc:217]     @     0x559f58998a29 PyEval_EvalFrameEx
W0108 15:06:05.824107 12697 init.cc:217]     @     0x559f58993e0a PyEval_EvalCodeEx
W0108 15:06:05.824198 12697 init.cc:217]     @     0x559f589af6a9 (unknown)
W0108 15:06:05.824290 12697 init.cc:217]     @     0x559f589c7e1e (unknown)
W0108 15:06:05.824349 12697 init.cc:217]     @     0x559f5897f70e PyObject_Call
W0108 15:06:05.824440 12697 init.cc:217]     @     0x559f58a2480b (unknown)

生成model命令：
python -u infer_classifyer.py \
    --ernie_config_path ${MODEL_PATH}/ernie_config.json \
    --init_checkpoint "../checkpoints/step_1000" \
    --save_inference_model_path ./saved_model \
    --predict_set  ${TASK_DATA_PATH}/chnsenticorp/test.tsv \
    --vocab_path ${MODEL_PATH}/vocab.txt \
    --num_labels 2

服务端：
环境python2.7、paddle1.7.2
启动服务命令：python -m propeller.tools.start_server -m ernie/saved_model//step_1000_inference_model -p 9999

客户端
python3.7， paddle1.8.1

**Comment by Meiyim** [comment]
从目前的log还无法判断是什么问题，可以再多贴一些log看下。

**Comment by lonelydancer** [comment]
就这些log，请问需要单独安装fluid inference么

**Comment by Meiyim** [comment]
pip install paddle的时候会自动安装fluid_inference.  可能需要深入server端代码打些log看看。
或者再启动server时加入`-v`([reference](https://github.com/PaddlePaddle/ERNIE/blob/develop/propeller/tools/start_server.py#L31)) 选项看是否能看到有用的信息。

**Comment by lonelydancer** [comment]
使用python3，paddle=1.6.0,可以跑通了。

**Comment by lonelydancer** [comment]
@Meiyim 我跑起来后发现程序好像没有加载到gpu上。nvidia-smi看不到进程。我指定了0号卡。

[INFO] 2021-01-13 10:31:45,737 [   server.py:  144]:    InferenceProxy starting...
[INFO] 2021-01-13 10:31:45,738 [   server.py:  153]:    Queue init done
[DEBUG] 2021-01-13 10:31:45,739 [   server.py:   69]:   run_worker 0
[DEBUG] 2021-01-13 10:31:45,739 [   server.py:   72]:   cuda_env 0
[DEBUG] 2021-01-13 10:31:46,793 [   server.py:   80]:   Predictor building 0
[DEBUG] 2021-01-13 10:31:46,793 [   server.py:   53]:   create predictor on card 0
E0113 10:31:46.793504 19100 analysis_config.cc:73] Please compile with gpu to EnableGpu()
