### ISSUE TITLE
ernie文本分类泛化能力很差是什么原因？

### ISSUE THREAD

**Issue by stillme617** [PaddlePaddle/ERNIE#612]
在训练集大约70左右的准确率，测试集60%左右，但是使用微调后的模型分类新的文本效果很差，只有43%左右，新文本的类别分布比例和训练集测试集都是差不多的，请问是什么原因导致的？

**Comment by Meiyim** [comment]
原因有很多。你可以结合#475 看看能不能复现基准数据（如xnli）上的准确率。然后再看模型加载是否正确。数据处理是否正确。acc计算是否正确等等。
