### ISSUE TITLE
训练时对dev评估结果，与直接预测dev结果不一致

### ISSUE THREAD

**Issue by zqleee** [PaddlePaddle/ERNIE#613]
预测代码
![image](https://user-images.githubusercontent.com/33724161/104404673-2e967600-5596-11eb-976e-dab4638e3e72.png)
评估代码
![image](https://user-images.githubusercontent.com/33724161/104404688-3bb36500-5596-11eb-8625-041666aec76b.png)

我demo训练了一个模型，准确度为：
![image](https://user-images.githubusercontent.com/33724161/104404776-74533e80-5596-11eb-9ece-755bfa031047.png)
然后直接用这个模型预测dev文件：
准确度只有0.56左右

请问是训练和评估过程的batch_size和预测时的batch_size不同导致的吗，我现在只能猜测是自定义模型中的这个部分出了问题
![image](https://user-images.githubusercontent.com/33724161/104404892-b11f3580-5596-11eb-9d31-163f7a659d02.png)

**Comment by zqleee** [comment]
我把代码全部换动态图，结果一致。是不是静态图有什么问题？导致eval和predict过程不一致

**Comment by oyxuan-11** [comment]
您好，请问您运行的python版本，paddle 版本是多少呢

**Comment by zqleee** [comment]
python 3.7.7  2.0.0rc1 方便留个联系方式吗

**Comment by LeeeeeeeeeeeZZZ** [comment]
我做的时候分了两个阶段训练。第一个阶段用的一组超参数，第二阶段换了另一组。然后在预测的时候，必须要和第二阶段的超参数相同，才能得到正确的结果。我看了下这些参数，好像跟预测阶段都没有太大的关系，都是训练时的一些参数。为什么会出现这种情况呢
![image](https://user-images.githubusercontent.com/33724161/104564957-84e2e200-5686-11eb-87db-bf000588ddee.png)

**Comment by zqleee** [comment]
还有ernie代码目前支持bert动态图吗，参数都是我自己手动映射过去的
