### ISSUE TITLE
如何加载finetune的模型做预测

### ISSUE THREAD

**Issue by EDkami9399** [PaddlePaddle/ERNIE#617]
我已经用自己的数据集finetune了一个模型，模型参数保存在了一个'infer_model'文件夹里 那么我要如何加载这个模型去做predict呢。 之前尝试了https://github.com/PaddlePaddle/ERNIE里在线预测的方式，只改动了模型路径，但是最后输出的结果[array([[ 1.5209239,  2.910406 , -5.0615687]], dtype=float32)]emmmmm貌似不是很能理解，所以我要如何实现这个predict的过程呢。 py3.6  paddle2.0

**Comment by WeiyueSu** [comment]
infer_model里的__model__文件指定了模型的关系和输入输出，如果是使用上面的在线预测，以上你的输出分数就是3分类的结果（过softmax之前）。

**Comment by EDkami9399** [comment]
> infer_model里的__model__文件指定了模型的关系和输入输出，如果是使用上面的在线预测，以上你的输出分数就是3分类的结果（过softmax之前）。

明白了 谢谢 ~ 还有个问题 就是如果我想加载模型参数的话要怎样做呢，因为除了做infer之外还想加载fintune的模型然后提取词向量~

**Comment by zhuzhf** [comment]
调用paddle.static.save_inference_model(path_prefix, feed_vars, fetch_vars, executor)函数的时候，fetch_vars设成你想要提取的变量，这样的话可以输出相应的向量。

**Comment by EDkami9399** [comment]
> 调用paddle.static.save_inference_model（path_prefix，feed_vars，fetch_vars，executor）函数的时候，fetch_vars建立成你想要的提取变量，这样的话可以输出相应的向量。

好的~感谢！
