### ISSUE TITLE
ernie-gen的position embedding

### ISSUE THREAD

**Issue by pvop** [PaddlePaddle/ERNIE#618]
您好，最近看您ernie-gen的论文，真的是非常棒的工作，想请教您一个问题：
T5中通过特殊字符来表示那些地方被mask了，那些地方需要预测。请问ernie-gen是和mass一样通过位置的方式吗，ernie-gen中decoder输入词的位置是其在原始input中的位置吗？
感谢回复！

**Comment by XIAOLINSHINE** [comment]
“请问ernie-gen是和mass一样通过位置的方式吗，ernie-gen中decoder输入词的位置是其在原始input中的位置吗？”
是的
