### ISSUE TITLE
二次训练，有能跑通的吗？

### ISSUE THREAD

**Issue by FankLi** [PaddlePaddle/ERNIE#619]
https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/pretrain/README.md

上面的官方说明（这个说明有点混乱。。。），是需要什么版本进行训练？有没有能跑通的？

期待并感谢官方的回答！

**Comment by zhuzhf** [comment]
readme上是没有设置node_ip，默认是单机多卡的并行训练。paddle.distributed.launch从paddle 1.5.1开始支持，最好使用最新的版本，更多分布式相关的信息可以参考python3 -m paddle.distributed.launch --help和https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/distributed_training/cluster_quick_start.html
