### ISSUE TITLE
预训练代码 for ERNIE ViL

### ISSUE THREAD

**Issue by HarveyGuo960817** [PaddlePaddle/ERNIE#620]
请教是否能够开源ERNIR ViL的预训练代码呢？尤其是如何用scene graph parser进行词性的识别，以及最后对应预训练任务的处理？谢谢

**Comment by TangDonnie** [comment]
ERNIE-ViL中的scene graph parser是采用的开源的spice（https://github.com/peteanderson80/SPICE）模型，而场景图的任务，可以根据论文的描述比较容易复现。

**Comment by TangDonnie** [comment]
ERNIE-ViL中的scene graph parser是采用的开源的spice [https://github.com/peteanderson80/SPICE]
模型，而场景图的任务，可以根据论文的描述比较容易复现。

**Comment by HarveyGuo960817** [comment]
> ERNIE-ViL中的scene graph parser是采用的开源的spice [https://github.com/peteanderson80/SPICE]
> 模型，而场景图的任务，可以根据论文的描述比较容易复现。

收到，谢谢答复

**Comment by weihao20** [comment]
> > ERNIE-ViL中的scene graph parser是采用的开源的spice [https://github.com/peteanderson80/SPICE]
> > 模型，而场景图的任务，可以根据论文的描述比较容易复现。
> 
> 收到，谢谢答复

你好，请问你现在实现了scene graph parser了吗
