### ISSUE TITLE
hub install ernie_gen==1.0.2 安装成功，但引入报错

### ISSUE THREAD

**Issue by uuleaf** [PaddlePaddle/ERNIE#622]
在AIStudio 以及以下docker环境，均无法跑通ernie_gen
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7

#安装流程
_paddlehub 从1.8.0 到2.0.0 都试了了，paddle-ernie的dev各个版本也都用穷举安装了，没有一个跑通的_
python3 -m pip install paddlehub -i https://mirror.baidu.com/pypi/simple
python3 -m pip install paddle-ernie -i https://mirror.baidu.com/pypi/simple
hub install ernie_gen==1.0.2
![image](https://user-images.githubusercontent.com/6434727/106361321-4886d580-6358-11eb-8f8e-117bf563b2bc.png)

#跑训练的时候报错

![image](https://user-images.githubusercontent.com/6434727/106361339-5f2d2c80-6358-11eb-8b4c-c3c532628f6d.png)

**Comment by uuleaf** [comment]
百度不维护了啊，哈哈哈+1

**Comment by iceriver97** [comment]
同样的错误，请问您解决了吗？
