### ISSUE TITLE
Ernie-M (multilingual) availability

### ISSUE THREAD

**Issue by acul3** [PaddlePaddle/ERNIE#623]
hi 
according to paper (https://arxiv.org/abs/2012.15674) ernie-m 
pre-trained models will be made publicly available

is it available yet?

so excited to try since it outperform xtreme task

thanks

**Comment by oyxuan-11** [comment]
Hi

Thank you for your interest in our work, we plan to make ERNIE-M public in May 2021.

Best

**Comment by acul3** [comment]
great thanks! looking forward to explore

**Comment by yaysummeriscoming** [comment]
> Hi
> 
> Thank you for your interest in our work, we plan to make ERNIE-M public in May 2021.
> 
> Best

Really looking forward to giving ERNIE-M a go! Any update on the release date?

**Comment by ElaineSee** [comment]
Same here! Really excited to check out ERNIE-M. Just gonna leave a comment here so that I can be notified when it's released! Looking forward. Thanks =)

**Comment by wangshuohuan** [comment]
The code and models of ERNIE-M had been available at https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m .
