### ISSUE TITLE
动态图执行ernie pretrain过程的教程能否更详细

### ISSUE THREAD

**Issue by pangyoki** [PaddlePaddle/ERNIE#626]
包括使用的数据集、可正常执行的脚本

**Comment by tianxin1860** [comment]
> 包括使用的数据集、可正常执行的脚本

请问在您的当前环境跑动态图脚本会报什么错？

**Comment by pangyoki** [comment]
https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/pretrain/README.md 
因为这个readme里没给数据集，我用的repro分支下data中的demo_train_set.gz数据。然后用readme里给出的指令跑，报了batch size的错：
<img width="721" alt="21850c2561ec17b59be61a43db390ac0" src="https://user-images.githubusercontent.com/26408901/106692466-7fd2dc00-660f-11eb-9109-b0ce6916907a.png">
<img width="1135" alt="204cd57db294a44bbdc68769ab5472b3" src="https://user-images.githubusercontent.com/26408901/106692492-8bbe9e00-660f-11eb-895a-cab7ca5f37b9.png">

**Comment by pangyoki** [comment]
如果完全按照readme的步骤，用make_pretrain_data.py生成数据集，执行的时候会hang住

**Comment by 447428054** [comment]
@pangyoki 请问你的问题解决了吗
