### ISSUE TITLE
ERNIE的tokenizer可以加入special token吗，像bert的[unused1]

### ISSUE THREAD

**Issue by cocoa0409** [PaddlePaddle/ERNIE#629]
如题
from ernie.tokenizing_ernie import ErnieTokenizer
我看ERNIE字典里没保留这些special token，如果需要用到的话，应该怎么办呢？

**Comment by Meiyim** [comment]
`ErnieTokenizer `有`special_token_list `用来添加特殊字符。特殊字符将不会被切分： https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/tokenizing_ernie.py#L121

通过手动修改词表(`vocab.txt`) 文件，可以在词表后部添加新的特殊字符，如`[unused1]`等
