### ISSUE TITLE
ernie-vil finetuning下游任务卡住

### ISSUE THREAD

**Issue by wanglc2008** [PaddlePaddle/ERNIE#631]
https://github.com/PaddlePaddle/ERNIE/blob/f6628ee8dfac2809ad42ebe9c8985fab8d8f2b9b/ernie-vil/finetune.py#L829

使用flickr30k数据finetune image retrieval和text retrieval任务，运行到这个会卡住
paddle1.8 + python2.7

**Comment by TangDonnie** [comment]
你好，请问你的训练数据ready了吗
