### ISSUE TITLE
subprocess.CalledProcessError returned non-zero exit status 1 in ernie-gen/utils/finetune_launch.py

### ISSUE THREAD

**Issue by darshan22** [PaddlePaddle/ERNIE#632]
I am trying to fine-tune the ernie-gen base model for squad-qg task, but I get the following error.

-----------  Configuration Arguments -----------
current_node_ip: 11.111.0.8
log_prefix:
node_id: 0
node_ips: 11.111.0.8
print_config: True
split_log_path: log
training_script: ./run_seq2seq.py
training_script_args: ['--use_cuda', 'true', '--do_train', 'true', '--do_val', 'true', '--do_test', 'true', '--do_pred', 'false', '--train_set', './Data/datasets/squad_qg//train.tsv', '--dev_set', './Data/datasets/squad_qg//dev.tsv', '--test_set', './Data/datasets/squad_qg//test.tsv', '--pred_set', './Data/datasets/squad_qg//', '--epoch', '10', '--tokenizer', 'FullTokenizer', '--tokenized_input', 'true', '--task_type', 'normal', '--role_type_size', '0', '--turn_type_size', '0', '--max_src_len', '512', '--max_tgt_len', '96', '--max_dec_len', '48', '--hidden_dropout_prob', '0.1', '--attention_probs_dropout_prob', '-1', '--random_noise', 'true', '--noise_prob', '0.7', '--continuous_position', 'true', '--tgt_type_id', '3', '--batch_size', '4', '--learning_rate', '2.5e-5', '--lr_scheduler', 'linear_warmup_decay', '--warmup_proportion', '0.1', '--weight_decay', '0.01', '--weight_sharing', 'True', '--label_smooth', '0.1', '--do_decode', 'true', '--beam_size', '5', '--length_penalty', '1.0', '--init_pretraining_params', 'ernie_gen_base/params', '--vocab_path', 'ernie_gen_base/vocab.txt', '--ernie_config_path', 'ernie_gen_base/ernie_config.json', '--checkpoints', './checkpoints', '--save_and_valid_by_epoch', 'true', '--eval_script', 'sh', './eval/tasks/squad_qg/eval.sh', '--eval_mertrics', 'Bleu_4,METEOR,ROUGE_L', '--random_seed', '83513']
------------------------------------------------
all_trainer_endpoints:  11.111.0.8:6170,11.111.0.8:6171,11.111.0.8:6172,11.111.0.8:6173 , node_id:  0 , current_ip:  11.111.0.8 , num_nodes:  1 , node_ips:  ['11.111.0.8'] , gpus_per_proc:  1 , selected_gpus_per_proc:  [[0], [1], [2], [3]] , nranks:  4
Traceback (most recent call last):
  File "./utils/finetune_launch.py", line 175, in <module>
    main(lanch_args)
  File "./utils/finetune_launch.py", line 166, in main
    start_procs(args)
  File "./utils/finetune_launch.py", line 136, in start_procs
    raise subprocess.CalledProcessError(returncode=procs[i].returncode,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './run_seq2seq.py', '--use_cuda', 'true', '--do_train', 'true', '--do_val', 'true', '--do_test', 'true', '--do_pred', 'false', '--train_set', './Data/datasets/squad_qg//train.tsv', '--dev_set', './Data/datasets/squad_qg//dev.tsv', '--test_set', './Data/datasets/squad_qg//test.tsv', '--pred_set', './Data/datasets/squad_qg//', '--epoch', '10', '--tokenizer', 'FullTokenizer', '--tokenized_input', 'true', '--task_type', 'normal', '--role_type_size', '0', '--turn_type_size', '0', '--max_src_len', '512', '--max_tgt_len', '96', '--max_dec_len', '48', '--hidden_dropout_prob', '0.1', '--attention_probs_dropout_prob', '-1', '--random_noise', 'true', '--noise_prob', '0.7', '--continuous_position', 'true', '--tgt_type_id', '3', '--batch_size', '4', '--learning_rate', '2.5e-5', '--lr_scheduler', 'linear_warmup_decay', '--warmup_proportion', '0.1', '--weight_decay', '0.01', '--weight_sharing', 'True', '--label_smooth', '0.1', '--do_decode', 'true', '--beam_size', '5', '--length_penalty', '1.0', '--init_pretraining_params', 'ernie_gen_base/params', '--vocab_path', 'ernie_gen_base/vocab.txt', '--ernie_config_path', 'ernie_gen_base/ernie_config.json', '--checkpoints', './checkpoints', '--save_and_valid_by_epoch', 'true', '--eval_script', 'sh', './eval/tasks/squad_qg/eval.sh', '--eval_mertrics', 'Bleu_4,METEOR,ROUGE_L', '--random_seed', '83513']' returned non-zero exit status 1.

**Comment by Meiyim** [comment]
please check the real training log at `./log`

**Comment by darshan22** [comment]
The above pasted stuff is what I found the log file in ./log folder. I have 4 GPU's therefore I changed the variable "CUDA_VISIBLE_DEVICES" in run_seq2seq.sh to "0,1,2,3". But it seems that the subprocess's exited before even starting the training. I couldn't get enough details about this error.
