### ISSUE TITLE
请问中文模型2.0版本啥时候开源呢

### ISSUE THREAD

**Issue by Cypress12** [PaddlePaddle/ERNIE#634]
有时间表吗

**Comment by XIAOLINSHINE** [comment]
暂时不会开源，如果您想使用ERNIE2.0，目前有2种方式：
1.通过EasyDL平台：https://ai.baidu.com/easydl/nlp/  目前平台支持文本分类-单标签、文本分类-多标签、情感倾向分析、文本实体抽取、文本实体关系抽取、短文本相似度任务，后续还将继续新增常用任务，通过ERNIE2.0完成上述任务，效果更好。
2.下载文心NLP开发套件：https://wenxin.baidu.com/wenxin/sdk  可以申请旗舰版的下载，旗舰版支持ERNIE2.0。

**Comment by loujie0822** [comment]
现在的pretrain 可以给予ERNIE2.0的英文版进行吗？

**Comment by nbcc** [comment]
> 现在的pretrain 可以给予ERNIE2.0的英文版进行吗？

可以关注下多粒度语义预训练模型 ernie-gram，中文模型已开源 [Link](https://github.com/PaddlePaddle/ERNIE/tree/develop/ernie-gram)

附中文典型任务效果对比：
<img width="882" alt="ernie-gram 效果" src="https://user-images.githubusercontent.com/864331/119317728-00931200-bcab-11eb-90cb-556cfdd92190.png">


正式论文见：https://arxiv.org/abs/2010.12148
