### ISSUE TITLE
tokenizing_ernie.truncate长度问题

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/ERNIE#635]
在使用tokenizing_ernie对句对进行编码的时候：

ErnieTokenizer.encode(text_a, text_b, max_seq_len-3)

最后在规范化句子总长度时会调用truncate：
https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/tokenizing_ernie.py#L187

`
def truncate(self, id1, id2, seqlen):
        len1 = len(id1)
        len2 = len(id2)
        half = seqlen // 2
        if len1 > len2:
            len1_truncated, len2_truncated = max(half, seqlen - len2), min(
                half, len2)
        else:
            len1_truncated, len2_truncated = min(half, seqlen - len1), max(
                half, seqlen - len1)
        return id1[:len1_truncated], id2[:len2_truncated]

`
假设原始的text_a,text_b即 id1, id2的长度是138和258，设置的max_len=128 ，那么此时seqlen=max_len-3=125
len1=138, len2=258, 那么len1_truncated=-13，len2_truncated=62， 那么id1[:len1_truncated]的长度就是125， id2[:len2_truncated]就是62， 经过build_for_ernie加上cls，sep,sep后总长度就是125+62+3=190 ,和预设置的max_len=128不一致？请问这个怎么理解呢？

**Comment by PROoshio** [comment]
https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/tokenizing_ernie.py#L195 这行代码应该是min(half, len1), max(
half, seqlen - len1)
