### ISSUE TITLE
/dev/shm没有写权限，是否影响CPU多核训练性能

### ISSUE THREAD

**Issue by yzhw9981** [PaddlePaddle/ERNIE#636]
厂内MPI集群，用CPU多核训练，export了CPU_NUM=16，但是从监控看使用的核数只有8核，比设定值少了一半（使用了dataset，使用train_exe.train_from_dataset输入训练数据，dataset线程数设置了16）
看日志有一个报错信息，
/home/disk1/normandy/maybach/app-user-20210311235839-11063/workspace/python27-gcc820/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:38: UserWarning: [Errno 13] Permission denied. joblib will operate in serial mode
warnings.warn('%s. joblib will operate in serial mode' % (e,))
不清楚/dev/shm不可用是否影响了CPU多核性能的使用

**Comment by Irene-smile** [comment]
你可以如流联系下 zhuxiaolin03  ,你这个是环境问题，需要找下集群的同学
