### ISSUE TITLE
Paddle-Inference-Demo  ernie-varlen 运行报错 TensorRT's tensor input requires at least 2 dimensions, but input read_file_0.tmp_0 has 1 dims.

### ISSUE THREAD

**Issue by ustcdane** [PaddlePaddle/ERNIE#637]
运行 demo  ernie-varlen 
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/ernie-varlen

Linux环境：
CentOS Linux release 7.4.1708 (Core) 
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

前向库：
https://paddle-inference-lib.bj.bcebos.com/2.0.0-rc0-gpu-cuda10-cudnn7-avx-mkl/paddle_inference.tgz
模型：
demo页面自带的 ernie_model_4.tar.gz
TR:
TensorRT-6.0.1.5.CentOS-7.6.x86_64-gnu.cuda-10.0.cudnn7.6.tar.gz
编译通过，运行模型出现如下错误：

./build/ernie_varlen_test --model_dir=./ernie_model_4

报错：

> I0316 20:46:29.055225 163963 tensorrt_subgraph_pass.cc:118] ---  detect a sub-graph with 81 nodes

W0316 20:46:29.058228 163963 tensorrt_subgraph_pass.cc:293] The Paddle lib links the 6015 version TensorRT, make sure the runtime TensorRT you are using is no less than this version, otherwise, there might be Segfault!
I0316 20:46:29.058288 163963 tensorrt_subgraph_pass.cc:329] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0316 20:46:29.536973 163963 op_converter.h:187] trt input [matmul_0.tmp_0] dynamic shape info not set, please check and retry.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

>   --------------------------------------
> C++ Traceback (most recent call last):
>   --------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString()
> ----------------------
> Error Message Summary:
> ----------------------
> InvalidArgumentError: TensorRT's tensor input requires at least 2 dimensions, but input read_file_0.tmp_0 has 1 dims.
  [Hint: Expected shape.size() > 1UL, but received shape.size():1 <= 1UL:1.] (at /paddle/paddle/fluid/inference/tensorrt/engine.h:78)

**Comment by ustcdane** [comment]
@NHZlX  https://github.com/PaddlePaddle/Paddle/issues/25107  辛苦帮忙看下 Thanks

**Comment by zlsh80826** [comment]
Paddle-Inference-Demo varlen feature 需求 tensorrt 7.2 以上

**Comment by ustcdane** [comment]
> 
> 
> Paddle-Inference-Demo varlen feature 需求 tensorrt 7.2 以上

多谢~
