### ISSUE TITLE
ernie gen的超参length_penalty代表什么呢？什么情况需要修改？

### ISSUE THREAD

**Issue by gaolexx** [PaddlePaddle/ERNIE#638]
ernie gen的超参length_penalty代表什么呢？什么情况需要修改？

**Comment by Meiyim** [comment]
具体含义可以参考beam_seach相关教程。用于防止生成过长的句子。

**Comment by network-opinion** [comment]
请问一下，ernie-gen更改哪个超参可以生成长句子呢，我想做文本摘要，但是卡在50个汉字不动了
