### ISSUE TITLE
The exact English pretraining data and Chinese pretraining data that are exact same to the BERT paper's pretraining data.

### ISSUE THREAD

**Issue by guotong1988** [PaddlePaddle/ERNIE#639]
Any one know where to get them?
Thank you and thank you.

**Comment by OleNet** [comment]
For english data, only book-corpus cannot be downloaded as far as I know, the wikipedia corpus can still be downloaded, you may search "wiki dump" in search engine for more information.
For Chinese dataset, some dataset are in private, but you can still search "wikipedia cn corpus" in search engine for more information.
