### ISSUE TITLE
中文ERNIE 2.0 版本的预训练模型是否会提供？

### ISSUE THREAD

**Issue by linmuchuiyang** [PaddlePaddle/ERNIE#640]
看到网页上提供了ERNIE 1.0版本的中文预训练模型，但还是base的，后面会提供更多的关于中文的预训练模型吗，尤其是ERNIE 2.0版本的。

**Comment by Irene-smile** [comment]
目前开源，如果您想使用ERNIE2.0，目前有2种方式：
1.通过EasyDL平台：https://ai.baidu.com/easydl/nlp/ 目前平台支持文本分类-单标签、文本分类-多标签、情感倾向分析、文本实体抽取、文本实体关系抽取、短文本相似度任务，后续还将继续新增常用任务，通过ERNIE2.0完成上述任务，效果更好。
2.下载文心NLP开发套件：https://wenxin.baidu.com/wenxin/sdk 可以申请旗舰版的下载，旗舰版支持ERNIE2.0。

**Comment by Irene-smile** [comment]
暂时没有开源，如果您想使用ERNIE2.0，目前有2种方式：
1.通过EasyDL平台：https://ai.baidu.com/easydl/nlp/ 目前平台支持文本分类-单标签、文本分类-多标签、情感倾向分析、文本实体抽取、文本实体关系抽取、短文本相似度任务，后续还将继续新增常用任务，通过ERNIE2.0完成上述任务，效果更好。
2.下载文心NLP开发套件：https://wenxin.baidu.com/wenxin/sdk 可以使用企业免费版或者企业旗舰版，旗舰版已经支持ERNIE2.0，免费版将在4月支持ERNIE2.0。
