### ISSUE TITLE
第一次 eval 之后 50 step 就卡死，稳定复现，请问可能是什么原因？

### ISSUE THREAD

**Issue by modkzs** [PaddlePaddle/ERNIE#643]
![image](https://user-images.githubusercontent.com/4951846/114339018-e122a880-9b86-11eb-85d9-1048d46f256e.png)

**Comment by OleNet** [comment]
是不是遇到空数据了，或者数据读完了。
根据内部数据流的写法，怀疑是在等待数据，倒推回来似乎就是数据读完了。可以先check下。

**Comment by modkzs** [comment]
> 是不是遇到空数据了，或者数据读完了。
> 根据内部数据流的写法，怀疑是在等待数据，倒推回来似乎就是数据读完了。可以先check下。

我试过把 evel 的 step 调大到 90000，代码是可以正常跑到 eval 结束，在 eval 之后 50 step 继续卡住了，目前看跟数据没关系，

**Comment by OleNet** [comment]
你是多卡运行吗？

**Comment by modkzs** [comment]
> 你是多卡运行吗？

8卡运行的

**Comment by jeffzhengye** [comment]
> 是不是遇到空数据了，或者数据读完了。
> 根据内部数据流的写法，怀疑是在等待数据，倒推回来似乎就是数据读完了。可以先check下。

paddle 一个最大的问题就是卡死或者崩溃都不能提示可debug的信息，
