### ISSUE TITLE
请问有propeller的相关资料吗或者使用说明

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/ERNIE#645]
1、propeller的作用和功能是什么样的?有相关的使用说明吗
2、ernie动态图训练保存模型保存的是.pbparams的格式，这个和checkpoint模型有什么区别，或者说动态图如何保存称为checkpoint格式的模型？

**Comment by Meiyim** [comment]
duplicate of https://github.com/PaddlePaddle/Paddle/issues/32310
