### ISSUE TITLE
预处理数据的问题

### ISSUE THREAD

**Issue by BucherLi** [PaddlePaddle/ERNIE#65]
“”基于百科类、资讯类、论坛对话类数据构造具有上下文关系的句子对数据，利用百度内部词法分析工具对句对数据进行字、词、实体等不同粒度的切分”（这个能给个切分后的例子吗，一个样本有两句?）

**Comment by tianxin1860** [comment]
是的，一条样本包含2句话，明文id化后的[数据示例](https://github.com/PaddlePaddle/LARK/tree/develop/ERNIE/data) 可以参考这里
