### ISSUE TITLE
请问后续会开源ERNIE-Gram的预训练代码吗？

### ISSUE THREAD

**Issue by RyanHuangNLP** [PaddlePaddle/ERNIE#671]
想了解一下，有开源ERNIE-Gram的预训练代码的计划吗？

**Comment by nbcc** [comment]
目前暂无计划，对复现策略细节感兴趣，可以关注论文[方法和附录-A](https://arxiv.org/abs/2010.12148)

**Comment by ume-technology** [comment]
> 目前暂无计划，对复现策略细节感兴趣，可以关注论文[方法和附录-A](https://arxiv.org/abs/2010.12148)

大佬，小白问一个问题。
我看到这个问题以后我有一个疑惑：ERNIE-GRAM 相关的代码是一个需要传入 pretrain-model 文件才可以运行的代码。那 ERNIE-GRAM 这个分支代码就不是预训练一个语言模型的代码， 也就是说我想要看论文中关于 ERNIE 模型结构的代码来训练一个自己数据的预训练模型是不可以的（如题主所述，是因为您这套训练模型的代码还没有开源是么？），那如果没有开源模型结构的代码，您在 readme 中给出的数据集中包含 trian  dev  test 有什么意义呢？我不是也不能训练么？您是单纯为了让人可以复现结果么？如果是，那我的预训练模型也是从您这里直接 down 下来的，那复现的结果肯定和论文给出的结果没有偏差了，所以说您给出的这个 ERNIE-GRAM 这套代码有什么价值呢？（没有任何贬义情感，就是关于这里面的概念性理解产生了疑惑，希望大佬不吝赐教，让我拨开云雾）。

**Comment by ume-technology** [comment]
> 目前暂无计划，对复现策略细节感兴趣，可以关注论文[方法和附录-A](https://arxiv.org/abs/2010.12148)

学生自学， 问题可能有点小白。  还是希望您能解答一下。

**Comment by nbcc** [comment]
> > 目前暂无计划，对复现策略细节感兴趣，可以关注论文[方法和附录-A](https://arxiv.org/abs/2010.12148)
> 
> 学生自学， 问题可能有点小白。 还是希望您能解答一下。

预训练技术本身可以认为是一种高级的参数初始化方式。预训练模型提供了神经网络参数初始化后，需就在下游应用任务继续训练（fine-tuning）。
