### ISSUE TITLE
单机多卡训练时加载预训练模型出错

### ISSUE THREAD

**Issue by junfeizhu** [PaddlePaddle/ERNIE#679]
PaddlePaddle版本：2.0.2
GPU：GTX 1080 Ti *4
系统环境：centos 7, python 3.7

在使用 python -m paddle.distributed.launch normaltrain.py 进行单机多卡训练时出错。经过试验发现是在载入预训练模型时出了问题。在载入ERNIE模型时报如下错误：

![image](https://user-images.githubusercontent.com/32788240/119588204-e4a28400-be02-11eb-968f-66ae375aa58e.png)

但是在不加载任何预训练模型，只使用基础API搭建自己的模型时可以用单机多卡训练。

并且对于ERNIE，使用单机单卡去微调是完全没有问题的。

我已经在Paddle提了issue并被建议到ERNIE来提issue。
https://github.com/PaddlePaddle/Paddle/issues/33012#issue-896323645

**Comment by nbcc** [comment]
git clone 最新的 ernie 工程试试，感觉是 https://github.com/PaddlePaddle/ERNIE/pull/673 这个问题
