### ISSUE TITLE
实体之间的关系如何提取和表达？

### ISSUE THREAD

**Issue by yangxg** [PaddlePaddle/ERNIE#68]
介绍中提到：**“ERNIE 通过学习词与实体的表达，使模型能够建模出『哈尔滨』与『黑龙江』的关系，学到『哈尔滨』是 『黑龙江』的省会以及『哈尔滨』是个冰雪城市。”**

想问一下模型是如何规范的表达“哈尔滨”、“黑龙江”这些不同实体之间的关系的？ 有程序接口或者具体示例吗？ 谢谢了！

**Comment by jtyoui** [comment]
同问

**Comment by zhouchx** [comment]
同求,我也没看到代码里任何关于entity embedding的说明,只有和Bert一样的输入...
模型在finetune的时候是如何对输入句子进行实体识别以及转化成词向量的代码里没有找到...
