### ISSUE TITLE
ERINIE-doc的预训练数据

### ISSUE THREAD

**Issue by xyltt** [PaddlePaddle/ERNIE#687]
请问，ERINIE-doc的预训练数据的CC-NEWS和STORIES的获取和处理方式能分享一下吗？

**Comment by dingsiyu** [comment]
你好，数据可以向原作者申请 (https://github.com/pytorch/fairseq/tree/master/examples/roberta)，我们无权公开，关于数据处理，我们这边仅做了简单的数据去重。

**Comment by xyltt** [comment]
> 你好，数据可以向原作者申请 ([https://github.com/pytorch/fairseq/tree/master/examples/roberta)，我们无权公开，关于数据处理，我们这边仅做了简单的数据去重。](https://github.com/pytorch/fairseq/tree/master/examples/roberta)%EF%BC%8C%E6%88%91%E4%BB%AC%E6%97%A0%E6%9D%83%E5%85%AC%E5%BC%80%EF%BC%8C%E5%85%B3%E4%BA%8E%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86%EF%BC%8C%E6%88%91%E4%BB%AC%E8%BF%99%E8%BE%B9%E4%BB%85%E5%81%9A%E4%BA%86%E7%AE%80%E5%8D%95%E7%9A%84%E6%95%B0%E6%8D%AE%E5%8E%BB%E9%87%8D%E3%80%82)

谢谢，请问你们是向原作者申请的吗？还是自己抽取？因为我看原作者在issue里提到他们因为许可证问题也无法公开（https://github.com/pytorch/fairseq/issues/2947）。
