### ISSUE TITLE
关于ernie-doc整篇文档的分类处理

### ISSUE THREAD

**Issue by Phoebe0126** [PaddlePaddle/ERNIE#688]
![2B59A35A-1A3A-4B1C-9EAE-936F66390B86](https://user-images.githubusercontent.com/43496733/120157666-d8189400-c225-11eb-94a8-09a0a2e24a5c.jpeg)
请问论文中的这个处理具体在代码文件的哪一部分呢？

**Comment by zpp13** [comment]
在读取数据时就做了分割了

**Comment by Phoebe0126** [comment]
> 在读取数据时就做了分割了

分割长文本为不同的chunk之后，各个chunk会打乱，最终的长文本分类结果如果获得呢？貌似代码中没有看到按照原有顺序拼接chunk的向量并以最后的[CLS]进行分类。

**Comment by zpp13** [comment]
没有看到打乱chunk的过程，可能是我只找了几段自己感兴趣的代码看。
不过我在看create_model的时候，看到cls_feats = ernie_doc.get_pooled_output()，我认为这就是在以最后的[CLS]进行分类了
