### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version

### ISSUE THREAD

**Issue by xingzhoupy** [PaddlePaddle/ERNIE#69]
Traceback (most recent call last):
  File "/tmp/pycharm_project_909/ERNIE/run_classifier.py", line 277, in <module>
    main(args)
  File "/tmp/pycharm_project_909/ERNIE/run_classifier.py", line 43, in main
    place = fluid.CUDAPlace(0)
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/paddle/paddle/fluid/pybind/pybind.cc:731]
PaddlePaddle Call Stacks: 
0       0x7fb5162d498dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7fb5162d4cd7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fb5162b7114p
3       0x7fb5162fc19ep
4             0x4a9151p _PyCFunction_FastCallDict + 513
5             0x451798p _PyObject_FastCallDict + 520
6             0x45187bp _PyObject_Call_Prepend + 203
7             0x451450p PyObject_Call + 96
8             0x4c748bp
9             0x4bebeap
10            0x451632p _PyObject_FastCallDict + 162
11            0x5400f5p
12            0x5451dcp _PyEval_EvalFrameDefault + 15980
13            0x53f331p
14            0x5404c7p
15            0x5451dcp _PyEval_EvalFrameDefault + 15980
16            0x53ffa1p
17            0x540de0p PyEval_EvalCode + 96
18            0x4266f8p PyRun_FileExFlags + 360
19            0x4268ddp PyRun_SimpleFileExFlags + 221
20            0x43b11ap Py_Main + 3418
21            0x41d892p main + 354
22      0x7fb57f9ab445p __libc_start_main + 245
23            0x41d950p
cuda 9 cudnn7 tensorflow-gpu正常运行，这个是什么问题，求解决

**Comment by tianxin1860** [comment]
你安装的 paddlepaddle 是CPU版本的，安装 GPU 版本就好了；
