### ISSUE TITLE
请问想做个图文检索的下游任务，用什么模型好

### ISSUE THREAD

**Issue by Yaningkong** [PaddlePaddle/ERNIE#698]
我看到unimo与vil两个模型好像都能做，两者在这方面有什么区别，请问哪个效果好点或者更好实现点？

**Comment by yinweichong** [comment]
这两个预训练方法的区别参考论文，具体下游任务的实现参考代码。Flickr30K IR&TR效果上，unimo略好于vil，详细的效果对比也请参考论文。
