### ISSUE TITLE
ernie-doc的中文阅读理解效果为什么比不上clue里的Bert-base？

### ISSUE THREAD

**Issue by lxww302** [PaddlePaddle/ERNIE#699]
![image](https://user-images.githubusercontent.com/68112258/121523273-9c9d7700-ca28-11eb-9f0d-2a867171b8be.png)
如图，在CMRC2018数据集上，ernie-doc汇报的结果是76.1，CLUE榜单上bert-base是80.5；在C3数据集上，ernie-doc汇报的结果是76.5，CLUE榜单上bert-base是77.03。看起来不如bert-base，想问下为啥是这样，是训练或者评估的设置上有什么区别吗？

**Comment by dingsiyu** [comment]
榜单上的结果一般都会做集成，bert_base单模型的结果可以参考CLUE的github官网（ https://github.com/CLUEbenchmark/CLUE )

**Comment by lxww302** [comment]
好的，多谢解答
