### ISSUE TITLE
/paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed

### ISSUE THREAD

**Issue by bbingy** [PaddlePaddle/ERNIE#70]
Load pretraining parameters from /home/lby/ERNIE_stable/params.
/paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.
Traceback (most recent call last):
  File "run_classifier.py", line 276, in <module>
    main(args)
  File "run_classifier.py", line 195, in main
    train_exe.run(fetch_list=[])
  File "/home/lby/.conda/envs/paddlepaddle/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 303, in run

1       0x7f9b22cf2759p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f9b247840c6p
3       0x7f9b247a67d4p paddle::platform::TemporaryAllocator::Release(std::function<void ()> const&) + 100
4       0x7f9b247860e1p paddle::platform::CUDADeviceContext::Wait() const + 113
5       0x7f9b24506a68p paddle::framework::details::ScopeBufferedSSAGraphExecutor::WaitComputationalStreams() + 120
6       0x7f9b24506072p paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 1794
7       0x7f9b22e2d872p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
8       0x7f9b22ce2c7ep
9       0x7f9b22d1d79ep
10      0x55838e22b744p _PyCFunction_FastCallDict + 340
11      0x55838e2b257ep
12      0x55838e2d738ap _PyEval_EvalFrameDefault + 778
13      0x55838e2abbfep
14      0x55838e2ac771p
15      0x55838e2b2505p
16      0x55838e2d8147p _PyEval_EvalFrameDefault + 4295
17      0x55838e2ac53bp
18      0x55838e2b2505p
19      0x55838e2d738ap _PyEval_EvalFrameDefault + 778
20      0x55838e2ad289p PyEval_EvalCodeEx + 809
21      0x55838e2ae01cp PyEval_EvalCode + 28
22      0x55838e3303c4p
23      0x55838e3307c1p PyRun_FileExFlags + 161
24      0x55838e3309c3p PyRun_SimpleFileExFlags + 451
25      0x55838e3344b3p Py_Main + 1555
26      0x55838e1fd02ep main + 238
27      0x7f9b5c84db97p __libc_start_main + 231
28      0x55838e2dde0ep

多分类会报这样的错误，请问是否可以使用预训练好的模型进行多分类呢？可以的话应该修改哪里呢？

**Comment by tianxin1860** [comment]
通过 run_classifier.py 脚本中的  `--num_labels`  配置自己任务的类别个数即可

**Comment by bbingy** [comment]
谢谢！可是`--num_labels`不是指的标签个数吗？我使用的数据是多类别多标签的。想要同时对20个类别做预测，每一类有4个标签。 @tianxin1860

**Comment by bbingy** [comment]
找到原因了，是因为label的数值没有全都大于零。
