### ISSUE TITLE
ernie-doc在DuReader数据上的实验

### ISSUE THREAD

**Issue by lxww302** [PaddlePaddle/ERNIE#701]
![image](https://user-images.githubusercontent.com/68112258/122033719-5f0f6400-ce03-11eb-92a6-75135c1a2a33.png)
如图，公开的DuReader数据有zhidao和search两个dev集，其中各有5000个question，好像跟这里的统计不一致。请问是有一个ernie-doc的非公开子集吗，方便将其开源吗？这样有新的工作可以跟贵工作更公平的比较。

**Comment by dingsiyu** [comment]
这个版本的dureader数据集是公司为发布正式版dureader数据集而推出的内测版本，不会计划开源，但目前百度官方已经开放了正式版的Dureader数据集，包括dureader_robust, dureader_checklist, dureader_yesorno，其中dureader_robust和dureader_yesorno被收录至千言数据集 (https://aistudio.baidu.com/aistudio/competition/detail/49/?isFromLUGE=TRUE), 
支持实时评测，欢迎使用
