### ISSUE TITLE
ernie-doc的读两遍和memory传递机制是怎么实现的？

### ISSUE THREAD

**Issue by lxww302** [PaddlePaddle/ERNIE#703]
1. task_reader里的self.features_all里面的特征只存了按segment切分的一遍特征，模型里也没有看到哪里做了特殊处理，请问这个读两遍机制是在哪里实现的？
2. memory传递倒是看到了相关代码，可是没有看到同一个query不同segment之间memory的传递机制

**Comment by sjy1203** [comment]
1. repeat_input 控制了是否读取两遍，具体实现在这一行：https://github.com/PaddlePaddle/ERNIE/blob/2641a12a472a94f5b719dc59fb7c6f231ac93d42/ernie-doc/reader/task_reader.py#L578
2. 对于mrc任务，因为考虑到query比较短，而且任务信息比较丰富，所以会把query与每一个segment都会进行拼接，而只有doc会进行滑动切分，

**Comment by lxww302** [comment]
> 1. repeat_input 控制了是否读取两遍，具体实现在这一行：https://github.com/PaddlePaddle/ERNIE/blob/2641a12a472a94f5b719dc59fb7c6f231ac93d42/ernie-doc/reader/task_reader.py#L578
> 2. 对于mrc任务，因为考虑到query比较短，而且任务信息比较丰富，所以会把query与每一个segment都会进行拼接，而只有doc会进行滑动切分，

1. repeat_input 参数看到了，但是看finetune脚本似乎并没有开启，我尝试开启发现效果变差了。
2. 我想问的是memory的传递问题，一条case如果document过长，ernie-doc会把这条case切成多个segment，这些segment放在相邻的batch里，通过memory传递给下个batch。我理解一个batch有的case在下个batch有segment需要传递，有的case就这一个segment，它的memory就不需要传给下个batch了；但看代码似乎是一个batch里的所有case产生的memory都会传给下个batch，感觉有点奇怪

**Comment by jc-ryan** [comment]
> > 1. repeat_input 控制了是否读取两遍，具体实现在这一行：https://github.com/PaddlePaddle/ERNIE/blob/2641a12a472a94f5b719dc59fb7c6f231ac93d42/ernie-doc/reader/task_reader.py#L578
> > 2. 对于mrc任务，因为考虑到query比较短，而且任务信息比较丰富，所以会把query与每一个segment都会进行拼接，而只有doc会进行滑动切分，
> 
> 1. repeat_input 参数看到了，但是看finetune脚本似乎并没有开启，我尝试开启发现效果变差了。
> 2. 我想问的是memory的传递问题，一条case如果document过长，ernie-doc会把这条case切成多个segment，这些segment放在相邻的batch里，通过memory传递给下个batch。我理解一个batch有的case在下个batch有segment需要传递，有的case就这一个segment，它的memory就不需要传给下个batch了；但看代码似乎是一个batch里的所有case产生的memory都会传给下个batch，感觉有点奇怪

我也注意到了这个问题，相邻batch之间如果同属一个长篇章是没有问题，但属于不同的篇章的batch也进行了memory的传递；并且repeat_input并未开启，那何来的retrospect阶段呢
