### ISSUE TITLE
pretrain model差异

### ISSUE THREAD

**Issue by kaishxu** [PaddlePaddle/ERNIE#710]
哈咯，想问下，中文ERNIE_1.0_max-len-512和中文model-ernie1.0.1有什么差异吗？我想自己预训练ERNIE模型，然后再在ERNIE-GEN上finetune，不知道会不会出问题？

**Comment by YuxiangLu** [comment]
ernie 1.0 对应的是max len 128的版本，ernie1.0.1对应的是max len 512的版本。

**Comment by YuxiangLu** [comment]
> 哈咯，想问下，中文ERNIE_1.0_max-len-512和中文model-ernie1.0.1有什么差异吗？我想自己预训练ERNIE模型，然后再在ERNIE-GEN上finetune，不知道会不会出问题？

ERNIE 1.0指的是 max len 128的版本，ERNIE 1.0.1指的是max len 512的版本。为啥不直接预训练一个ERNIE-GEN呢？

**Comment by kaishxu** [comment]
> > 哈咯，想问下，中文ERNIE_1.0_max-len-512和中文model-ernie1.0.1有什么差异吗？我想自己预训练ERNIE模型，然后再在ERNIE-GEN上finetune，不知道会不会出问题？
> 
> ERNIE 1.0指的是 max len 128的版本，ERNIE 1.0.1指的是max len 512的版本。为啥不直接预训练一个ERNIE-GEN呢？

你说的对！现在我考虑直接训练ERNIE-GEN了！不过这两个：https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz和https://ernie.bj.bcebos.com/ERNIE_1.0_max-len-512.tar.gz 应该都是512长度的吧？我看他都直接后缀说明了max len 512。🤣
