### ISSUE TITLE
PADDLE  出现异常，Google or  BAIDU 全部找不到相关的文章

### ISSUE THREAD

**Issue by ume-technology** [PaddlePaddle/ERNIE#711]
如题所述，这样的问题导致学习起来太费劲了。  不想读了。。。。。。。。大家有什么好的学习办法嘛？

**Comment by nbcc** [comment]
> 如题所述，这样的问题导致学习起来太费劲了。 不想读了。。。。。。。。大家有什么好的学习办法嘛？

Paddle 一个重要的方式是，在框架开源之外，努力建设基于框架实现的各大类AI任务的高质样例实现，看 demo 学起来更快，见：https://github.com/PaddlePaddle/PaddleNLP
