### ISSUE TITLE
CPU 跑 gram 分支的 NER demo 报错

### ISSUE THREAD

**Issue by ume-technology** [PaddlePaddle/ERNIE#712]
AssertionError: The setting of Parameter-Server must has server_num or servers.

报错信息如上。 找了半天没有找到相关 paddle 的报错信息。 这种是 CPU 的任务启动不对？  CPU 的任务应该怎么启动

**Comment by ume-technology** [comment]
求各位大佬指点迷津

**Comment by nbcc** [comment]
> AssertionError: The setting of Parameter-Server must has server_num or servers.
> 
> 报错信息如上。 找了半天没有找到相关 paddle 的报错信息。 这种是 CPU 的任务启动不对？ CPU 的任务应该怎么启动

不支持 ps 方式训练（一般是 CPU 场景下默认的训练方式）；
