### ISSUE TITLE
When you unify NLU and NLG in the same model, do you apply uni-directional masking?

### ISSUE THREAD

**Issue by cmsflash** [PaddlePaddle/ERNIE#715]
NLG models usually use uni-directional masking, i.e. a token can only attend to earlier tokens, not later tokens. NLU models usually don't use uni-directional masking and attend bi-directionally. How do you address this problem?

**Comment by oyjxer** [comment]
using bi-directionally mask in nlu task, while using uni-directional mask in nlg task

**Comment by cmsflash** [comment]
But I thought we can only apply one type of masking in the encoder?
