### ISSUE TITLE
ERNIE-M Release Data

### ISSUE THREAD

**Issue by sumanthd17** [PaddlePaddle/ERNIE#717]
I saw an older issue which said ERNIE-M is expected to be released in May 2021, Wanted to know the expected timeline for ERNIE-M release. Thanks

**Comment by ricardorei** [comment]
Is there any news on the release of ERNIE-M?

**Comment by wangshuohuan** [comment]
The code and models of ERNIE-M had been available at https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m .
