### ISSUE TITLE
可否提供 ERNITE-ViL 下游任务所用的特征

### ISSUE THREAD

**Issue by coldmanck** [PaddlePaddle/ERNIE#720]
ERNIE-Vil 的下游任务 VQA, IR&TR 使用到 bottom-up attention 提取特征, 然而提取所需的tool需要使用到的caffe不好安装, 请问能提供下载链接吗?

**Comment by yinweichong** [comment]
vilbert的repo提供了部分butd的特征，可直接使用https://github.com/jiasenlu/vilbert_beta/tree/master/data
