### ISSUE TITLE
请问是否有计划提供中文ERNIE2.0和ERNIE3.0

### ISSUE THREAD

**Issue by lbda1** [PaddlePaddle/ERNIE#725]
请问是否有具体的时间计划对外提供中文ERNIE2.0和ERNIE3.0

**Comment by nbcc** [comment]
> 请问是否有具体的时间计划对外提供中文ERNIE2.0和ERNIE3.0

ernie-gram 中文预训练模型已经开源了，介绍见 https://github.com/PaddlePaddle/ERNIE/tree/develop/ernie-gram

典型中文任务对比效果见[论文-实验部分 ](https://arxiv.org/abs/2010.12148)

**Comment by lbda1** [comment]
请问ernie-gram就是ernie3.0吗，ernie-gram和ernie3.0是不同的两个模型吧



在 2021-08-05 10:52:50，"nbcc" ***@***.***> 写道：

请问是否有具体的时间计划对外提供中文ERNIE2.0和ERNIE3.0

ernie-gram 中文预训练模型已经开源了，介绍见 https://github.com/PaddlePaddle/ERNIE/tree/develop/ernie-gram

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lbda1** [comment]
> > 请问是否有具体的时间计划对外提供中文ERNIE2.0和ERNIE3.0
> 
> ernie-gram 中文预训练模型已经开源了，介绍见 https://github.com/PaddlePaddle/ERNIE/tree/develop/ernie-gram
> 
> 典型中文任务对比效果见[论文-实验部分 ](https://arxiv.org/abs/2010.12148)

ernie3.0和ERNIE3.0是不同的工作吧
