### ISSUE TITLE
Ernie1.0的dialog language model

### ISSUE THREAD

**Issue by nkjsy** [PaddlePaddle/ERNIE#726]
请问Ernie1.0里的dialog language model预训练任务，这种多于2句的任务是怎么进行数据预处理的？处理的代码在哪里？没有找到。
另外fine tune的时候也可以用这种多句的任务吗？该如何输入token type id呢？是输入0,1,2...吗？

**Comment by WeiyueSu** [comment]
dialogr任务输入是句子pair和2分类结果，不需要额外预处理。finetune阶段还是只有0 1两种token type

**Comment by nkjsy** [comment]
论文的图片里显示dialog任务里的token type是Q，R，Q。。。您的意思是finetune阶段就是0对应Q，1对应R吗？这里token type应该理解为对话角色编号，而不是句子序列编号？

另外如果这样理解的话，预处理还是要特殊处理一下？比如truncate的逻辑，应该改成3句话中最长的一句进行截断？

**Comment by nkjsy** [comment]
论文的图片里显示dialog任务里的token type是Q，R，Q。。。您的意思是finetune阶段就是0对应Q，1对应R吗？这里token type应该理解为对话角色编号，而不是句子序列编号？

另外如果这样理解的话，预处理还是要特殊处理一下？比如truncate的逻辑，应该改成3句话中最长的一句进行截断？
