### ISSUE TITLE
ImportError: cannot import name 'feature_pb2' from 'propeller.paddle.data' (/data/home/scv1927/archive/ERNIE/propeller/paddle/data/__init__.py)

### ISSUE THREAD

**Issue by GuocaiL** [PaddlePaddle/ERNIE#740]
ImportError: cannot import name 'feature_pb2' from 'propeller.paddle.data' (/data/home/scv1927/archive/ERNIE/propeller/paddle/data/__init__.py)

**Comment by GuocaiL** [comment]
请问各位大佬，这个问题怎么解决呢

**Comment by ABAPPLO** [comment]
把   make_pretrain_data.py 文件中的  from propeller.paddle.data import feature_pb2, example_pb2
  改成  from propeller.data import feature_pb2, example_pb2

**Comment by crrongyan** [comment]
~
