### ISSUE TITLE
run_config = dict(default_run_config, **json.loads(args.run_config))   File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/__init__.py", line 348, in loads     return _default_decoder.decode(s)   File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/decoder.py", line 337, in decode     obj, end = self.raw_decode(s, idx=_w(s, 0).end())   File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/decoder.py", line 355, in raw_decode     raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by GuocaiL** [PaddlePaddle/ERNIE#744]
![image](https://user-images.githubusercontent.com/43643599/133193974-1f606206-bb67-4dd3-851a-5c6ccc306640.png)
run_config = dict(default_run_config, **json.loads(args.run_config))
  File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/home/scv1927/.conda/envs/py37/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by crrongyan** [comment]
我也遇到了这个问题，我已经折腾了快两天了
