### ISSUE TITLE
develp 分支 基于paddle 2.0 的 ERNIE 1.0 继续pretrain 训练无法跑通 经分析是代码有问题

### ISSUE THREAD

**Issue by nlper-77** [PaddlePaddle/ERNIE#746]
1. propeller 有问题 需要用repro分支下的propeller 
2. pretrain.py  中 make_pretrain_dataset() 函数 导致程序跑不起来 这个坑太大 改不动，跑的时候会报train_ds 不是 paddle.io.Dataset的子类的错       train_ds = make_pretrain_dataset('train', args.data_dir, vocab=tokenizer.vocab, args=args)

**Comment by ZeyuChen** [comment]
@nlper-77 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
可以试试PaddleNLP的这个版本，包含了完整的预训练流程。

**Comment by nlper-77** [comment]
谢谢  还是paddlenlp的代码比较清晰
