### ISSUE TITLE
ERNIE-vil的vqa任务的数据集是怎么输入的呢

### ISSUE THREAD

**Issue by Takeru0618** [PaddlePaddle/ERNIE#761]
我从VQA官网上下载了这些数据集
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/82857532/140037662-954d142c-adb0-4b37-b1c9-97f30976f52f.png">

想询问一下是怎么使用这些数据的

**Comment by BinglengTang** [comment]
代码里的输入是这样的"question_id, text, match_label, score, image_w, image_h, number_box, image_loc, image_embeddings", 前面的都可以从questions和annotations里面拿到，后面图片的使用bottom-up and top-down的特征提取器提取到的
