### ISSUE TITLE
ERNIE-M Release Data (related to #717)

### ISSUE THREAD

**Issue by ricardorei** [PaddlePaddle/ERNIE#767]
I am bumping #717 because it seems like no one replied.

Is there any release date for ERNIE-M?

**Comment by wangshuohuan** [comment]
We will release ERNIE-M in December.

**Comment by wangshuohuan** [comment]
The code and models of ERNIE-M had been available at https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m .
