### ISSUE TITLE
ernie-m下载的权重好像没有看到vocab文件？

### ISSUE THREAD

**Issue by another1s** [PaddlePaddle/ERNIE#776]
![ernie_m](https://user-images.githubusercontent.com/21125331/145760916-fa2218ae-2842-4e48-95d1-c64d364c2dc1.png)
如题，下载了ernie-m的预训练模型并用winrar在window10底下解压了。但好像只有个config还有param文件夹---里面是每一层的参数
，没有看到用于初始化tokenizer的vocab或者其他类似的文件。。
请问这个是我下载的有错误么，还是说解压的方式不对

**Comment by oyjxer** [comment]
你好，ernie-m的vocab.txt及相关文件在configs目录里https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m/configs

**Comment by another1s** [comment]
> 你好，ernie-m的vocab.txt及相关文件在configs目录里https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m/configs

多谢指教！还有个问题想确认一下，因为先前用ernie1.0印象里这个权重应该是一个.pdparams的文件，现在我解压出来好像每层都是单独一个文件，我试了下原先用的load_dygraph好像不管用了。。现在这样子要怎么读这个模型权重呢？

**Comment by another1s** [comment]
> 你好，ernie-m的vocab.txt及相关文件在configs目录里https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m/configs

抱歉我现在加载了这个piece.model文件它的词表好像跟这个vocab.txt完全对不上？我的0对应对应的是bos token，但vocab里却是‘['UNK']’。能不能麻烦给个这个tokenizer的demo。。。。

然后ernie-m的网络权重里我看到一个sent_embedding的层，它的维度是[100, 514]请问这个层具体的机制是怎样的呢？我在mbert和xlm-roberta没看到过类似的结构，烦请指点一下

**Comment by oyjxer** [comment]
目前ernie-m代码不支持动态图，请使用ernie-m代码目录的中的代码进行加载

**Comment by oyjxer** [comment]
sent_embedding并未使用，可忽略

**Comment by oyxuan-11** [comment]
> > 你好，ernie-m的vocab.txt及相关文件在configs目录里https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m/configs
> 
> 抱歉我现在加载了这个piece.model文件它的词表好像跟这个vocab.txt完全对不上？我的0对应对应的是bos token，但vocab里却是‘['UNK']’。能不能麻烦给个这个tokenizer的demo。。。。
> 
> 然后ernie-m的网络权重里我看到一个sent_embedding的层，它的维度是[100, 514]请问这个层具体的机制是怎样的呢？我在mbert和xlm-roberta没看到过类似的结构，烦请指点一下

tokenizer 的使用方式可以参考下面的链接～
https://github.com/PaddlePaddle/ERNIE/blob/e25b1cfa63000b29ce710bb0503a96a2c64a2eb3/ernie-m/reader/task_reader.py
