### ISSUE TITLE
在训练好分类模型下，怎么预测单个句子？

### ISSUE THREAD

**Issue by Inspiring26** [PaddlePaddle/ERNIE#79]

**Comment by SunnyGJing** [comment]
同求，希望早日更新 预测结果可视的功能

**Comment by nbcc** [comment]
见示例
https://github.com/PaddlePaddle/LARK/blob/68e04f38a59becb3d1baa6d127e8657e486e6415/ERNIE/script/run_ChnSentiCorp.sh
