### ISSUE TITLE
请问有CV大模型吗

### ISSUE THREAD

**Issue by raychiu0202** [PaddlePaddle/ERNIE#796]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raychiu0202** [comment]
我看到最新的资料显示文心大模型目前没有开放CV大模型，请问什么时候开放呢？

**Comment by ZeyuChen** [comment]
CV大模型相关内容会开放在 https://github.com/PaddlePaddle/VIMER 这个repo。
@raychiu0202
