### ISSUE TITLE
ernie-gram

### ISSUE THREAD

**Issue by wjzqbb** [PaddlePaddle/ERNIE#797]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wjzqbb** [comment]
ernie-gram模型代码正确么，为什么我跑不起来，是不是我不能只把ernie-gram那个文件单独拿出来。我的run.sh总是缺少参数。

**Comment by ZeyuChen** [comment]
> ernie-gram模型代码正确么，为什么我跑不起来，是不是我不能只把ernie-gram那个文件单独拿出来。我的run.sh总是缺少参数。

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching

试试跑一下这个ERNIE-Gram的匹配任务吧，当前的repo的模型还未完全升级到动态图。

**Comment by renyan01** [comment]
Zeyu Chen，有问题请教，编号799，期待您的回复！提个小建议，你们ERNIE项目的老师能不能提供外部的邮箱，给你们百度邮箱发邮件发不出去
