### ISSUE TITLE
关于max_seq_len的最大值是多少？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/ERNIE#82]
如题。self._max_position_seq_len = config['max_position_embeddings']，从配置读取的，是没有限制的嘛？

**Comment by tianxin1860** [comment]
_max_position_seq_len 表示 position_embedding 参数矩阵的维度，是在预训练阶段固定的，如果你从头开始预训练可以自己配置；我们使用我们发布的预训练模型做finetune, 那就保持 max_position_embeddings = 513 不变；
