### ISSUE TITLE
如果通用模型持续预训练，下游任务的模型层需要重新简单训练吗？

### ISSUE THREAD

**Issue by yayaQAQ** [PaddlePaddle/ERNIE#826]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/20497531/172976864-dbd21feb-a56e-4b3b-8c5c-13672153bfd8.png">
看论文的时候想到的，如果不需要的话，是为什么呢？任务层的效果变化幅度怎么样？下游任务可能会变得更差吗？
如果需要的话，重新一轮会需要多久呢？

**Comment by webYFDT** [comment]
下游任务进行微调要好于直接zero-shot的方式
