### ISSUE TITLE
ERNIE3.0文本生成

### ISSUE THREAD

**Issue by ssrssrcode** [PaddlePaddle/ERNIE#828]
您好，请问一下开源的ERNIE3.0模型是否支持生成任务？因为在ernie和paddlenlp项目中的example中ernie3.0均未使用于生成任务，生成任务使用的都是ernie-gen。

**Comment by webYFDT** [comment]
暂为开源ernie3.0的生成任务，不能直接将ernie3.0模型替换到本套件中的生成任务代码中
