### ISSUE TITLE
文本生成任务在推理（测试）中“infer_data_params.json”这个json文件在哪呢？

### ISSUE THREAD

**Issue by ScarletBlaze** [PaddlePaddle/ERNIE#830]
你好，我想借助你们的模型测试一下文本生成的效果，在下载了预训练模型和代码后，执行测试代码提示发现缺少“infer_data_params.json”文件，请问这个文件在哪里可以得到呢？谢谢！
![params](https://user-images.githubusercontent.com/17705192/176395078-59159b3c-430d-4d70-93d4-4fb001c96e58.png)

**Comment by webYFDT** [comment]
请问你预测的运行的代码python run_infer.py --param_path ./examples/cls_ernie_gen_infilling_ch_infer.json
cls_ernie_gen_infilling_ch_infer.json配置文件中是否配置了"inference_model_path": 路径，该路径为你训练完模型后产生的文件夹

**Comment by deandean82** [comment]
同问，根据download_ernie_gen_base_ch.sh 下载的  http://bj.bcebos.com/wenxin-models/ernie_gen_base_ch_open.tgz 模型文件中没有这个json文件

**Comment by freecui** [comment]
同问，我下载http://bj.bcebos.com/wenxin-models/ernie_3.0_base_ch_open.tgz出来的也没
![image](https://user-images.githubusercontent.com/8288975/181417834-0b48bd71-ff56-4c6e-9cd9-1f2ef6c7f8d8.png)

**Comment by freecui** [comment]
估计要先训练，然后再去推理
