### ISSUE TITLE
关于5.20开源的ERNIE-GEN模型

### ISSUE THREAD

**Issue by Kunlun-Zhu** [PaddlePaddle/ERNIE#832]
您好，感谢你们的工作，请问关于5.20开源的ERNIE-GEN模型请问相关使用有说明文档吗，和2020.5公布的ERNIE-GEN有什么区别吗。

**Comment by webYFDT** [comment]
使用说明见：https://github.com/PaddlePaddle/ERNIE/tree/94a2367ba7f0f83b48330233450ea095d8dc9382/applications/tasks/text_generation

**Comment by buluxianfeng** [comment]
W0715 03:21:37.624673 20068 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
INFO: 07-15 03:21:38: static_trainer_ernie_gen.py:441 * 139834698254144 load_model_params on static mode....
INFO: 07-15 03:21:38: static_trainer_ernie_gen.py:461 * 139834698254144 pre_train_model's name = ernie_gen_ch
INFO: 07-15 03:21:39: ernie_gen_infilling_dataset_reader.py:156 * 139834698254144 set data_generator and start.......
开始训练ERNIE-Gen后，一直停在上述界面，
没有log和model输出，已经一晚上了，请问怎么解决？@webYFDT

**Comment by freecui** [comment]
我可以跑训练，但是不跑reference
![82da32ce9b83f9988f85bc6a85ddd1c](https://user-images.githubusercontent.com/8288975/182345819-8e6331f5-f705-48b5-ad65-3e63ce982d70.png)

**Comment by yijunL** [comment]
> 使用说明见：https://github.com/PaddlePaddle/ERNIE/tree/94a2367ba7f0f83b48330233450ea095d8dc9382/applications/tasks/text_generation

这里只说明了问题生成任务，如果要进行多轮对话生成任务应该要怎么做呢
