### ISSUE TITLE
训练ERNIE-Gen报错

### ISSUE THREAD

**Issue by lcs1225** [PaddlePaddle/ERNIE#850]
按照readme中命令 python run_trainer_ernie_gen.py --param_path ./examples/cls_ernie_gen_infilling_ch.json 训练模型报错，有人遇到过这个问题吗
<img width="947" alt="7422deb7e0953cccc59db12cb902964" src="https://user-images.githubusercontent.com/29704155/184064820-4ca9a8f2-8c74-4f2d-a450-4a7f6f11d0b1.png">
![d00f952e2c0b1401d102e17bddd7228](https://user-images.githubusercontent.com/29704155/184064826-b2e11cb0-f27c-465a-b698-18d07da759cc.jpg)

**Comment by fb8py** [comment]
你好，我也碰到一样的问题。
paddlepaddle       2.3.1
Python                  3.9.11

**Comment by lcs1225** [comment]
> 

  "trainer": {
    "type" : "CustomGenerationTrainer",
    "PADDLE_PLACE_TYPE": "gpu",
    "ramdom_seed": 1,
    "save_inference_model": true,
    "train_log_step": 10,
    "is_do_train": 1,
    "is_eval_dev": 0,
    "is_eval_test": 0,
    "eval_step": 10000,
    "save_model_step": 100000000,
    "load_parameters": "",
    "load_checkpoint": "",
    "pre_train_model": [
      {
        "name": "ernie_gen_ch",
        "params_path": "../../models_hub/ernie_gen_ch_dir/params"
      }
    ],
    "output_path": "./output/ernie_gen_ch"
  }

这里的"is_eval_dev"改成0 就好了
