### ISSUE TITLE
700多M的ERNIE-VIL2 在coco-CN的跨模态检索上显著好于2.3G的华为WUKONG

### ISSUE THREAD

**Issue by bendanzzc** [PaddlePaddle/ERNIE#855]
根据两者官网和自己复现，性能基本属实，请问可以公开是如何训练的嘛？如果用的也是公开数据集，就打破了我对跨模态pretrain的模型大小和性能关系的认知。还是说ERNIE用的是 fine-tune的结果。因为我看Wukong的finetune结果和ERNIE的比较接近

**Comment by JH-Xie** [comment]
请问你的coco-CN数据集实在哪里下载的，官方链接已无法下载，能否提供一份？
