### ISSUE TITLE
官方样例训练报错ValueError: CUDA_VISIBLE_DEVICES shoule be set only 1 card if you use `python` to launch fleet program.

### ISSUE THREAD

**Issue by xiaobie-lhm** [PaddlePaddle/ERNIE#858]
![image](https://user-images.githubusercontent.com/55732208/189824257-6afa3410-b3cd-4c6e-a257-904d83d21e21.png)
![1663049808377](https://user-images.githubusercontent.com/55732208/189824389-59e622ad-f8b5-4583-9db0-8259002b8b5b.jpg)

想请大佬帮忙看下这个运行问题，我这边用的是官方给出的文本分类样例，显示无法运行，这种情况怎么处理呢？多谢啦~
https://github.com/PaddlePaddle/ERNIE

**Comment by Ryan-XC** [comment]
EXPORT CUDA_VISIBLE_DEVICES=0

**Comment by xiaobie-lhm** [comment]
多谢多谢，用的就是这个方法，已经解决了~
