### ISSUE TITLE
序列标注任务预测配置文件中修改max_seq_len值后，还需要做哪些修改

### ISSUE THREAD

**Issue by Spider4U** [PaddlePaddle/ERNIE#860]
序列标注任务中我想增加输入端文本最大长度，除了在预测配置文件中修改max_seq_len值后，还需要做哪些修改

**Comment by nTjing** [comment]
> 序列标注任务中我想增加输入端文本最大长度，除了在预测配置文件中修改max_seq_len值后，还需要做哪些修改

我想问一下 你运行序列标注任务时是否出现报错：ModuleNotFoundError: No module named 'erniekit' 是怎么解决的呢？
我已经安装了paddlenlp和paddle-gpu
