### ISSUE TITLE
文本生成官方案例 运行报错 ZeroDivisionError: float division by zero     请教解决方法

### ISSUE THREAD

**Issue by xiaobie-lhm** [PaddlePaddle/ERNIE#861]
INFO: 09-27 08:59:02: ernie_gen_infilling_dataset_reader.py:156 * 140497794008896 set data_generator and start.......
sort: multi-character tab ‘$\\t’
ERROR: 09-27 08:59:03: custom_static_generation_trainer.py:113 * 140497794008896 traceback.format_exc():Traceback (most recent call last):
  File "/paddle/ERNIE-ernie-kit-open-v1.0/applications/tasks/text_generation/trainer/custom_static_generation_trainer.py", line 107, in do_train
    self.do_evaluate(self.data_set_reader.dev_reader, InstanceName.EVALUATE, steps)
  File "/paddle/ERNIE-ernie-kit-open-v1.0/applications/tasks/text_generation/trainer/custom_static_generation_trainer.py", line 157, in do_evaluate
    self.model_class.get_metrics(fetch_output_dict, meta_info, phase, reader)
  File "/paddle/ERNIE-ernie-kit-open-v1.0/applications/tasks/text_generation/model/ernie_infilling_generation.py", line 496, in get_metrics
    eval_res = self.eval.eval(outfile, phase, reader.features[phase])
  File "../../../erniekit/metrics/gen_eval.py", line 62, in eval
    eval_res[mertric] = eval_func(refs, preds)
  File "../../../erniekit/metrics/gen_eval.py", line 75, in bleu
    return _compute_bleu(refs, preds, max_order=4)[0]
  File "../../../erniekit/metrics/gen_eval.py", line 126, in _compute_bleu
    ratio = float(translation_length) / reference_length
ZeroDivisionError: float division by zero

您好，我在运行ernie框架中的文本生成案例时，出现了这个报错，想请教下这个可以怎样解决呢？
https://github.com/PaddlePaddle/ERNIE/tree/ernie-kit-open-v1.0/applications/tasks/text_generation

**Comment by xiaobie-lhm** [comment]
<img width="455" alt="1664357839371" src="https://user-images.githubusercontent.com/55732208/192745415-57a48c9e-5584-45af-94fa-90ea8783a5fa.png">
好像是训练之后验证过程中，这个输出的文件为空所导致，想请教下这个该怎么解决呢？

**Comment by leesurelye** [comment]
我找到原因了，官方文档中在做验证的时候，将模型的输出结果放在了文件 `./output/evaluate_10.part*`（这个文件有真实的数据），然后在代码中生成使merge_cmd指令，将结果放入`./output/evaluate_10`中，但是执行指令时，指令出错，，修改一下cmd指令就行。
具体代码请见：multi_process_eval.py中的finalize_writer函数。修改merge_cmd

**Comment by xiaobie-lhm** [comment]
您好，感谢您的解答，想问一下multi_process_eval.py在哪里找到的呢，我在text_generation里面没有找到这个文件呢
![image](https://user-images.githubusercontent.com/55732208/202079777-5cc2d1c0-93e1-4481-8b2d-b7e10ade612b.png)

**Comment by leesurelye** [comment]
你好，代码在这里：https://github.com/PaddlePaddle/ERNIE/blob/ernie-kit-open-v1.0/erniekit/utils/multi_process_eval.py
请将函数finalize_writer里面的这两个变量修改为如下代码：
```python
sort_cmd = ["sort", outfile + ".part*", "-n", "-t", "\\t", "-k", str(sort_key_index)]
awk_cmd = ["awk", "-F", "\"\\t\"",  "'{print " + merge_str + "}'",  ">" + outfile]
```

**Comment by xiaobie-lhm** [comment]
太感谢了，改完之后果然解决了！
还有个问题想请教您一下，我这边用自己的数据训练，发现我训练量超过10000之后，这里都只显示evaluate_10000，是因为训练量有限制吗？还是因为评估过程当中有什么限制呢，一直没找到是什么问题
![image](https://user-images.githubusercontent.com/55732208/202114389-08f93e83-227e-4835-9380-742dde4f523d.png)

**Comment by leesurelye** [comment]
你好，请修改运行的配置文件：https://github.com/PaddlePaddle/ERNIE/blob/ernie-kit-open-v1.0/applications/tasks/text_generation/examples/cls_ernie_gen_infilling_ch.json。
将trainer中的`eval_step`修改一下就行，这个参数的意思是每执行10000step就进行一次验证。
<img width="659" alt="image" src="https://user-images.githubusercontent.com/65715863/202117979-46211cee-992e-4c73-8bc6-d63799a5077e.png">

**Comment by xiaobie-lhm** [comment]
哦哦，好的，多谢多谢，这个开源模型对训练量应该没有什么限制吧，哈哈哈，我看ERNIE Easydl那个产品对训练量是有限制到10000的，以为是这个问题
