### ISSUE TITLE
请问文本生成的最大长度在哪里设置，上限为多少？

### ISSUE THREAD

**Issue by BaiIIzt** [PaddlePaddle/ERNIE#866]
![image](https://user-images.githubusercontent.com/75989862/195072871-d08542ba-bbbf-4131-b710-fb0e8077edd2.png)
请问文本生成的最大长度在哪里设置？
我想基于该模型做摘要生成，因此把输入改成为
![Uploading image.png…]()
得到的结果为4个32个tokens的句子，想请问一下问题在哪里？感觉是参数的设置出问题了
![image](https://user-images.githubusercontent.com/75989862/195073635-33b60ff9-b0a8-46d8-8b96-4f97232c26ff.png)

**Comment by BaiIIzt** [comment]
![image](https://user-images.githubusercontent.com/75989862/195075431-f517b599-1853-4c90-b4dd-3d214ef25ecc.png)

**Comment by BaiIIzt** [comment]
谢谢

**Comment by wj-Mcat** [comment]
You can post issues in paddlenlp repo which maintains the Ernie doc model actively.
