### ISSUE TITLE
训练文本生成的时候出错

### ISSUE THREAD

**Issue by fucktx** [PaddlePaddle/ERNIE#888]
env
```
Linux version 3.10.0-1160.62.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Apr 5 16:57:59 UTC 2022

paddlenlp               2.3.5              
paddlepaddle-gpu        2.3.2 
```

ERROR: 02-20 12:04:54: custom_static_generation_trainer.py:113 * 140627310425920 traceback.format_exc():Traceback (most recent call last):
  File "/home/xx/ERNIE/applications/tasks/text_generation/trainer/custom_static_generation_trainer.py", line 107, in do_train
    self.do_evaluate(self.data_set_reader.dev_reader, InstanceName.EVALUATE, steps)
  File "/home/xx/ERNIE/applications/tasks/text_generation/trainer/custom_static_generation_trainer.py", line 149, in do_evaluate
    self.model_class.add_metric_result(cur_output_dict, phase)
  File "/home/xx/ERNIE/applications/tasks/text_generation/model/ernie_infilling_generation.py", line 414, in add_metric_result
    seq_ids = forward_output_dict["finished_ids"]
KeyError: 'finished_ids'

INFO: 02-20 12:04:54: static_trainer_ernie_gen.py:470 * 140627310425920 save model on static....

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1   paddle::framework::InterpreterCore::RunInstructionAsync(unsigned long, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)
2   paddle::framework::InterpreterCore::CheckGC(paddle::framework::Instruction const&, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1676865894 (unix time) try "date -d @1676865894" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8b0) received by PID 140307 (TID 0x7fe4a5fff700) from PID 2224 ***]

Segmentation fault

**Comment by liyunlaiii** [comment]
想问一下，这个问题解决了吗  我也遇到了同样的报错
