### ISSUE TITLE
保存模型时报错

### ISSUE THREAD

**Issue by jiyuwangbupt** [PaddlePaddle/ERNIE#889]
![image](https://user-images.githubusercontent.com/37127150/221458884-a32f0e3d-bdb1-45ea-b00b-c095d0f5499d.png)
 运行代码为：python run_trainer.py --param_path ./examples/cls_ernie_fc_ch.json

**Comment by guoguo12343** [comment]
paddle别用2.4版本的，用2.3的就可以，相对的cuda也要降到11.6，这应该是新版paddle改了什么东西。
