### ISSUE TITLE
在原先已经训练好的分类模型基础上怎么在新一批的数据中继续训练

### ISSUE THREAD

**Issue by Spider4U** [PaddlePaddle/ERNIE#891]
一开始训练的分类模型已经完成，后来有了新一批数据，我想在之前训练好的模型上继续训练新数据，我该怎么修改配置文件，谢谢！

**Comment by Josoope** [comment]
你好，请问训练json文件应该怎么配置呀

**Comment by Spider4U** [comment]
> 你好，请问训练json文件应该怎么配置呀

https://aistudio.baidu.com/aistudio/projectdetail/5255526
