### ISSUE TITLE
怎么得到单个词的word embedding vector

### ISSUE THREAD

**Issue by Walleclipse** [PaddlePaddle/ERNIE#90]
你好，
按照 [FAQ](https://github.com/PaddlePaddle/LARK/tree/develop/ERNIE#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%BE%93%E5%85%A5%E5%8F%A5%E5%AD%90%E7%BB%8F%E8%BF%87-ernie-%E7%BC%96%E7%A0%81%E5%90%8E%E7%9A%84-embedding-%E8%A1%A8%E7%A4%BA)说的那样利用 `ernir_encoder.py `可以得到 `cls_emb.npy` 和 `top_layer_emb.npy` 。但是由于position embedding的存在，`top_layer_emb.npy`  中的每个token的embedding还跟位置有关是不是？如果我想像elmo一样得到一个**字典的word embedding vector**的话该怎么操作呢？
谢谢

**Comment by tianxin1860** [comment]
top_layer_emb 中的 token embedding 是位置相关的

**Comment by Walleclipse** [comment]
好的 谢谢
