### ISSUE TITLE
下载的百度预训练模型，可以作为checkpoint继续进行训练吗？

### ISSUE THREAD

**Issue by jeremyjiao** [PaddlePaddle/ERNIE#92]
因为bert pytorch版本提供了language model fine tuning的方法，对预训练的model进行language model层面的fine tuning，或者可以理解为预训练模型上再次进行预训练。ERNIE模型现在只找到了下载的model直接进行fine tuning的方法，想知道有没有类似的language model fine tuning的方法。

**Comment by nbcc** [comment]
ERNIE 和 BERT 下均提供了 pretraining 流程。
