### ISSUE TITLE
xnli数据集复现，dev-acc:0.780,test-acc:0.770,没有达到发布的效果

### ISSUE THREAD

**Issue by shuying136** [PaddlePaddle/ERNIE#99]
直接运行 bash script/run_xnli.sh   训练后的结果与发布不对，然后把xnli训练集的空格去掉，再训练也没有达到相应的效果

**Comment by shuying136** [comment]
xnli训练集里面有空格分开，测试集与验证集里面没有分开

**Comment by tianxin1860** [comment]
所有数据集上的指标评估方式是:  同 1 个任务跑 5 次，取验证集评估结果中的 max_acc 作为 dev_acc,  取 max_dev_acc 对应的测试集评估结果作为 test_acc,  然后求 5 个 max_dev_acc 及 test_acc 均值作为最终发布的 dev_acc 和 test_acc。

**Comment by Vincent717** [comment]
hi 没有看懂呢 究竟是5次取max还是5次取平均，以及超参是怎么设置的呢。
